//! Extraction against inline sheets: every at-rule shape that names a file, the
//! package/relative split, comments, the generated-sheet banner.

use kndo_adapter_css::CssAdapter;
use kndo_contract::evidence::{FileEvidence, ImportShape, ImportTarget, MarkerTarget};

fn extract(path: &str, source: &str) -> FileEvidence {
    kndo_testkit::extract_evidence(&CssAdapter::new(), path, source)
}

fn targets(ev: &FileEvidence) -> Vec<String> {
    ev.imports
        .iter()
        .filter_map(|i| match &i.target {
            ImportTarget::Relative(s) => Some(format!("rel {s}")),
            ImportTarget::Package(s) => Some(format!("pkg {s}")),
            _ => None,
        })
        .collect()
}

#[test]
fn every_at_rule_shape_names_its_file() {
    let ev = extract(
        "src/main.css",
        r#"@import "./reset.css";
@import url(base.css);
@import url("./print.css") print;
@import 'tailwindcss';
@import "~normalize.css";
@import url("https://fonts.example.com/x.css");
@import "//cdn.example.com/y.css";

/* kndo: a comment */
body { color: red; }
"#,
    );
    assert_eq!(
        targets(&ev),
        [
            "rel ./reset.css",
            "pkg base.css",
            "rel ./print.css",
            "pkg tailwindcss",
            "pkg normalize.css",
        ]
    );
    assert!(
        ev.imports
            .iter()
            .all(|i| matches!(i.shape, ImportShape::SideEffect))
    );
    assert_eq!(ev.comments.len(), 1, "comments feed suppression");
    assert!(ev.declarations.is_empty() && ev.roots.is_empty());
}

#[test]
fn scss_modules_use_and_forward() {
    let ev = extract(
        "styles/main.scss",
        r#"@use "sass:math";
@use "tokens" as t;
@use "../theme" with ($accent: "blue");
@forward "src/list" show list-reset;
// a line comment
.a { width: math.div(1, 2); }
"#,
    );
    assert_eq!(
        targets(&ev),
        [
            "pkg sass:math",
            "pkg tokens",
            "rel ../theme",
            "pkg src/list",
        ],
        "a `with` map's strings configure, they do not import"
    );
    assert_eq!(ev.comments.len(), 1);
}

#[test]
fn a_generated_sheet_reports_its_banner_and_concludes_nothing() {
    let ev = extract(
        "dist/vendor.css",
        "/* Generated by tool X. DO NOT EDIT. */\n.legacy { color: gray; }\n",
    );
    assert!(ev.roots.is_empty(), "{:?}", ev.roots);
    assert_eq!(ev.markers.len(), 1);
    assert_eq!(ev.markers[0].on, MarkerTarget::File);
    assert_eq!(ev.markers[0].path, "generated");
    assert_eq!(
        ev.markers[0].args,
        ["/* Generated by tool X. DO NOT EDIT. */"]
    );
    let plain = extract("a.css", ".x { color: red; }");
    assert!(plain.roots.is_empty() && plain.markers.is_empty());
}
