//! The gate registry — the single source the CI workflow is GENERATED from.
//!
//! v1 kept the invariant list in three hand-synced places (a prose list, the workflow
//! steps, and the grep of `--list`), with a recorded incident: a named gate that had
//! never once passed in CI while appearing in the job list. Here the registry is the
//! only spelling: `cargo xtask gen-ci` renders `.github/workflows/v2.yml` from it, the
//! workflow's existence check greps the same names, and the `generated_ci_is_current`
//! gate fails the build when the committed file and the generator drift. Renaming or
//! deleting a gate without regenerating cannot pass.

use std::path::PathBuf;

pub struct Gate {
    /// The `#[test]` function name in `tests/gates.rs` — checked against `--list`.
    pub name: &'static str,
    /// One line of what the gate protects, rendered into the step name.
    pub invariant: &'static str,
}

pub const GATES: &[Gate] = &[
    Gate {
        name: "generated_ci_is_current",
        invariant: "the committed v2.yml byte-matches the generator",
    },
    Gate {
        name: "contract_fingerprint_is_intentional",
        invariant: "a contract shape change updates fingerprint.txt in the same commit",
    },
    Gate {
        name: "dogfood_kndo_reports_nothing_on_itself",
        invariant: "kndo over this repository reports zero findings",
    },
    Gate {
        name: "warm_and_cold_runs_are_byte_identical",
        invariant: "cached, re-cached and uncached runs serialize identically",
    },
    Gate {
        name: "threads_one_and_many_are_byte_identical",
        invariant: "thread count never changes a byte of output",
    },
    Gate {
        name: "incremental_and_full_assembly_are_byte_identical",
        invariant: "a change replayed over cached evidence equals a from-scratch build",
    },
    Gate {
        name: "adapter_conformance_fixtures_are_byte_identical",
        invariant: "the harvested fixture corpus replays to its pinned reports",
    },
    Gate {
        name: "dogfood_zero_means_measured",
        invariant: "every dogfood abstention is accepted in writing — zero cannot cheapen",
    },
    Gate {
        name: "report_schema_is_generated_and_valid",
        invariant: "the committed schema is derived from the types and validates real reports",
    },
    Gate {
        name: "frontends_import_only_the_facade",
        invariant: "a frontend's production dependencies contain exactly one kndo crate: kndo",
    },
    Gate {
        name: "builtin_plugin_proofs",
        invariant: "every built-in plugin proves its effect baseline-then-plugin, closed over default_plugins",
    },
    Gate {
        name: "plugin_dependency_implication",
        invariant: "a plugin named in another's dependencies activates even when its own rules never match",
    },
    Gate {
        name: "abi_compat_matrix",
        invariant: "the pinned reference components still run against the HEAD host",
    },
];

/// Repo-relative location of the generated workflow.
pub const WORKFLOW_REPO_PATH: &str = ".github/workflows/v2.yml";

/// Absolute path to the generated workflow, resolved from this crate's location
/// (v2/crates/kndo-gates → repo root is three levels up).
pub fn workflow_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .join(WORKFLOW_REPO_PATH)
}

const TEMPLATE: &str = r#"# GENERATED by `cargo xtask gen-ci` from kndo-gates' registry — edits land there,
# never here. The `generated_ci_is_current` gate fails when this file drifts.
name: v2

on:
  push:
    branches: [claude/proyecto-rediseno-greenfield-yg7bjp, main]
    paths: ["v2/**", ".github/workflows/v2.yml"]
  pull_request:
    paths: ["v2/**", ".github/workflows/v2.yml"]
  workflow_dispatch:

concurrency:
  group: v2-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash
    working-directory: v2

jobs:
  lint:
    name: lint (fmt, clippy, commit message)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.98.0
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: v2
      - name: cargo fmt --check
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: conventional commit (HEAD)
        run: |
          subject=$(git log -1 --format=%s)
          echo "$subject"
          case "$subject" in "Merge "*) exit 0;; esac
          echo "$subject" | grep -qE '^(feat|fix|docs|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9,/_-]+\))?!?: .+' \
            || { echo "not a conventional commit"; exit 1; }

  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Windows deferred by owner decision (tree-sitter-scss upstream) — v2/DECISIONS.md.
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.98.0
          # The ABI compliance suite builds the reference guests at run time; a
          # toolchain without this target dies with "can't find crate for `core`".
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: v2
      - name: cargo test --workspace
        run: cargo test --workspace

  gates:
    name: named gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.98.0
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: v2
      - name: every named gate still exists
        run: |
          set -eu
          cargo test -p kndo-gates --test gates -- --list > /tmp/gate-list.txt
          missing=""
          for name in @GATE_NAMES@; do
            grep -q "$name" /tmp/gate-list.txt || missing="$missing $name"
          done
          [ -z "$missing" ] || { echo "named gates missing from the harness:$missing"; exit 1; }
@GATE_STEPS@
  corpus:
    name: corpus is measured and its findings are committed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.98.0
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: v2
      - uses: actions/cache@v4
        with:
          path: /tmp/kndo-corpus
          key: corpus-${{ hashFiles('v2/corpus/corpus.toml') }}
      - name: clone the pinned corpus
        run: bash corpus/clone.sh /tmp/kndo-corpus
      - name: measure
        run: cargo run --release -p xtask -- corpus --corpus-dir /tmp/kndo-corpus
      - name: the committed measurement matches this code
        run: git diff --exit-code -- corpus-findings/

  package-install:
    name: package + install (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Windows deferred by owner decision (tree-sitter-scss upstream) — v2/DECISIONS.md.
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.98.0
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: v2
      - name: package, exactly as a release will
        run: cargo run -p xtask -- package --tag v0.0.0-ci --out-dir dist
      - name: verify checksum, install and run from the artifact
        run: cargo run -p xtask -- verify-artifact --dir dist
"#;

pub fn render_ci() -> String {
    let names: Vec<&str> = GATES.iter().map(|g| g.name).collect();
    let steps: String = GATES
        .iter()
        .map(|g| {
            format!(
                "      - name: gate — {} ({})\n        run: cargo test -p kndo-gates --test gates -- --exact {}\n",
                g.name, g.invariant, g.name
            )
        })
        .collect();
    TEMPLATE
        .replace("@GATE_NAMES@", &names.join(" "))
        .replace("@GATE_STEPS@", &steps)
}
