#!/bin/sh
# Regenerate the v1 oracle: run the v1 kndo binary over every pinned corpus repo and
# store its findings JSON with volatile run metadata stripped (started_at, duration_ms,
# project_root — per corpus/corpus.toml [oracle]).
#
# Usage: KNDO_BIN=/path/to/kndo CORPUS_DIR=/path/to/clones ./run-oracle.sh [out-dir]
# Each clone under CORPUS_DIR must be named as in corpus.toml and checked out at the
# pinned commit; the script refuses a mismatched pin.
set -eu

KNDO_BIN=${KNDO_BIN:?set KNDO_BIN to the v1 kndo binary}
CORPUS_DIR=${CORPUS_DIR:?set CORPUS_DIR to the directory of pinned clones}
OUT=${1:-$(dirname "$0")}
TOML="$(dirname "$0")/../corpus/corpus.toml"

names=$(grep '^name = ' "$TOML" | cut -d'"' -f2)
for name in $names; do
    pin=$(awk -v n="$name" '$0 ~ "^name = \""n"\"" {f=1} f && /^commit = / {print; exit}' "$TOML" | cut -d'"' -f2)
    repo="$CORPUS_DIR/$name"
    head=$(git -C "$repo" rev-parse HEAD)
    if [ "$head" != "$pin" ]; then
        echo "oracle: $name is at $head, corpus.toml pins $pin — refusing" >&2
        exit 1
    fi
    echo "oracle: $name @ $pin"
    (cd "$repo" && "$KNDO_BIN" check --format json --no-cache > /tmp/oracle-raw.json) || true
    python3 - "$OUT/$name.json" <<'EOF'
import json, sys
with open('/tmp/oracle-raw.json') as f:
    d = json.load(f)
for k in ('started_at', 'duration_ms', 'project_root'):
    d.get('run', {}).pop(k, None)
with open(sys.argv[1], 'w') as f:
    json.dump(d, f, indent=1, ensure_ascii=False)
    f.write('\n')
EOF
done

python3 - "$OUT" <<'EOF'
import json, sys, glob, os, collections
out = sys.argv[1]
rows = []
for p in sorted(glob.glob(os.path.join(out, '*.json'))):
    with open(p) as f:
        d = json.load(f)
    cats = collections.Counter(f_['category'] for f_ in d.get('findings', []))
    rows.append((os.path.basename(p)[:-5], d['run'].get('cache', '?'),
                 len(d.get('findings', [])), dict(sorted(cats.items())),
                 [a['id'] for a in d['run'].get('adapters', [])],
                 [x.get('category') for x in d.get('run', {}).get('abstained', [])]))
with open(os.path.join(out, 'summary.md'), 'w') as f:
    f.write('# Oracle summary — v1 findings over the pinned corpus\n\n')
    f.write('Generated by run-oracle.sh; regenerating on the same pins must be byte-identical.\n\n')
    f.write('| repo | findings | by category | abstained |\n|---|---|---|---|\n')
    for name, cache, n, cats, adapters, abst in rows:
        catstr = ', '.join(f'{k} {v}' for k, v in cats.items()) or '—'
        f.write(f'| {name} | {n} | {catstr} | {", ".join(a for a in abst if a) or "—"} |\n')
print('summary.md written')
EOF
