// Code generated by protoc-gen-go. DO NOT EDIT.

package main

type wireFormat struct{}

// deadHelper is unreachable AND its type never used — in an authored file both
// would be accused. Here the banner says a generator owns them.
func deadHelper(w wireFormat) wireFormat {
	return w
}
