[package]
name = "kndo-adapter-js"
description = "JavaScript/TypeScript language adapter (docs/adapters/js-ts.md)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rustc-hash = { workspace = true }
kndo-core = { path = "../kndo-core" }
kndo-adapter-toolkit = { path = "../kndo-adapter-toolkit" }
smol_str = { workspace = true }
tree-sitter = { workspace = true }
serde_json = { workspace = true }
