[package]
name = "kndo-adapter-html"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kndo-adapter-ts = { path = "../kndo-adapter-ts" }
kndo-contract = { path = "../kndo-contract" }
kndo-toolkit = { path = "../kndo-toolkit" }
smol_str = { version = "0.3", features = ["serde"] }

[dev-dependencies]
kndo-testkit = { path = "../kndo-testkit" }
