/**
 * @generated by graphql-codegen — nothing imports this file, and in an authored
 * file that would be an unused:file finding; the marker roots it Tooling and it
 * declares nothing accusable.
 */
export type Query = { id: number };
