//! Extraction against tree-sitter-swift 0.7.3, every node kind verified in its
//! `node-types.json`. Members attribute to their enclosing type; an
//! `extension Foo` block declares nothing itself and hands `Foo` to its
//! members (a `class_declaration` whose `declaration_kind` is `extension`,
//! named by a possibly-qualified `user_type` — the last segment is the bare
//! name). Initializers, deinitializers and enum cases are never declared (the
//! shared constructor posture, and `.case` dot-shorthand resolves by type, not
//! name); their bodies still contribute references.

use kndo_contract::evidence::{
    Attachment, DeclarationId, EvidenceSink, MarkerTarget, Reach, RefKind, RelationKind, RootKind,
    RootTarget, SymbolKind,
};
use kndo_contract::vocab::{Confidence, ProjectPath};
use kndo_toolkit as tk;
use smol_str::SmolStr;
use tree_sitter::Node;

/// The Swift ecosystem's generated-file needles: the shared convention plus
/// `Generated by` (Sourcery, protoc-gen-swift stamp it).
const GENERATED_NEEDLES: &[&str] = &[
    "@generated",
    "Code generated",
    "DO NOT EDIT",
    "Generated by",
];

const COMMENTS: tk::CommentMarkers<'static> = tk::CommentMarkers {
    line: &["//"],
    block: &[("/*", "*/")],
    line_doc: b"/",
    block_doc: b"*",
};

const METRICS: tk::MetricsSpec = tk::MetricsSpec {
    is_branch: |n, _| match n.kind() {
        // A `switch` arm counts unless it is the default — the catch-the-rest,
        // not a new predicate (the shared rule); `guard` is an early-return
        // conditional, counted like `if`.
        "switch_entry" => {
            let mut c = n.walk();
            !n.children(&mut c).any(|ch| ch.kind() == "default_keyword")
        }
        "if_statement"
        | "guard_statement"
        | "for_statement"
        | "while_statement"
        | "repeat_while_statement"
        | "catch_block" => true,
        "&&" | "||" => true,
        _ => false,
    },
    token_class: |n| match n.kind() {
        "simple_identifier" | "type_identifier" => Some("id"),
        "line_str_text" | "multi_line_str_text" => Some("str"),
        "integer_literal" | "hex_literal" | "oct_literal" | "bin_literal" | "real_literal" => {
            Some("num")
        }
        "comment" | "multiline_comment" => None,
        other => Some(other),
    },
};

type TypeIds = std::collections::BTreeMap<SmolStr, kndo_contract::evidence::DeclarationId>;

pub fn extract(
    path: &ProjectPath,
    source: &[u8],
    tree: &tree_sitter::Tree,
    out: &mut EvidenceSink,
) {
    let p = path.as_str();
    let file_name = p.rsplit('/').next().unwrap_or(p);

    // `Package.swift` IS the manifest — Swift source by format: it declares
    // nothing accusable, and its structure is read by `extract_manifest`. What
    // role it plays is the spec's `file_roles` to say, like every other
    // path convention this language keeps.
    let is_manifest = file_name == "Package.swift"
        || (file_name.starts_with("Package@swift-") && file_name.ends_with(".swift"));
    if is_manifest {
        return;
    }

    // The namespace IS the SwiftPM target: `internal` — the language's default
    // — reaches every file the module compiles and stops there, so one clause
    // per file is the whole of Swift's scope shape. The target is spelled by
    // the layout, never by the bytes, which is why `resolve` and this agree by
    // sharing one function.
    let target = crate::resolve::target_of(p);
    if let Some((name, _)) = target {
        out.namespace([SmolStr::new(name)]);
    }
    // A test target is its own module: what it declares belongs to the
    // package in test builds alone. The test-shaped NAME is not that — a
    // `LoadTests.swift` in a library target is compiled into it like any
    // other file, and says nothing here.
    let in_test_target = target.is_some_and(|(_, test)| test);
    if in_test_target {
        out.attachment(Attachment::TestOnly);
    }

    tk::mark_generated(source, GENERATED_NEEDLES, &["//", "/*", "*"], out);

    let root = tree.root_node();
    let mut cursor = root.walk();
    let children: Vec<Node<'_>> = root.named_children(&mut cursor).collect();
    // Two passes: types declare first, so a same-file `extension Foo` can
    // attach its members to Foo's id (a cross-file extension's members stay
    // ownerless — the method pool is name-global either way).
    let mut type_ids = TypeIds::new();
    let cx = FileCx { in_test_target };
    for item in &children {
        if matches!(item.kind(), "class_declaration" | "protocol_declaration")
            && !is_extension(*item, source)
        {
            top_level_item(*item, source, &cx, &mut type_ids, out);
        }
    }
    for item in children {
        if matches!(item.kind(), "class_declaration" | "protocol_declaration")
            && !is_extension(item, source)
        {
            continue;
        }
        top_level_item(item, source, &cx, &mut type_ids, out);
    }

    references_and_comments(root, source, out);
}

/// `` `default` `` and `default` are ONE identifier: Swift requires the
/// backticks only where the word would otherwise be a keyword, and permits
/// them anywhere. The quotes are spelling, never name, so they come off on
/// both sides — a declaration and the reference that reaches it.
fn bare(name: &str) -> &str {
    name.strip_prefix('`')
        .and_then(|n| n.strip_suffix('`'))
        .unwrap_or(name)
}

fn is_extension(item: Node<'_>, source: &[u8]) -> bool {
    item.kind() == "class_declaration"
        && item
            .child_by_field_name("declaration_kind")
            .is_some_and(|k| tk::text(k, source) == "extension")
}

/// Per-file facts every declaration handler needs.
#[derive(Clone, Copy)]
struct FileCx {
    /// Under `Tests/`: the toolchain's own runners (XCTest by `test*` name,
    /// swift-testing by `@Test`) dispatch on declarations no source line names.
    in_test_target: bool,
}

fn top_level_item(
    item: Node<'_>,
    source: &[u8],
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    match item.kind() {
        "import_declaration" => import(item, source, out),
        "class_declaration" => class_like(item, source, cx, type_ids, out),
        "protocol_declaration" => protocol(item, source, cx, type_ids, out),
        "function_declaration" => {
            function(item, source, None, false, None, cx, out);
        }
        "property_declaration" => property(item, source, None, None, out),
        "typealias_declaration" => {
            if let Some(n) = item.child_by_field_name("name") {
                out.declaration(
                    bare(tk::text(n, source)),
                    SymbolKind::Type,
                    tk::span(item),
                    reach_of(item, source),
                );
            }
        }
        _ => {}
    }
}

/// `import Foo` (or `@testable import Foo`): the module's whole top-level
/// surface lands in bare scope — no per-name binding syntax exists, so the
/// namespace shape is the truthful one (it keeps the target's surface alive
/// and marks this file an importer for region checks).
fn import(item: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    let mut c = item.walk();
    let Some(module) = item
        .named_children(&mut c)
        .find(|n| n.kind() == "identifier")
    else {
        return;
    };
    // `import Foo.Bar` — the module is the first segment.
    let name = tk::text(module, source);
    let module_name = name.split('.').next().unwrap_or(name);
    out.import(
        kndo_contract::evidence::ImportTarget::Package(SmolStr::new(module_name)),
        kndo_contract::evidence::ImportShape::Namespace {
            local: SmolStr::new(module_name),
        },
        tk::span(item),
        Confidence::Certain,
    );
}

/// class / struct / enum / actor / extension — one grammar node, told apart by
/// `declaration_kind`. An extension declares nothing; everything else is a
/// Type. Bodies dispatch members with the owner's bare name.
fn class_like(
    item: Node<'_>,
    source: &[u8],
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    let Some(kind_node) = item.child_by_field_name("declaration_kind") else {
        return;
    };
    let decl_kind = tk::text(kind_node, source);
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    // An extension's name is a (possibly qualified) `user_type`; a declaration's
    // is a plain `type_identifier`.
    let name: SmolStr = if name_node.kind() == "user_type" {
        let mut c = name_node.walk();
        match name_node
            .named_children(&mut c)
            .filter(|n| n.kind() == "type_identifier")
            .last()
        {
            Some(last) => SmolStr::new(bare(tk::text(last, source))),
            None => return,
        }
    } else {
        SmolStr::new(bare(tk::text(name_node, source)))
    };

    let conforms = has_conformances(item);
    let owner_id = if decl_kind == "extension" {
        // A same-file extension attaches its members to the extended type.
        let existing = type_ids.get(&name).copied();
        // `extension Foo: Codable` is FOO's promise: retroactive conformance
        // is the idiom, and a rule asking whether `Foo` conforms must see it
        // wherever it was written.
        if let Some(owner) = existing {
            relations_of(item, source, owner, out);
        }
        existing
    } else {
        let id = out.declaration(
            name.clone(),
            SymbolKind::Type,
            tk::span(item),
            reach_of(item, source),
        );
        markers_of(item, source, id, out);
        relations_of(item, source, id, out);
        // `@main` — SwiftPM resolves the attributed type's `static main()` as
        // the executable entry; the type itself is the anchor we can name.
        if has_attribute(item, source, "main") {
            out.root(
                RootTarget::Declaration(id),
                RootKind::Production,
                Confidence::Certain,
            );
        }
        type_ids.insert(name.clone(), id);
        Some(id)
    };

    if let Some(body) =
        tk::child_of_kind(item, "class_body").or_else(|| tk::child_of_kind(item, "enum_class_body"))
    {
        let mut c = body.walk();
        let members: Vec<Node<'_>> = body.named_children(&mut c).collect();
        let owner = Owner {
            name: &name,
            id: owner_id,
            conforms,
            // `public extension Foo { func bar() }` makes `bar` public; the
            // engine caps the effective reach by Foo's own, so stating the
            // extension's modifier here is both simpler and correct.
            inherits: (decl_kind == "extension")
                .then(|| declared_reach(item, source))
                .flatten(),
        };
        for m in members {
            member(m, source, &owner, cx, type_ids, out);
        }
    }
}

fn protocol(
    item: Node<'_>,
    source: &[u8],
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = SmolStr::new(bare(tk::text(name_node, source)));
    let owner_id = out.declaration(
        name.clone(),
        SymbolKind::Type,
        tk::span(item),
        reach_of(item, source),
    );
    markers_of(item, source, owner_id, out);
    relations_of(item, source, owner_id, out);
    type_ids.insert(name.clone(), owner_id);
    if let Some(body) = tk::child_of_kind(item, "protocol_body") {
        let mut c = body.walk();
        let members: Vec<Node<'_>> = body.named_children(&mut c).collect();
        let owner = Owner {
            name: &name,
            id: Some(owner_id),
            conforms: false,
            inherits: Some(Reach::Inherited),
        };
        for m in members {
            member(m, source, &owner, cx, type_ids, out);
        }
    }
}

/// The enclosing type as its members see it: the bare name, the id when it
/// was declared in THIS file (a cross-file extension's members stay
/// ownerless), and whether it declares conformances.
struct Owner<'a> {
    name: &'a str,
    id: Option<kndo_contract::evidence::DeclarationId>,
    conforms: bool,
    /// What a member with NO visibility modifier of its own reaches. A
    /// protocol REQUIREMENT is exactly as visible as its protocol — there is
    /// no narrower thing for it to be — and `Inherited` is that sentence; a
    /// `public extension` likewise hands its own modifier down. Everywhere
    /// else the member takes the language default, which is the module.
    inherits: Option<Reach>,
}

fn member(
    m: Node<'_>,
    source: &[u8],
    owner: &Owner<'_>,
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    match m.kind() {
        "function_declaration" | "protocol_function_declaration" => {
            let id = function(
                m,
                source,
                Some(owner.name),
                owner.conforms,
                owner.inherits.clone(),
                cx,
                out,
            );
            if let (Some(id), Some(owner)) = (id, owner.id) {
                out.member_of(id, owner);
            }
        }
        "property_declaration" => property(m, source, owner.id, owner.inherits.clone(), out),
        // A protocol's `var v: Int { get }` is its own node kind. Its name sits
        // under the same `pattern`, and it was never declared at all.
        "protocol_property_declaration" => {
            let Some(pattern) = tk::child_of_kind(m, "pattern") else {
                return;
            };
            let Some(ident) = tk::child_of_kind(pattern, "simple_identifier") else {
                return;
            };
            let id = out.declaration(
                bare(tk::text(ident, source)),
                SymbolKind::Variable,
                tk::span(m),
                Reach::Inherited,
            );
            markers_of(m, source, id, out);
            if let Some(owner) = owner.id {
                out.member_of(id, owner);
            }
        }
        "class_declaration" => class_like(m, source, cx, type_ids, out),
        "protocol_declaration" => protocol(m, source, cx, type_ids, out),
        "typealias_declaration" => {
            if let Some(n) = m.child_by_field_name("name") {
                let id = out.declaration(
                    bare(tk::text(n, source)),
                    SymbolKind::Type,
                    tk::span(m),
                    member_reach(m, source, owner.inherits.clone()),
                );
                if let Some(owner) = owner.id {
                    out.member_of(id, owner);
                }
            }
        }
        // init/deinit/enum_entry: never declared; their reference evidence
        // arrives through the file-wide walk.
        _ => {}
    }
}

fn function(
    item: Node<'_>,
    source: &[u8],
    owner: Option<&str>,
    owner_conforms: bool,
    inherits: Option<Reach>,
    cx: &FileCx,
    out: &mut EvidenceSink,
) -> Option<kndo_contract::evidence::DeclarationId> {
    let reach = member_reach(item, source, inherits);
    let fn_name = match item.child_by_field_name("name") {
        Some(n) => tk::text(n, source),
        // `static func == (l: S, r: S)` has no `name` field at all: the
        // operator is an anonymous token, and without this the declaration was
        // dropped whole. It is a name like any other — the call sites spell it
        // `a == b`, which the reference pass reports.
        None => operator_name(item, source)?,
    };
    let kind = if owner.is_some() {
        SymbolKind::Method
    } else {
        SymbolKind::Function
    };
    let scoped_or_wider = !matches!(reach, Reach::Owner | Reach::File);
    let id = out.declaration(bare(fn_name), kind, tk::span(item), reach);
    markers_of(item, source, id, out);

    // The toolchain's own test runners dispatch on declarations no source line
    // names: XCTest finds `test*` methods by name, swift-testing anything
    // carrying `@Test`. Both are toolchain-enforced in a Tests/ target —
    // Certain, the same tier as the layout root itself.
    if cx.in_test_target && (fn_name.starts_with("test") || has_attribute(item, source, "Test")) {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Test,
            Confidence::Certain,
        );
    }

    // `override`: invoked through the superclass — the source never names the
    // call. Probable, the dispatch tier.
    if has_modifier(item, source, "override") {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Probable,
        );
    }
    // A conforming type's non-private methods may witness protocol
    // requirements invoked entirely outside the repo (Codable synthesis,
    // delegate protocols) — requirements of external protocols are not
    // statically enumerable, so the keep is Possible: degrading toward
    // silence on exactly the fact we cannot enumerate.
    if owner_conforms && scoped_or_wider {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Possible,
        );
    }

    if let Some(body) = item.child_by_field_name("body") {
        out.metrics(id, tk::function_metrics(item, &METRICS, source));
        let _ = body;
    }
    Some(id)
}

/// `let`/`var`, top-level or member: the bound names come from the `name`
/// field's pattern (possibly several in one declaration). Computed properties
/// are Variables too.
fn property(
    item: Node<'_>,
    source: &[u8],
    owner_id: Option<kndo_contract::evidence::DeclarationId>,
    inherits: Option<Reach>,
    out: &mut EvidenceSink,
) {
    let reach = member_reach(item, source, inherits);
    let is_let = {
        let mut found = false;
        tk::walk(item, &mut |n| {
            if n.kind() == "value_binding_pattern" {
                let mut c = n.walk();
                if n.children(&mut c).any(|ch| ch.kind() == "let") {
                    found = true;
                }
            }
        });
        found
    };
    let kind = if is_let {
        SymbolKind::Constant
    } else {
        SymbolKind::Variable
    };
    let mut c = item.walk();
    let names: Vec<Node<'_>> = item.children_by_field_name("name", &mut c).collect();
    for n in names {
        let ident = if n.kind() == "simple_identifier" {
            Some(n)
        } else {
            tk::child_of_kind(n, "simple_identifier")
        };
        if let Some(ident) = ident {
            let id = out.declaration(
                bare(tk::text(ident, source)),
                kind.clone(),
                tk::span(item),
                reach.clone(),
            );
            markers_of(item, source, id, out);
            if let Some(owner) = owner_id {
                out.member_of(id, owner);
            }
        }
    }
}

// ---------------------------------------------------------------- visibility

/// Swift's access levels as reaches: `fileprivate` is the file's; `private`
/// is the file's on a top-level declaration and the owner's on a member
/// (extensions in the same file included, which the file pool holds); NO
/// modifier and `internal` are the module boundary → the unit's reach (the
/// default rung), which a `@testable import` widens to the test target the
/// manifest made its friend; `package` is the group of targets one package
/// aggregates; `public`/`open` → Exported.
fn reach_of(item: Node<'_>, source: &[u8]) -> Reach {
    declared_reach(item, source).unwrap_or(Reach::Unit { up: 0 })
}

/// The same, for a member whose owner hands something down when the source
/// spells nothing: a protocol requirement, a member of a `public extension`.
fn member_reach(item: Node<'_>, source: &[u8], inherits: Option<Reach>) -> Reach {
    declared_reach(item, source)
        .or(inherits)
        .unwrap_or(Reach::Unit { up: 0 })
}

/// What the source SPELLS, or `None` where it spells nothing.
fn declared_reach(item: Node<'_>, source: &[u8]) -> Option<Reach> {
    let modifiers = tk::child_of_kind(item, "modifiers")?;
    let mut c = modifiers.walk();
    for m in modifiers.named_children(&mut c) {
        if m.kind() == "visibility_modifier" {
            return Some(
                match tk::text(m, source)
                    .split('(')
                    .next()
                    .unwrap_or_default()
                    .trim()
                {
                    "fileprivate" => Reach::File,
                    "private" => {
                        if item.parent().is_none_or(|p| p.kind() == "source_file") {
                            Reach::File
                        } else {
                            Reach::Owner
                        }
                    }
                    "package" => Reach::Unit { up: 1 },
                    "public" | "open" => Reach::Exported,
                    // `internal`, or a form we do not know — the default rung.
                    _ => Reach::Unit { up: 0 },
                },
            );
        }
    }
    None
}

fn has_modifier(item: Node<'_>, source: &[u8], word: &str) -> bool {
    let Some(modifiers) = tk::child_of_kind(item, "modifiers") else {
        return false;
    };
    let mut found = false;
    tk::walk(modifiers, &mut |n| {
        if n.child_count() == 0 && tk::text(n, source) == word {
            found = true;
        }
    });
    found
}

fn has_attribute(item: Node<'_>, source: &[u8], name: &str) -> bool {
    let Some(modifiers) = tk::child_of_kind(item, "modifiers") else {
        return false;
    };
    let mut c = modifiers.walk();
    modifiers
        .named_children(&mut c)
        .filter(|n| n.kind() == "attribute")
        .any(|attr| {
            let mut ac = attr.walk();
            attr.named_children(&mut ac)
                .any(|n| n.kind() == "user_type" && tk::text(n, source) == name)
        })
}

/// Every attribute a declaration carries, as a MARKER: its path as written
/// (`main`, `objc`, `Test`, `IBAction`, `propertyWrapper`) and its arguments.
/// Structural, never a table of names — what an attribute MEANS is a dispatch
/// rule's to say, this adapter's job is to report that it is there.
///
/// `override` rides here too. The glossary counts a MODIFIER as a marker, and
/// this is the one Swift modifier a rule reads: an overriding member is
/// invoked through the superclass, so no source line names it. The rest of
/// Swift's modifiers are read where they belong — visibility as `Reach` — or
/// have no consumer, and a marker no rule reads is noise in the evidence.
fn markers_of(item: Node<'_>, source: &[u8], id: DeclarationId, out: &mut EvidenceSink) {
    let Some(modifiers) = tk::child_of_kind(item, "modifiers") else {
        return;
    };
    let mut c = modifiers.walk();
    for m in modifiers.named_children(&mut c) {
        match m.kind() {
            "attribute" => {
                let mut ac = m.walk();
                let children: Vec<Node<'_>> = m.named_children(&mut ac).collect();
                let Some(name) = children.iter().find(|n| n.kind() == "user_type") else {
                    continue;
                };
                let args = children
                    .iter()
                    .filter(|n| n.kind() == "value_argument")
                    .map(|n| SmolStr::new(tk::text(*n, source).trim_matches('"')))
                    .collect();
                out.marker(
                    MarkerTarget::Declaration(id),
                    tk::text(*name, source),
                    args,
                    tk::span(m),
                );
            }
            _ if tk::text(m, source) == "override" => {
                out.marker(
                    MarkerTarget::Declaration(id),
                    "override",
                    Vec::new(),
                    tk::span(m),
                );
            }
            _ => {}
        }
    }
}

/// Every type this declaration promises the surface of, as a RELATION.
///
/// Swift writes one list after the colon and its grammar does not tell a
/// superclass from a protocol — `class A: B, C` is legal with B a class or a
/// protocol, and only the whole program knows which. So one kind is emitted,
/// and it is the true sentence for both: `Implements` is the contract's word
/// for "promises another type's surface", which a subclass does as much as a
/// conformer. Nothing in the engine reads the kind — it reaches a
/// `Trigger::Relation` and the supertype edges, and both compare NAMES.
fn relations_of(item: Node<'_>, source: &[u8], id: DeclarationId, out: &mut EvidenceSink) {
    let mut c = item.walk();
    for spec in item
        .named_children(&mut c)
        .filter(|n| n.kind() == "inheritance_specifier")
    {
        // `: XCTestCase`, `: Encodable`, `: Collection where …` — the name is
        // the specifier's own type, and a generic argument list is not it.
        let mut sc = spec.walk();
        let named: Vec<Node<'_>> = spec.named_children(&mut sc).collect();
        let Some(ty) = named
            .iter()
            .find(|n| matches!(n.kind(), "user_type" | "type_identifier"))
        else {
            continue;
        };
        // `Swift.Codable` and `Codable` are the same promise; the last
        // segment is the name every rule and every supertype edge compares.
        let mut tc = ty.walk();
        let name = ty
            .named_children(&mut tc)
            .filter(|n| n.kind() == "type_identifier")
            .last()
            .map(|n| tk::text(n, source))
            .unwrap_or_else(|| tk::text(*ty, source));
        out.relation(id, RelationKind::Implements, name, tk::span(spec));
    }
}

/// The operator a `func` declares, where the grammar leaves it an anonymous
/// token: the child right after `func`, when nothing named took the name seat.
fn operator_name<'a>(item: Node<'_>, source: &'a [u8]) -> Option<&'a str> {
    let mut c = item.walk();
    let children: Vec<Node<'_>> = item.children(&mut c).collect();
    let at = children.iter().position(|n| n.kind() == "func")?;
    let token = children.get(at + 1)?;
    (!token.is_named() && token.kind() != "(").then(|| tk::text(*token, source))
}

fn has_conformances(item: Node<'_>) -> bool {
    let mut c = item.walk();
    item.named_children(&mut c)
        .any(|ch| ch.kind() == "inheritance_specifier")
}

// ---------------------------------------------------------------- references

/// The expression kinds whose operator token is a NAME a declaration can
/// match. Not every anonymous token is one: `->`, `?` and `!` are syntax, and
/// only these seats hold an operator the source could have written a `func`
/// for.
const OPERATOR_EXPRESSIONS: &[&str] = &[
    "additive_expression",
    "multiplicative_expression",
    "equality_expression",
    "comparison_expression",
    "conjunction_expression",
    "disjunction_expression",
    "nil_coalescing_expression",
    "range_expression",
    "bitwise_operation",
    "prefix_expression",
    "postfix_expression",
];

/// One flat pass for references and comments: identifiers classify by their
/// syntactic seat; binder positions (declaration names, parameter names,
/// argument labels, import segments) never become references. Enum-case
/// dot-shorthand (`.retry`) lands as a Read of the bare name — the pool-side
/// counterpart of never declaring the cases.
fn references_and_comments(root: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    tk::walk_pruned(root, &["import_declaration"], &mut |n| match n.kind() {
        "comment" | "multiline_comment" => {
            tk::comment_evidence(n, source, &COMMENTS, out);
        }
        // An operator APPLICATION: `a == b` names `==`, which some type in
        // the project may declare (`static func == (l:r:)`). The grammar
        // leaves the operator an anonymous token on both sides — the
        // declaration and the use — so the two join by the same spelling.
        k if !k.is_empty()
            && n.parent()
                .is_some_and(|p| OPERATOR_EXPRESSIONS.contains(&p.kind()))
            && !n.is_named() =>
        {
            out.reference_on(k, RefKind::Call, None, tk::span(n));
        }
        "simple_identifier" | "type_identifier" => {
            if let Some(parent) = n.parent() {
                if is_binder_seat(n, parent) {
                    return;
                }
                out.reference_on(
                    bare(tk::text(n, source)),
                    classify(n, parent),
                    receiver_of(parent, source),
                    tk::span(n),
                );
            }
        }
        _ => {}
    });
}

/// What `expr.member` was read FROM, where the source spells it as a name:
/// the `target` of the navigation this identifier is the suffix of. A target
/// that is itself an expression (`a.b.c`, `f().x`) names nothing the pool can
/// use, and absence is the honest answer there.
fn receiver_of(parent: Node<'_>, source: &[u8]) -> Option<SmolStr> {
    if parent.kind() != "navigation_suffix" {
        return None;
    }
    let target = parent.parent()?.child_by_field_name("target")?;
    matches!(target.kind(), "simple_identifier" | "type_identifier")
        .then(|| SmolStr::new(bare(tk::text(target, source))))
}

/// Identifier positions that BIND a new name rather than use one.
fn is_binder_seat(n: Node<'_>, parent: Node<'_>) -> bool {
    match parent.kind() {
        "class_declaration"
        | "protocol_declaration"
        | "function_declaration"
        | "protocol_function_declaration"
        | "typealias_declaration"
        | "init_declaration" => parent.child_by_field_name("name") == Some(n),
        // `case fast, slow` — every identifier seat in an entry binds a case.
        "enum_entry" => true,
        // Parameter external/internal names and argument labels.
        "parameter" => true,
        "value_argument" => parent.child_by_field_name("name") == Some(n),
        // Property and switch binding patterns (`let (a, b)` included). NOT
        // `property_declaration` itself: its `name` field IS a `pattern`, so
        // every bound name is already covered here, and the only other
        // identifier directly under it is the `value` — `let alpha = beta`
        // reads `beta`, which naming the parent kind used to throw away.
        //
        // A pattern that starts with `.` binds nothing: `case .space` USES an
        // enum case by dot-shorthand, which is the pervasive form and the
        // pool-side counterpart of never declaring the cases.
        "pattern" => !dot_shorthand(n),
        "value_binding_pattern" => true,
        "type_parameter" => true,
        _ => false,
    }
}

/// Is this identifier the member half of a leading-dot shorthand — `.space`
/// in a pattern, where the type is inferred and only the name is written?
fn dot_shorthand(n: Node<'_>) -> bool {
    n.prev_sibling().is_some_and(|s| s.kind() == ".")
}

fn classify(n: Node<'_>, parent: Node<'_>) -> RefKind {
    match parent.kind() {
        // Callee position: `foo(...)` — the call's first child.
        "call_expression" if parent.child(0) == Some(n) => RefKind::Call,
        // Member seat: `expr.member` — a call when the navigation itself is a
        // call's callee.
        "navigation_suffix" => {
            let called = parent.parent().is_some_and(|nav| {
                nav.parent()
                    .is_some_and(|gp| gp.kind() == "call_expression" && gp.child(0) == Some(nav))
            });
            if called { RefKind::Call } else { RefKind::Read }
        }
        "user_type" => {
            let in_inheritance = {
                let mut a = parent.parent();
                let mut hit = false;
                while let Some(node) = a {
                    if node.kind() == "inheritance_specifier" {
                        hit = true;
                        break;
                    }
                    a = node.parent();
                }
                hit
            };
            if in_inheritance {
                RefKind::Extend
            } else {
                RefKind::TypeUse
            }
        }
        _ => RefKind::Read,
    }
}
