//! Extraction against tree-sitter-swift 0.7.3, every node kind verified in its
//! `node-types.json`. Members attribute to their enclosing type; an
//! `extension Foo` block declares nothing itself and hands `Foo` to its
//! members (a `class_declaration` whose `declaration_kind` is `extension`,
//! named by a possibly-qualified `user_type` — the last segment is the bare
//! name). Initializers, deinitializers and enum cases are never declared (the
//! shared constructor posture, and `.case` dot-shorthand resolves by type, not
//! name); their bodies still contribute references.

use kndo_contract::evidence::{EvidenceSink, Reach, RefKind, RootKind, RootTarget, SymbolKind};
use kndo_contract::vocab::{Confidence, ProjectPath};
use kndo_toolkit as tk;
use smol_str::SmolStr;
use tree_sitter::Node;

/// The Swift ecosystem's generated-file needles: the shared convention plus
/// `Generated by` (Sourcery, protoc-gen-swift stamp it).
const GENERATED_NEEDLES: &[&str] = &[
    "@generated",
    "Code generated",
    "DO NOT EDIT",
    "Generated by",
];

const COMMENTS: tk::CommentMarkers<'static> = tk::CommentMarkers {
    line: &["//"],
    block: &[("/*", "*/")],
    line_doc: b"/",
    block_doc: b"*",
};

const METRICS: tk::MetricsSpec = tk::MetricsSpec {
    is_branch: |n, _| match n.kind() {
        // A `switch` arm counts unless it is the default — the catch-the-rest,
        // not a new predicate (the shared rule); `guard` is an early-return
        // conditional, counted like `if`.
        "switch_entry" => {
            let mut c = n.walk();
            !n.children(&mut c).any(|ch| ch.kind() == "default_keyword")
        }
        "if_statement"
        | "guard_statement"
        | "for_statement"
        | "while_statement"
        | "repeat_while_statement"
        | "catch_block" => true,
        "&&" | "||" => true,
        _ => false,
    },
    token_class: |n| match n.kind() {
        "simple_identifier" | "type_identifier" => Some("id"),
        "line_str_text" | "multi_line_str_text" => Some("str"),
        "integer_literal" | "hex_literal" | "oct_literal" | "bin_literal" | "real_literal" => {
            Some("num")
        }
        "comment" | "multiline_comment" => None,
        other => Some(other),
    },
};

type TypeIds = std::collections::BTreeMap<SmolStr, kndo_contract::evidence::DeclarationId>;

pub fn extract(
    path: &ProjectPath,
    source: &[u8],
    tree: &tree_sitter::Tree,
    out: &mut EvidenceSink,
) {
    let p = path.as_str();
    let file_name = p.rsplit('/').next().unwrap_or(p);

    // `Package.swift` IS the manifest — Swift source by format, tooling by
    // role: it roots as Tooling and declares nothing accusable (its
    // dependency names flow through the manifests capability instead).
    let is_manifest = file_name == "Package.swift"
        || (file_name.starts_with("Package@swift-") && file_name.ends_with(".swift"));
    if is_manifest {
        out.root(
            RootTarget::WholeFile,
            RootKind::Tooling,
            Confidence::Certain,
        );
        return;
    }

    // SwiftPM's own layout is the build tool's boundary — Certain; a
    // test-shaped NAME outside it is convention: Probable, and the file keeps
    // its library-mode Production root.
    let test_dir = p.starts_with("Tests/") || p.contains("/Tests/");
    let test_name = file_name.ends_with("Tests.swift") || file_name.ends_with("Test.swift");
    if test_dir {
        out.root(RootTarget::WholeFile, RootKind::Test, Confidence::Certain);
    } else if file_name == "main.swift" {
        // The whole file's top-level code runs at process start — SwiftPM's
        // own rule for the filename, not a heuristic.
        out.root(
            RootTarget::WholeFile,
            RootKind::Production,
            Confidence::Certain,
        );
    } else {
        if test_name {
            out.root(RootTarget::WholeFile, RootKind::Test, Confidence::Probable);
        }
        // Library mode, the shared stance: any non-test file is importable
        // published surface. Probable — convention, not this file's statement.
        out.root(
            RootTarget::WholeFile,
            RootKind::Production,
            Confidence::Probable,
        );
    }

    let generated = tk::generated_marked(source, GENERATED_NEEDLES, &["//", "/*", "*"]);
    let in_test_target = test_dir;

    let root = tree.root_node();
    let mut cursor = root.walk();
    let children: Vec<Node<'_>> = root.named_children(&mut cursor).collect();
    // Two passes: types declare first, so a same-file `extension Foo` can
    // attach its members to Foo's id (a cross-file extension's members stay
    // ownerless — the method pool is name-global either way).
    let mut type_ids = TypeIds::new();
    let cx = FileCx {
        generated,
        in_test_target,
    };
    for item in &children {
        if matches!(item.kind(), "class_declaration" | "protocol_declaration")
            && !is_extension(*item, source)
        {
            top_level_item(*item, source, &cx, &mut type_ids, out);
        }
    }
    for item in children {
        if matches!(item.kind(), "class_declaration" | "protocol_declaration")
            && !is_extension(item, source)
        {
            continue;
        }
        top_level_item(item, source, &cx, &mut type_ids, out);
    }

    references_and_comments(root, source, out);
}

fn is_extension(item: Node<'_>, source: &[u8]) -> bool {
    item.kind() == "class_declaration"
        && item
            .child_by_field_name("declaration_kind")
            .is_some_and(|k| tk::text(k, source) == "extension")
}

/// Per-file facts every declaration handler needs.
#[derive(Clone, Copy)]
struct FileCx {
    generated: bool,
    /// Under `Tests/`: the toolchain's own runners (XCTest by `test*` name,
    /// swift-testing by `@Test`) dispatch on declarations no source line names.
    in_test_target: bool,
}

fn top_level_item(
    item: Node<'_>,
    source: &[u8],
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    match item.kind() {
        "import_declaration" => import(item, source, out),
        _ if cx.generated => {}
        "class_declaration" => class_like(item, source, cx, type_ids, out),
        "protocol_declaration" => protocol(item, source, cx, type_ids, out),
        "function_declaration" => {
            function(item, source, None, false, cx, out);
        }
        "property_declaration" => property(item, source, None, out),
        "typealias_declaration" => {
            if let Some(n) = item.child_by_field_name("name") {
                out.declaration(
                    tk::text(n, source),
                    SymbolKind::Type,
                    tk::span(item),
                    reach_of(item, source),
                );
            }
        }
        _ => {}
    }
}

/// `import Foo` (or `@testable import Foo`): the module's whole top-level
/// surface lands in bare scope — no per-name binding syntax exists, so the
/// namespace shape is the truthful one (it keeps the target's surface alive
/// and marks this file an importer for region checks).
fn import(item: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    let mut c = item.walk();
    let Some(module) = item
        .named_children(&mut c)
        .find(|n| n.kind() == "identifier")
    else {
        return;
    };
    // `import Foo.Bar` — the module is the first segment.
    let name = tk::text(module, source);
    let module_name = name.split('.').next().unwrap_or(name);
    out.import(
        kndo_contract::evidence::ImportTarget::Package(SmolStr::new(module_name)),
        kndo_contract::evidence::ImportShape::Namespace {
            local: SmolStr::new(module_name),
        },
        tk::span(item),
        Confidence::Certain,
    );
}

/// class / struct / enum / actor / extension — one grammar node, told apart by
/// `declaration_kind`. An extension declares nothing; everything else is a
/// Type. Bodies dispatch members with the owner's bare name.
fn class_like(
    item: Node<'_>,
    source: &[u8],
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    let Some(kind_node) = item.child_by_field_name("declaration_kind") else {
        return;
    };
    let decl_kind = tk::text(kind_node, source);
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    // An extension's name is a (possibly qualified) `user_type`; a declaration's
    // is a plain `type_identifier`.
    let name: SmolStr = if name_node.kind() == "user_type" {
        let mut c = name_node.walk();
        match name_node
            .named_children(&mut c)
            .filter(|n| n.kind() == "type_identifier")
            .last()
        {
            Some(last) => SmolStr::new(tk::text(last, source)),
            None => return,
        }
    } else {
        SmolStr::new(tk::text(name_node, source))
    };

    let conforms = has_conformances(item);
    let owner_id = if decl_kind == "extension" {
        // A same-file extension attaches its members to the extended type.
        type_ids.get(&name).copied()
    } else {
        let id = out.declaration(
            name.clone(),
            SymbolKind::Type,
            tk::span(item),
            reach_of(item, source),
        );
        // `@main` — SwiftPM resolves the attributed type's `static main()` as
        // the executable entry; the type itself is the anchor we can name.
        if has_attribute(item, source, "main") {
            out.root(
                RootTarget::Declaration(id),
                RootKind::Production,
                Confidence::Certain,
            );
        }
        type_ids.insert(name.clone(), id);
        Some(id)
    };

    if let Some(body) =
        tk::child_of_kind(item, "class_body").or_else(|| tk::child_of_kind(item, "enum_class_body"))
    {
        let mut c = body.walk();
        let members: Vec<Node<'_>> = body.named_children(&mut c).collect();
        let owner = Owner {
            name: &name,
            id: owner_id,
            conforms,
        };
        for m in members {
            member(m, source, &owner, cx, type_ids, out);
        }
    }
}

fn protocol(
    item: Node<'_>,
    source: &[u8],
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = SmolStr::new(tk::text(name_node, source));
    let owner_id = out.declaration(
        name.clone(),
        SymbolKind::Type,
        tk::span(item),
        reach_of(item, source),
    );
    type_ids.insert(name.clone(), owner_id);
    if let Some(body) = tk::child_of_kind(item, "protocol_body") {
        let mut c = body.walk();
        let members: Vec<Node<'_>> = body.named_children(&mut c).collect();
        let owner = Owner {
            name: &name,
            id: Some(owner_id),
            conforms: false,
        };
        for m in members {
            member(m, source, &owner, cx, type_ids, out);
        }
    }
}

/// The enclosing type as its members see it: the bare name, the id when it
/// was declared in THIS file (a cross-file extension's members stay
/// ownerless), and whether it declares conformances.
struct Owner<'a> {
    name: &'a str,
    id: Option<kndo_contract::evidence::DeclarationId>,
    conforms: bool,
}

fn member(
    m: Node<'_>,
    source: &[u8],
    owner: &Owner<'_>,
    cx: &FileCx,
    type_ids: &mut TypeIds,
    out: &mut EvidenceSink,
) {
    match m.kind() {
        "function_declaration" | "protocol_function_declaration" => {
            let id = function(m, source, Some(owner.name), owner.conforms, cx, out);
            if let (Some(id), Some(owner)) = (id, owner.id) {
                out.member_of(id, owner);
            }
        }
        "property_declaration" => property(m, source, owner.id, out),
        "class_declaration" => class_like(m, source, cx, type_ids, out),
        "protocol_declaration" => protocol(m, source, cx, type_ids, out),
        "typealias_declaration" => {
            if let Some(n) = m.child_by_field_name("name") {
                let id = out.declaration(
                    tk::text(n, source),
                    SymbolKind::Type,
                    tk::span(m),
                    reach_of(m, source),
                );
                if let Some(owner) = owner.id {
                    out.member_of(id, owner);
                }
            }
        }
        // init/deinit/enum_entry: never declared; their reference evidence
        // arrives through the file-wide walk.
        _ => {}
    }
}

fn function(
    item: Node<'_>,
    source: &[u8],
    owner: Option<&str>,
    owner_conforms: bool,
    cx: &FileCx,
    out: &mut EvidenceSink,
) -> Option<kndo_contract::evidence::DeclarationId> {
    let name_node = item.child_by_field_name("name")?;
    let reach = reach_of(item, source);
    let fn_name = tk::text(name_node, source);
    let kind = if owner.is_some() {
        SymbolKind::Method
    } else {
        SymbolKind::Function
    };
    let scoped_or_wider = !matches!(reach, Reach::Owner | Reach::File);
    let id = out.declaration(fn_name, kind, tk::span(item), reach);

    // The toolchain's own test runners dispatch on declarations no source line
    // names: XCTest finds `test*` methods by name, swift-testing anything
    // carrying `@Test`. Both are toolchain-enforced in a Tests/ target —
    // Certain, the same tier as the layout root itself.
    if cx.in_test_target && (fn_name.starts_with("test") || has_attribute(item, source, "Test")) {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Test,
            Confidence::Certain,
        );
    }

    // `override`: invoked through the superclass — the source never names the
    // call. Probable, the dispatch tier.
    if has_modifier(item, source, "override") {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Probable,
        );
    }
    // A conforming type's non-private methods may witness protocol
    // requirements invoked entirely outside the repo (Codable synthesis,
    // delegate protocols) — requirements of external protocols are not
    // statically enumerable, so the keep is Possible: degrading toward
    // silence on exactly the fact we cannot enumerate.
    if owner_conforms && scoped_or_wider {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Possible,
        );
    }

    if let Some(body) = item.child_by_field_name("body") {
        out.metrics(id, tk::function_metrics(item, &METRICS, source));
        let _ = body;
    }
    Some(id)
}

/// `let`/`var`, top-level or member: the bound names come from the `name`
/// field's pattern (possibly several in one declaration). Computed properties
/// are Variables too.
fn property(
    item: Node<'_>,
    source: &[u8],
    owner_id: Option<kndo_contract::evidence::DeclarationId>,
    out: &mut EvidenceSink,
) {
    let reach = reach_of(item, source);
    let is_let = {
        let mut found = false;
        tk::walk(item, &mut |n| {
            if n.kind() == "value_binding_pattern" {
                let mut c = n.walk();
                if n.children(&mut c).any(|ch| ch.kind() == "let") {
                    found = true;
                }
            }
        });
        found
    };
    let kind = if is_let {
        SymbolKind::Constant
    } else {
        SymbolKind::Variable
    };
    let mut c = item.walk();
    let names: Vec<Node<'_>> = item.children_by_field_name("name", &mut c).collect();
    for n in names {
        let ident = if n.kind() == "simple_identifier" {
            Some(n)
        } else {
            tk::child_of_kind(n, "simple_identifier")
        };
        if let Some(ident) = ident {
            let id = out.declaration(
                tk::text(ident, source),
                kind.clone(),
                tk::span(item),
                reach.clone(),
            );
            if let Some(owner) = owner_id {
                out.member_of(id, owner);
            }
        }
    }
}

// ---------------------------------------------------------------- visibility

/// Swift's access levels as reaches: `fileprivate` is the file's; `private`
/// is the file's on a top-level declaration and the owner's on a member
/// (extensions in the same file included, which the file pool holds); NO
/// modifier and `internal` are the module boundary → the unit's reach (the
/// default rung); `package` is the group of targets one package aggregates;
/// `public`/`open` → Exported.
fn reach_of(item: Node<'_>, source: &[u8]) -> Reach {
    let Some(modifiers) = tk::child_of_kind(item, "modifiers") else {
        return Reach::Unit { up: 0 };
    };
    let mut c = modifiers.walk();
    for m in modifiers.named_children(&mut c) {
        if m.kind() == "visibility_modifier" {
            return match tk::text(m, source)
                .split('(')
                .next()
                .unwrap_or_default()
                .trim()
            {
                "fileprivate" => Reach::File,
                "private" => {
                    if item.parent().is_none_or(|p| p.kind() == "source_file") {
                        Reach::File
                    } else {
                        Reach::Owner
                    }
                }
                "package" => Reach::Unit { up: 1 },
                "public" | "open" => Reach::Exported,
                // `internal`, or a form we do not know — the default rung.
                _ => Reach::Unit { up: 0 },
            };
        }
    }
    Reach::Unit { up: 0 }
}

fn has_modifier(item: Node<'_>, source: &[u8], word: &str) -> bool {
    let Some(modifiers) = tk::child_of_kind(item, "modifiers") else {
        return false;
    };
    let mut found = false;
    tk::walk(modifiers, &mut |n| {
        if n.child_count() == 0 && tk::text(n, source) == word {
            found = true;
        }
    });
    found
}

fn has_attribute(item: Node<'_>, source: &[u8], name: &str) -> bool {
    let Some(modifiers) = tk::child_of_kind(item, "modifiers") else {
        return false;
    };
    let mut c = modifiers.walk();
    modifiers
        .named_children(&mut c)
        .filter(|n| n.kind() == "attribute")
        .any(|attr| {
            let mut ac = attr.walk();
            attr.named_children(&mut ac)
                .any(|n| n.kind() == "user_type" && tk::text(n, source) == name)
        })
}

fn has_conformances(item: Node<'_>) -> bool {
    let mut c = item.walk();
    item.named_children(&mut c)
        .any(|ch| ch.kind() == "inheritance_specifier")
}

// ---------------------------------------------------------------- references

/// One flat pass for references and comments: identifiers classify by their
/// syntactic seat; binder positions (declaration names, parameter names,
/// argument labels, import segments) never become references. Enum-case
/// dot-shorthand (`.retry`) lands as a Read of the bare name — the pool-side
/// counterpart of never declaring the cases.
fn references_and_comments(root: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    tk::walk_pruned(root, &["import_declaration"], &mut |n| match n.kind() {
        "comment" | "multiline_comment" => {
            tk::comment_evidence(n, source, &COMMENTS, out);
        }
        "simple_identifier" | "type_identifier" => {
            if let Some(parent) = n.parent() {
                if is_binder_seat(n, parent) {
                    return;
                }
                out.reference(tk::text(n, source), classify(n, parent), tk::span(n));
            }
        }
        _ => {}
    });
}

/// Identifier positions that BIND a new name rather than use one.
fn is_binder_seat(n: Node<'_>, parent: Node<'_>) -> bool {
    match parent.kind() {
        "class_declaration"
        | "protocol_declaration"
        | "function_declaration"
        | "protocol_function_declaration"
        | "typealias_declaration"
        | "init_declaration" => parent.child_by_field_name("name") == Some(n),
        // `case fast, slow` — every identifier seat in an entry binds a case.
        "enum_entry" => true,
        // Parameter external/internal names and argument labels.
        "parameter" => true,
        "value_argument" => parent.child_by_field_name("name") == Some(n),
        // Property binding patterns (`let (a, b)` included).
        "pattern" | "value_binding_pattern" | "property_declaration" => true,
        "type_parameter" => true,
        _ => false,
    }
}

fn classify(n: Node<'_>, parent: Node<'_>) -> RefKind {
    match parent.kind() {
        // Callee position: `foo(...)` — the call's first child.
        "call_expression" if parent.child(0) == Some(n) => RefKind::Call,
        // Member seat: `expr.member` — a call when the navigation itself is a
        // call's callee.
        "navigation_suffix" => {
            let called = parent.parent().is_some_and(|nav| {
                nav.parent()
                    .is_some_and(|gp| gp.kind() == "call_expression" && gp.child(0) == Some(nav))
            });
            if called { RefKind::Call } else { RefKind::Read }
        }
        "user_type" => {
            let in_inheritance = {
                let mut a = parent.parent();
                let mut hit = false;
                while let Some(node) = a {
                    if node.kind() == "inheritance_specifier" {
                        hit = true;
                        break;
                    }
                    a = node.parent();
                }
                hit
            };
            if in_inheritance {
                RefKind::Extend
            } else {
                RefKind::TypeUse
            }
        }
        _ => RefKind::Read,
    }
}
