//! Swift extraction, written against tree-sitter-swift 0.7.3 node
//! shapes verified by `parsing`'s `#[ignore]`d ground-truth dumps.
//!
//! Declaration/member dispatch is TABLE-driven, following the same pattern
//! `kndo-adapter-kotlin` established (and the same reason: kndo's own CRAP gate flags any
//! function whose branch count — a flat `match` arm counts as one — pushes complexity past 5
//! under zero coverage, and this adapter has more declaration shapes than that ceiling allows
//! in one dispatcher).

use kndo_adapter_toolkit::metrics::{
    push_accessor_metrics as toolkit_push_accessor_metrics,
    push_function_metrics as toolkit_push_function_metrics, MetricsSyntax, MIN_CLONE_TOKENS,
};
use kndo_adapter_toolkit::parsing::{find_child, span, text};
use kndo_core::adapter::{
    AdapterDiagnostic, DiagnosticLevel, FileFacts, ImportBinding, ImportKind, RawImport,
    RawReference, RawRoot, RawRootTarget, Span,
};
use kndo_core::vocab::{Confidence, RefKind, RootKind, SymbolKind};
use smol_str::SmolStr;
use tree_sitter::Node;

const GENERATED_MARKERS: kndo_adapter_toolkit::classify::ContentMarkers =
    kndo_adapter_toolkit::classify::ContentMarkers {
        generated_markers: &[
            kndo_adapter_toolkit::classify::LineMarker::Contains("Generated by"),
            kndo_adapter_toolkit::classify::LineMarker::Contains("generated by"),
            kndo_adapter_toolkit::classify::LineMarker::Contains("DO NOT EDIT"),
        ],
        scan_window_lines: 64,
        comment_openers: &["//", "/*", "*"],
    };

/// `switch_entry` counts once per arm (matching every other
/// adapter's n-way-match rule); `guard_statement` is an implicit early-return conditional,
/// counted same as `if`; `catch_block` (not `do_statement`) counts per catch clause, matching
/// Java's try/catch convention exactly. Nil-coalescing (`??`) and force-unwrap (`!`) are
/// deliberately NOT branches — value-producing operators, not control-flow forks.
const METRICS_SYNTAX: MetricsSyntax = MetricsSyntax {
    branch_kinds: &[
        "if_statement",
        "guard_statement",
        "switch_entry",
        "for_statement",
        "while_statement",
        "catch_block",
        "&&",
        "||",
    ],
    identifier_kinds: &["simple_identifier", "type_identifier"],
    literal_kinds: &[
        "line_string_literal",
        "multi_line_string_literal",
        "integer_literal",
        "hex_literal",
        "oct_literal",
        "bin_literal",
        "real_literal",
        "boolean_literal",
        "nil",
    ],
    skip_kinds: &["comment", "multiline_comment"],
    // Each of these becomes its own shape when it is substantial enough to carry clone
    // evidence by itself; a small one stays an expression inside its owner.
    // NOT `lambda_function_type`: that is a closure TYPE annotation, not a body.
    nested_callable_kinds: &["lambda_literal"],
    // Empty for the same reason as Kotlin: Swift construction is a plain
    // `call_expression`, so there is no node kind that means "construction" to report.
    construction_kinds: &[],
};

/// Item-walk context: the member owner (a struct/class/enum/protocol/extension's bare name),
/// for `member_of` attribution — an `extension`'s members carry the EXTENDED
/// type's name here, not any name of the extension block itself (which has none).
struct Ctx<'a> {
    owner: Option<&'a str>,
    /// The owner type (or extension) declares at least one inheritance/conformance entry:
    /// its non-private methods may be protocol witnesses invoked through machinery outside
    /// the repo (a custom `KeyedEncodingContainerProtocol` implementation is called by the
    /// stdlib's Codable synthesis — no source call site can exist). Requirements of external
    /// protocols aren't enumerable statically, so such methods root at `Possible` — the
    /// dynamic-dispatch tier, degrading toward silence.
    owner_conforms: bool,
    /// A top-level (`owner: None`) `let`/`var` is a lazily-initialized global in
    /// an ordinary file — its initializer only runs on first access, so `within` names the
    /// global itself, not `None`. `main.swift`'s top-level code is the one exception:
    /// it's a script, executing procedurally at load like any other module-load statement.
    /// Irrelevant once `owner` is `Some` (member initializers already have their own `within`).
    top_level_lazy: bool,
}

type DeclHandler = fn(Node, &[u8], &Ctx<'_>, &mut FileFacts);

const DECL_HANDLERS: &[(&str, DeclHandler)] = &[
    ("class_declaration", handle_type),
    ("protocol_declaration", handle_protocol),
    ("function_declaration", handle_function),
    // A protocol's method requirement — no body, just a signature.
    ("protocol_function_declaration", handle_function),
    ("init_declaration", handle_init),
    ("deinit_declaration", handle_deinit),
    ("property_declaration", handle_property),
    ("typealias_declaration", handle_type_alias),
    ("enum_entry", handle_enum_entry),
];

fn dispatch_declaration(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some((_, handler)) = DECL_HANDLERS.iter().find(|(k, _)| *k == item.kind()) else {
        return;
    };
    handler(item, src, ctx, out);
}

pub(crate) fn extract(path: &str, content: &[u8]) -> FileFacts {
    let mut out = FileFacts::default();
    if GENERATED_MARKERS.detect_generated(content) {
        out.detected_origin = Some(kndo_core::vocab::FileOrigin::Generated);
    }

    let Some(tree) = crate::parsing::parse(content) else {
        out.diagnostics.push(AdapterDiagnostic {
            level: DiagnosticLevel::Warn,
            message: "failed to initialize the Swift parser".to_string(),
            span: None,
        });
        return out;
    };
    let root = tree.root_node();
    if root.has_error() {
        out.diagnostics.push(AdapterDiagnostic {
            level: DiagnosticLevel::Warn,
            message: "parse errors — extraction is partial for this file".to_string(),
            span: None,
        });
    }

    out.unit = crate::manifest::unit_for_path(path).map(SmolStr::new);
    out.unit_name = out.unit.clone();

    walk_top_level(root, content, !is_main_swift(path), &mut out);
    // `main.swift`: the whole file's top-level code runs unconditionally at process
    // start — a filename convention SwiftPM itself enforces, not a heuristic.
    if is_main_swift(path) {
        out.roots.push(RawRoot {
            kind: RootKind::Production,
            target: RawRootTarget::WholeFile,
            confidence: Confidence::Certain,
        });
    }
    kndo_adapter_toolkit::suppression::collect_suppressions(
        root,
        content,
        &["comment", "multiline_comment"],
        &mut out.suppressions,
    );
    out
}

fn is_main_swift(path: &str) -> bool {
    path.rsplit('/').next() == Some("main.swift")
}

/// `source_file`'s children: declarations dispatch as usual (each handler already
/// walks its own body/value for references), but a `.swift` file — `main.swift` above all —
/// can *also* carry bare top-level executable statements (SwiftPM's "top-level code" file), the
/// same shape as a function body. Anything `DECL_HANDLERS` doesn't recognize is walked as body
/// content instead of silently dropped, or a `helper.live()` statement sitting directly in
/// `main.swift` would leave no reference behind at all.
fn walk_top_level(root: Node, content: &[u8], top_level_lazy: bool, out: &mut FileFacts) {
    let top = Ctx {
        owner: None,
        owner_conforms: false,
        top_level_lazy,
    };
    for item in root.children(&mut root.walk()) {
        match item.kind() {
            "import_declaration" => handle_import(item, content, out),
            kind if DECL_HANDLERS.iter().any(|(k, _)| *k == kind) => {
                dispatch_declaration(item, content, &top, out);
            }
            _ => walk_body(item, content, None, out),
        }
    }
}

fn handle_import(item: Node, src: &[u8], out: &mut FileFacts) {
    let Some(module) = item
        .children(&mut item.walk())
        .find(|n| n.kind() == "identifier")
    else {
        return;
    };
    let name = text(module, src);
    out.imports.push(RawImport {
        specifier: SmolStr::new(name),
        kind: ImportKind::Package,
        span: span(item),
        side_effect_only: false,
        type_only: false,
        confidence: Confidence::Certain,
        bindings: vec![ImportBinding {
            local: SmolStr::new(name),
            imported: Some(SmolStr::new(name)),
        }],
        reexported: false,
        opaque_namespace_use: false,
        // `import SomeKit` puts every top-level name of the module in bare scope — no
        // per-name binding syntax exists. The core's bare-name fallback consults the
        // resolved target's whole unit for imports carrying this.
        module_names_visible: true,
        local_alias: None,
        reconstructed: false,
    });
}

// ---------------------------------------------------------------- visibility

const VISIBILITY_LEVELS: &[(&str, u8)] = &[
    ("private", 0),
    ("fileprivate", 1),
    ("internal", 2),
    ("public", 3),
    ("open", 4),
];

/// `[File "private", File "fileprivate", Package "internal", Public "public", Public "open"]`.
/// No modifier at all defaults to `internal` (2) — Swift's own default, applying
/// uniformly at top-level and member position alike (no restricted subset the way Java/
/// Kotlin's ladders have).
fn visibility(item: Node) -> (u8, bool) {
    let level = visibility_keyword(item)
        .and_then(|kw| VISIBILITY_LEVELS.iter().find(|(k, _)| *k == kw))
        .map_or(2, |(_, l)| *l);
    (level, level >= 3)
}

fn visibility_keyword(item: Node) -> Option<&'static str> {
    let modifiers = modifiers_node(item)?;
    let vis = modifiers
        .children(&mut modifiers.walk())
        .find(|n| n.kind() == "visibility_modifier")?;
    vis.children(&mut vis.walk())
        .find_map(|c| VISIBILITY_LEVELS.iter().find(|(k, _)| *k == c.kind()))
        .map(|(k, _)| *k)
}

fn modifiers_node(item: Node) -> Option<Node> {
    item.children(&mut item.walk())
        .find(|n| n.kind() == "modifiers")
}

/// `@main`: an independent, `Certain`-confidence root trigger alongside `main.swift`'s
/// whole-file promotion — SwiftPM itself resolves the attributed type's `static func main()` as
/// the executable entry point, not a heuristic.
fn has_main_attribute(item: Node, src: &[u8]) -> bool {
    let Some(modifiers) = modifiers_node(item) else {
        return false;
    };
    modifiers
        .children(&mut modifiers.walk())
        .filter(|n| n.kind() == "attribute")
        .any(|attr| last_identifier_text(attr, src) == Some("main"))
}

fn has_modifier_wrapper(item: Node, wrapper: &str, keyword: &str) -> bool {
    let Some(modifiers) = modifiers_node(item) else {
        return false;
    };
    let Some(found) = modifiers
        .children(&mut modifiers.walk())
        .find(|n| n.kind() == wrapper)
    else {
        return false;
    };
    found
        .children(&mut found.walk())
        .any(|c| c.kind() == keyword)
}

// ---------------------------------------------------------------- struct/class/enum/extension

const CLASS_KIND_TABLE: &[(&str, SymbolKind)] = &[
    ("class", SymbolKind::Class),
    ("struct", SymbolKind::Struct),
    ("enum", SymbolKind::Enum),
];

fn class_symbol_kind(item: Node, src: &[u8]) -> Option<SymbolKind> {
    let kind_node = item.child_by_field_name("declaration_kind")?;
    CLASS_KIND_TABLE
        .iter()
        .find(|(k, _)| *k == text(kind_node, src))
        .map(|(_, sk)| sk.clone())
}

fn handle_type(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(name) = type_declaration_name(item, src) else {
        return;
    };
    if let Some(kind) = class_symbol_kind(item, src) {
        let vis = visibility(item);
        push_declaration(out, name, kind, item, None, ctx.owner, vis);
    }
    emit_main_root_if_attributed(item, src, name, out);
    emit_type_inheritance_refs(item, src, name, out);
    if let Some(body) = find_any_child(item, &["class_body", "enum_class_body"]) {
        handle_body(body, src, name, has_conformances(item), out);
    }
}

/// `@main` roots the attributed type's `static func main()` at `Certain`.
fn emit_main_root_if_attributed(item: Node, src: &[u8], name: &str, out: &mut FileFacts) {
    if !has_main_attribute(item, src) {
        return;
    }
    out.roots.push(RawRoot {
        kind: RootKind::Production,
        target: RawRootTarget::Declaration(SmolStr::new(format!("{name}.main"))),
        confidence: Confidence::Certain,
    });
}

/// Superclass/protocol conformance: both the single `inherits_from`-fielded specifier
/// most declarations carry and any additional ones in a multi-conformance list.
fn has_conformances(item: Node) -> bool {
    item.child_by_field_name("inherits_from").is_some()
        || item
            .children(&mut item.walk())
            .any(|c| c.kind() == "inheritance_specifier")
}

fn emit_type_inheritance_refs(item: Node, src: &[u8], name: &str, out: &mut FileFacts) {
    if let Some(inherited) = item.child_by_field_name("inherits_from") {
        walk_extend_refs(inherited, src, name, out);
    }
    for child in item.children(&mut item.walk()) {
        if child.kind() == "inheritance_specifier" {
            walk_extend_refs(child, src, name, out);
        }
    }
}

/// `class_declaration`'s own name (a plain `type_identifier`) vs `extension`'s (a `user_type`,
/// possibly qualified — the last identifier segment is the extended type's bare name).
fn type_declaration_name<'a>(item: Node, src: &'a [u8]) -> Option<&'a str> {
    let name_node = item.child_by_field_name("name")?;
    if name_node.kind() == "user_type" {
        return last_identifier_text(name_node, src);
    }
    Some(text(name_node, src))
}

fn handle_protocol(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = text(name_node, src);
    let vis = visibility(item);
    push_declaration(out, name, SymbolKind::Interface, item, None, ctx.owner, vis);
    for child in item.children(&mut item.walk()) {
        if child.kind() == "inheritance_specifier" {
            walk_extend_refs(child, src, name, out);
        }
    }
    if let Some(body) = find_child(item, "protocol_body") {
        handle_body(body, src, name, has_conformances(item), out);
    }
}

/// Iterates a `class_body`/`enum_class_body`/`protocol_body`'s members through the shared
/// declaration dispatch table.
fn handle_body(body: Node, src: &[u8], owner: &str, owner_conforms: bool, out: &mut FileFacts) {
    let ctx = Ctx {
        owner: Some(owner),
        owner_conforms,
        top_level_lazy: false, // unused once `owner` is `Some` — members have their own `within`
    };
    for member in body.children(&mut body.walk()) {
        dispatch_declaration(member, src, &ctx, out);
    }
}

// ---------------------------------------------------------------- functions & initializers

fn handle_function(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = text(name_node, src);
    let vis = visibility(item);
    let (kind, qualified) = qualify(ctx.owner, name);
    let body = find_child(item, "function_body");
    let signature_span = body.map(|b| Span {
        start: span(item).start,
        end: span(b).start,
    });
    push_declaration(out, name, kind, item, signature_span, ctx.owner, vis);
    root_if_dispatch_target(item, &qualified, out);
    // Possible-confidence witness root (Ctx::owner_conforms docs): internal or wider only —
    // a private method can never witness a protocol requirement.
    if ctx.owner_conforms && vis.0 >= 2 {
        out.roots.push(RawRoot {
            kind: RootKind::Production,
            target: RawRootTarget::Declaration(SmolStr::new(&qualified)),
            confidence: Confidence::Possible,
        });
    }

    walk_function_signature(item, src, Some(&qualified), out);
    if let Some(body) = body {
        walk_body(body, src, Some(&qualified), out);
        push_function_metrics(out, &qualified, span(item), body);
    }
}

fn qualify(owner: Option<&str>, name: &str) -> (SymbolKind, String) {
    let Some(owner) = owner else {
        return (SymbolKind::Function, name.to_string());
    };
    (SymbolKind::Method, format!("{owner}.{name}"))
}

/// `override` dispatch rooting — the `member_modifier` keyword, structurally
/// identical to Kotlin's `override`.
fn root_if_dispatch_target(item: Node, qualified: &str, out: &mut FileFacts) {
    if !has_modifier_wrapper(item, "member_modifier", "override") {
        return;
    }
    out.roots.push(RawRoot {
        kind: RootKind::Production,
        target: RawRootTarget::Declaration(SmolStr::new(qualified)),
        confidence: Confidence::Probable,
    });
    // Machinery dispatch: an explicit `override` is invoked through the
    // superclass — a tested owner plausibly has its overrides executed. Protocol witnesses
    // deliberately stay out (no keyword marks them; blanket-marking every method of a
    // conforming type would erase real untested signal — degrade toward silence only on
    // the precise fact).
    if let Some(d) = out
        .declarations
        .last_mut()
        .filter(|d| d.member_of.is_some())
    {
        d.implicitly_invoked = true;
    }
}

/// The function's own signature children — parameters/return type/generic bounds — plus
/// default parameter values. A default expression is a SIBLING of its `parameter` (after a
/// bare `=` token, tree-sitter-swift 0.7): calling the function with the argument omitted
/// executes the default, so its references belong `within` the function like body code
/// (e.g. `mode: Mode = .standard` — callers construct the value bare and still
/// exercise `.standard`'s arm). Dot-shorthand defaults qualify by the
/// parameter's own declared type — the one place the type is textually certain.
/// `function_body`'s kind never matches any arm below, so it's naturally skipped.
fn walk_function_signature(item: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    let mut param_type: Option<String> = None;
    let mut pending_default = false;
    for child in item.children(&mut item.walk()) {
        if matches!(
            child.kind(),
            "user_type" | "optional_type" | "type_parameters" | "parameter"
        ) {
            walk_type_refs(child, src, within, out);
            note_parameter(child, src, &mut param_type, &mut pending_default);
        } else {
            pending_default = default_step(child, src, pending_default, &param_type, within, out);
        }
    }
}

/// The `= <expr>` state machine outside type/parameter children: `=` arms it (only after a
/// typed parameter), the very next child is the default expression, anything else disarms.
fn default_step(
    child: Node,
    src: &[u8],
    pending: bool,
    param_type: &Option<String>,
    within: Option<&str>,
    out: &mut FileFacts,
) -> bool {
    if child.kind() == "=" {
        return param_type.is_some();
    }
    if pending {
        walk_default_value(child, src, param_type.as_deref(), within, out);
    }
    false
}

/// Remembers a `parameter`'s declared type for the default-value walk; other signature
/// children leave the state untouched.
fn note_parameter(
    child: Node,
    src: &[u8],
    param_type: &mut Option<String>,
    pending_default: &mut bool,
) {
    if child.kind() != "parameter" {
        return;
    }
    *param_type = find_child(child, "user_type").map(|t| text(t, src).to_string());
    *pending_default = false;
}

/// One default-value expression: dot-shorthand (`.numeric`, a `prefix_expression` led by
/// `.`) resolves against the parameter's declared type — emitted as a member reference with
/// that type as `scope_context`; every other shape is ordinary body code.
fn walk_default_value(
    expr: Node,
    src: &[u8],
    param_type: Option<&str>,
    within: Option<&str>,
    out: &mut FileFacts,
) {
    let shorthand = expr.kind() == "prefix_expression" && text(expr, src).starts_with('.');
    if let (true, Some(ty)) = (shorthand, param_type) {
        if let Some(member) = find_child(expr, "simple_identifier") {
            out.references.push(RawReference {
                name: SmolStr::new(text(member, src)),
                scope_context: Some(SmolStr::new(ty)),
                span: span(expr),
                within: within.map(SmolStr::new),
                kind: RefKind::Read,
            });
            return;
        }
    }
    walk_body(expr, src, within, out);
}

/// `deinit { … }` — the runtime invokes it when an instance dies, so like `init` it gets the
/// Constructor treatment: liveness follows the type (the core's container→constructor edge),
/// and its body's references (a stored closure fired on teardown)
/// stay visible instead of silently unwalked.
fn handle_deinit(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(owner) = ctx.owner else {
        return;
    };
    let qualified = format!("{owner}.<deinit>");
    push_declaration(
        out,
        "<deinit>",
        SymbolKind::Constructor,
        item,
        None,
        Some(owner),
        visibility(item),
    );
    if let Some(body) = find_child(item, "function_body") {
        walk_body(body, src, Some(&qualified), out);
    }
}

fn handle_init(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(owner) = ctx.owner else {
        return;
    };
    let vis = visibility(item);
    let qualified = format!("{owner}.<init>");
    let body = find_child(item, "function_body");
    let signature_span = body.map(|b| Span {
        start: span(item).start,
        end: span(b).start,
    });
    push_declaration(
        out,
        "<init>",
        SymbolKind::Constructor,
        item,
        signature_span,
        Some(owner),
        vis,
    );
    // Same signature walk as functions — inits are where default parameter values matter
    // most (a configuration-heavy `init` can carry a dozen of them).
    walk_function_signature(item, src, Some(&qualified), out);
    if let Some(body) = body {
        walk_body(body, src, Some(&qualified), out);
        push_function_metrics(out, &qualified, span(item), body);
    }
}

fn push_function_metrics(out: &mut FileFacts, qualified: &str, decl_span: Span, body: Node) {
    toolkit_push_function_metrics(
        out,
        qualified,
        decl_span,
        body,
        &METRICS_SYNTAX,
        MIN_CLONE_TOKENS,
    );
}

// ---------------------------------------------------------------- properties, type aliases, enum entries

fn handle_property(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(name_pattern) = item.child_by_field_name("name") else {
        return;
    };
    let Some(name_node) = find_child(name_pattern, "simple_identifier") else {
        return;
    };
    let name = text(name_node, src);
    let vis = visibility(item);
    push_declaration(
        out,
        name,
        property_symbol_kind(item, ctx),
        item,
        None,
        ctx.owner,
        vis,
    );
    if let Some(annotation) = find_child(item, "type_annotation") {
        walk_type_refs(annotation, src, ctx.owner, out);
    }
    walk_property_bodies(item, src, property_value_within(ctx, name), out);
    // A computed property is a callable and now says so in its kind — so it must have a shape
    // too, or `crap` and `duplicate` cannot see a getter however gnarly it is. Observers are
    // deliberately excluded: `willSet`/`didSet` run around a store, they are not the property.
    let accessors = computed_accessor_bodies(item);
    if !accessors.is_empty() {
        let (_, qualified) = qualify(ctx.owner, name);
        toolkit_push_accessor_metrics(
            out,
            &qualified,
            span(item),
            accessors,
            &METRICS_SYNTAX,
            MIN_CLONE_TOKENS,
        );
    }
}

/// Every accessor body of a computed property, in source order. Verified against
/// tree-sitter-swift 0.7.3's `node-types.json`: a `computed_property` holds either a bare
/// `statements` child (the implicit-getter shorthand `var x: Int { 1 + 2 }`) or one
/// `computed_getter`/`computed_setter`/`computed_modify` per accessor, each with its own
/// `statements`. Source order, so the numbering is faithful and deterministic together.
fn computed_accessor_bodies(item: Node) -> Vec<Node> {
    let Some(computed) = find_child(item, "computed_property") else {
        return Vec::new();
    };
    let mut c = computed.walk();
    computed
        .children(&mut c)
        .filter_map(|n| match n.kind() {
            "statements" => Some(n),
            "computed_getter" | "computed_setter" | "computed_modify" => {
                find_child(n, "statements")
            }
            _ => None,
        })
        .collect()
}

/// A **computed** property is a getter, not a value: `var isValid: Bool { … }` compiles to a
/// method and has a body a test can exercise, where `static let https = Scheme("https")` has a
/// value and nothing to exercise. Calling both `Field` made the kind unable to tell a header-name
/// constant from real logic, which is what let `untested` accuse 185 of vapor's stored constants
/// of not being tested.
///
/// `willSet`/`didSet` observers do NOT make a property computed — the property still stores its
/// value, and the observers run around the store rather than instead of it.
fn property_symbol_kind(item: Node, ctx: &Ctx<'_>) -> SymbolKind {
    let computed = find_child(item, "computed_property").is_some();
    match (computed, ctx.owner.is_some()) {
        (true, true) => SymbolKind::Method,
        (true, false) => SymbolKind::Function,
        (false, true) => SymbolKind::Field,
        (false, false) => SymbolKind::Variable,
    }
}

/// A top-level global's initializer/getter/observer only runs on first access or
/// on each read/write (Swift globals are always lazily-initialized) — `within` names the
/// global itself, unless this is `main.swift`'s procedurally-executed top-level code
/// (`top_level_lazy: false`).
fn property_value_within<'a>(ctx: &Ctx<'a>, name: &'a str) -> Option<&'a str> {
    match ctx.owner {
        Some(owner) => Some(owner),
        None if ctx.top_level_lazy => Some(name),
        None => None,
    }
}

/// Computed-property/observer bodies (get/set/willSet/didSet) are the property's OWN liveness
/// unit, walked but not independently declared.
fn walk_property_bodies(item: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    if let Some(value) = item.child_by_field_name("value") {
        walk_body(value, src, within, out);
    }
    if let Some(computed) = find_child(item, "computed_property") {
        walk_body(computed, src, within, out);
    }
    if let Some(observers) = find_child(item, "willset_didset_block") {
        walk_body(observers, src, within, out);
    }
}

fn handle_type_alias(item: Node, src: &[u8], _ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    push_declaration(
        out,
        text(name_node, src),
        SymbolKind::TypeAlias,
        item,
        None,
        None,
        (3, true),
    );
    if let Some(ty) = find_child(item, "user_type") {
        walk_type_refs(ty, src, None, out);
    }
}

fn handle_enum_entry(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(owner) = ctx.owner else {
        return;
    };
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    push_declaration(
        out,
        text(name_node, src),
        SymbolKind::EnumMember,
        item,
        None,
        Some(owner),
        (3, true),
    );
}

fn push_declaration(
    out: &mut FileFacts,
    name: &str,
    kind: SymbolKind,
    item: Node,
    signature_span: Option<Span>,
    member_of: Option<&str>,
    (level, exported): (u8, bool),
) {
    out.declarations.push(kndo_core::adapter::Declaration {
        name: SmolStr::new(name),
        kind,
        span: span(item),
        exported,
        visibility: kndo_core::adapter::VisibilityLevel(level),
        member_of: member_of.map(SmolStr::new),
        implicitly_invoked: false,
        nested_scope: false,
        visibility_inherited: false,
        visible_in_unit: None,
        implements: None,
        markers: Vec::new(),
        signature_span,
    });
}

// ---------------------------------------------------------------- type refs & inheritance

/// `user_type`/`optional_type` positions → `TypeUse`; recurses into `type_arguments`
/// for generics but not into the base path's own segments (already captured by
/// `last_identifier_text`).
fn walk_type_refs(node: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    if node.kind() == "optional_type" {
        if let Some(wrapped) = node.child_by_field_name("wrapped") {
            walk_type_refs(wrapped, src, within, out);
        }
        return;
    }
    if node.kind() != "user_type" {
        for child in node.children(&mut node.walk()) {
            walk_type_refs(child, src, within, out);
        }
        return;
    }
    emit_type_use_ref(node, src, within, out);
}

fn emit_type_use_ref(node: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    if let Some(name) = last_identifier_text(node, src) {
        out.references.push(RawReference {
            name: SmolStr::new(name),
            scope_context: None,
            span: span(node),
            within: within.map(SmolStr::new),
            kind: RefKind::TypeUse,
        });
    }
    if let Some(args) = find_child(node, "type_arguments") {
        walk_type_refs(args, src, within, out);
    }
}

/// The base path's own last `type_identifier` segment, recursing into a nested `user_type`
/// (qualified-path nesting) but not into `type_arguments`.
fn last_identifier_text<'a>(node: Node, src: &'a [u8]) -> Option<&'a str> {
    let mut result = None;
    for child in node.children(&mut node.walk()) {
        match child.kind() {
            "type_identifier" => result = Some(text(child, src)),
            "user_type" => result = last_identifier_text(child, src).or(result),
            _ => {}
        }
    }
    result
}

fn walk_extend_refs(node: Node, src: &[u8], owner: &str, out: &mut FileFacts) {
    if node.kind() == "inheritance_specifier" {
        emit_extend_ref(
            node.child_by_field_name("inherits_from"),
            node,
            src,
            owner,
            out,
        );
        return;
    }
    if node.kind() == "user_type" {
        emit_extend_ref(Some(node), node, src, owner, out);
        return;
    }
    for child in node.children(&mut node.walk()) {
        walk_extend_refs(child, src, owner, out);
    }
}

fn emit_extend_ref(ty: Option<Node>, site: Node, src: &[u8], owner: &str, out: &mut FileFacts) {
    let Some(name) = ty.and_then(|t| last_identifier_text(t, src)) else {
        return;
    };
    out.references.push(RawReference {
        name: SmolStr::new(name),
        scope_context: None,
        span: span(site),
        within: Some(SmolStr::new(owner)),
        kind: RefKind::Extend,
    });
}

// ---------------------------------------------------------------- expression/body references

type BodyHandler = fn(Node, &[u8], Option<&str>, &mut FileFacts);

const BODY_HANDLERS: &[(&str, BodyHandler)] = &[
    ("call_expression", handle_call),
    ("navigation_expression", handle_navigation),
    ("user_type", walk_type_refs),
    ("simple_identifier", handle_identifier_ref),
];

/// Expression/statement bodies: calls, navigation (member/property access), bare identifier
/// reads, type positions inside expressions — table-driven for the same CRAP-ceiling reason
/// `DECL_HANDLERS` is.
fn walk_body(node: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    if matches!(node.kind(), "comment" | "multiline_comment") {
        return;
    }
    if let Some((_, handler)) = BODY_HANDLERS.iter().find(|(k, _)| *k == node.kind()) {
        handler(node, src, within, out);
        return;
    }
    for child in node.children(&mut node.walk()) {
        walk_body(child, src, within, out);
    }
}

fn handle_identifier_ref(node: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    if !is_reference_position(node) {
        return;
    }
    out.references.push(RawReference {
        name: SmolStr::new(text(node, src)),
        scope_context: None,
        span: span(node),
        within: within.map(SmolStr::new),
        kind: RefKind::Read,
    });
}

fn handle_call(node: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    let mut cursor = node.walk();
    let mut children = node.children(&mut cursor);
    let Some(callee) = children.next() else {
        return;
    };
    emit_call_ref(callee, src, within, out);
    for child in children {
        walk_body(child, src, within, out);
    }
}

fn emit_call_ref(callee: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    match callee.kind() {
        "simple_identifier" => out.references.push(RawReference {
            name: SmolStr::new(text(callee, src)),
            scope_context: None,
            span: span(callee),
            within: within.map(SmolStr::new),
            kind: RefKind::Call,
        }),
        "navigation_expression" => emit_navigation_ref(callee, src, within, out, RefKind::Call),
        _ => walk_body(callee, src, within, out),
    }
}

fn handle_navigation(node: Node, src: &[u8], within: Option<&str>, out: &mut FileFacts) {
    emit_navigation_ref(node, src, within, out, RefKind::Read);
}

/// `a.b`/`a.b.c()` — the terminal segment becomes the reference, `scope_context` is set when
/// the target is a plain identifier/`self`; a complex target (a nested navigation/
/// call) is walked for its own references instead.
fn emit_navigation_ref(
    node: Node,
    src: &[u8],
    within: Option<&str>,
    out: &mut FileFacts,
    kind: RefKind,
) {
    let (Some(target), Some(suffix)) = (
        node.child_by_field_name("target"),
        node.child_by_field_name("suffix"),
    ) else {
        return;
    };
    let Some(name_node) = find_child(suffix, "simple_identifier") else {
        return;
    };
    out.references.push(RawReference {
        name: SmolStr::new(text(name_node, src)),
        scope_context: simple_qualifier_text(target, src).map(SmolStr::new),
        span: span(node),
        within: within.map(SmolStr::new),
        kind,
    });
    if simple_qualifier_text(target, src).is_some() {
        if target.kind() == "simple_identifier" {
            out.references.push(RawReference {
                name: SmolStr::new(text(target, src)),
                scope_context: None,
                span: span(target),
                within: within.map(SmolStr::new),
                kind: RefKind::Read,
            });
        }
    } else {
        walk_body(target, src, within, out);
    }
}

fn simple_qualifier_text<'a>(node: Node, src: &'a [u8]) -> Option<&'a str> {
    match node.kind() {
        "simple_identifier" => Some(text(node, src)),
        "self_expression" => Some("self"),
        _ => None,
    }
}

/// Whether a bare identifier here reads a value (vs. binding a new name in a parameter/
/// declaration pattern).
fn is_reference_position(node: Node) -> bool {
    let Some(parent) = node.parent() else {
        return false;
    };
    !matches!(parent.kind(), "parameter" | "pattern" | "bound_identifier")
}

// ---------------------------------------------------------------- small tree helpers

fn find_any_child<'a>(node: Node<'a>, kinds: &[&str]) -> Option<Node<'a>> {
    node.children(&mut node.walk())
        .find(|n| kinds.contains(&n.kind()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn facts(src: &str) -> FileFacts {
        extract("Sources/MyLib/Main.swift", src.as_bytes())
    }

    fn decl<'a>(f: &'a FileFacts, name: &str) -> &'a kndo_core::adapter::Declaration {
        f.declarations.iter().find(|d| d.name == name).unwrap()
    }

    #[test]
    fn a_computed_property_gets_a_shape_and_a_stored_one_does_not() {
        // Reclassifying computed properties to `Method` without giving them a shape left a
        // callable `crap` and `duplicate` could not see. One symbol, one numbering: the getter
        // is ordinal 0 (reading the property runs it) and the setter continues, so the two
        // cannot collide on a nested shape's identity.
        let f = facts(
            "struct S {\n\
             \x20   var stored: Int = 0\n\
             \x20   var computed: Int { return stored + 1 }\n\
             \x20   var both: Int {\n\
             \x20       get { return stored }\n\
             \x20       set { stored = newValue }\n\
             \x20   }\n\
             \x20   var observed: Int = 0 {\n\
             \x20       didSet { print(observed) }\n\
             \x20   }\n\
             }\n",
        );
        let shapes = |name: &str| -> Vec<u16> {
            let mut o: Vec<u16> = f
                .functions
                .iter()
                .filter(|m| m.symbol == name)
                .map(|m| m.shape_ordinal)
                .collect();
            o.sort();
            o
        };
        assert_eq!(
            shapes("S.computed"),
            vec![0],
            "the implicit getter is one shape"
        );
        assert_eq!(
            shapes("S.both"),
            vec![0, 1],
            "get and set are two, numbered once"
        );
        assert!(
            shapes("S.stored").is_empty(),
            "a stored property is a value"
        );
        assert!(
            shapes("S.observed").is_empty(),
            "observers run around a store; the property is still stored"
        );
    }

    #[test]
    fn unit_is_derived_from_the_sources_path_convention() {
        let f = facts("class Widget {}\n");
        assert_eq!(f.unit.as_deref(), Some("MyLib"));
        assert_eq!(f.unit_name.as_deref(), Some("MyLib"));
    }

    #[test]
    fn a_loose_path_leaves_unit_none() {
        let f = extract("scripts/loose.swift", b"class Widget {}\n");
        assert_eq!(f.unit, None);
    }

    #[test]
    fn a_computed_property_is_a_callable_and_a_stored_one_is_not() {
        // The kind has to separate `static let https = Scheme("https")` — a value with nothing
        // to exercise — from `var isValid: Bool { … }`, which is a getter with a body. Both
        // used to be `Field`, so nothing downstream could tell a header-name constant from
        // real logic.
        let f = facts(
            "struct Scheme {\n\
             \x20   static let https = Scheme()\n\
             \x20   var isValid: Bool { return true }\n\
             \x20   var stored: Int = 0 {\n\
             \x20       didSet { print(stored) }\n\
             \x20   }\n\
             }\n\
             var topLevelComputed: Int { return 1 }\n\
             let topLevelStored = 2\n",
        );
        assert_eq!(decl(&f, "https").kind, SymbolKind::Field);
        assert_eq!(decl(&f, "isValid").kind, SymbolKind::Method);
        assert_eq!(
            decl(&f, "stored").kind,
            SymbolKind::Field,
            "willSet/didSet observers run AROUND the store — the property still stores a value"
        );
        assert_eq!(
            decl(&f, "topLevelComputed").kind,
            SymbolKind::Function,
            "a computed global is a getter function, not a method of anything"
        );
        assert_eq!(decl(&f, "topLevelStored").kind, SymbolKind::Variable);
    }

    #[test]
    fn declarations_cover_the_type_zoo() {
        let f = facts(
            "class Widget {\n\
             \x20   private let x: Int = 1\n\
             \x20   internal func compute() -> Int { return x }\n\
             \x20   init() {}\n\
             \x20   struct Inner {\n\
             \x20       func innerFn() {}\n\
             \x20   }\n\
             }\n\
             protocol Greeter {\n\
             \x20   func go()\n\
             }\n\
             enum Color {\n\
             \x20   case red\n\
             \x20   case green\n\
             }\n\
             typealias Alias = String\n\
             func topLevelFn() {}\n\
             let topLevelVal = 5\n",
        );
        let names: Vec<&str> = f.declarations.iter().map(|d| d.name.as_str()).collect();
        for expected in [
            "Widget",
            "x",
            "compute",
            "<init>",
            "Inner",
            "innerFn",
            "Greeter",
            "go",
            "Color",
            "red",
            "green",
            "Alias",
            "topLevelFn",
            "topLevelVal",
        ] {
            assert!(names.contains(&expected), "missing {expected}: {names:?}");
        }
        assert_eq!(decl(&f, "x").member_of.as_deref(), Some("Widget"));
        assert_eq!(decl(&f, "Inner").member_of.as_deref(), Some("Widget"));
        assert_eq!(decl(&f, "innerFn").member_of.as_deref(), Some("Inner"));
        assert_eq!(decl(&f, "go").member_of.as_deref(), Some("Greeter"));
        assert_eq!(decl(&f, "red").member_of.as_deref(), Some("Color"));
        assert_eq!(decl(&f, "topLevelFn").member_of, None);
    }

    #[test]
    fn visibility_maps_to_the_five_rung_ladder_with_internal_default() {
        let f = facts(
            "class C {\n\
             \x20   private let a = 1\n\
             \x20   fileprivate let b = 1\n\
             \x20   internal let c = 1\n\
             \x20   public let d = 1\n\
             \x20   open var e = 1\n\
             \x20   let f = 1\n\
             }\n",
        );
        assert_eq!(decl(&f, "a").visibility.0, 0);
        assert!(!decl(&f, "a").exported);
        assert_eq!(decl(&f, "b").visibility.0, 1);
        assert_eq!(decl(&f, "c").visibility.0, 2);
        assert_eq!(decl(&f, "d").visibility.0, 3);
        assert!(decl(&f, "d").exported);
        assert_eq!(decl(&f, "e").visibility.0, 4);
        assert!(decl(&f, "e").exported, "open is exported too");
        assert_eq!(
            decl(&f, "f").visibility.0,
            2,
            "no modifier defaults to internal"
        );
    }

    #[test]
    fn plain_import_binds_the_module_name() {
        let f = facts("import Foundation\nclass C {}\n");
        let imp = f
            .imports
            .iter()
            .find(|i| i.specifier == "Foundation")
            .unwrap();
        assert!(imp.bindings.iter().any(|b| b.local == "Foundation"));
    }

    #[test]
    fn override_roots_production_probable() {
        let f = facts(
            "protocol Iface { func go() }\n\
             class C: Iface {\n\
             \x20   override func go() {}\n\
             \x20   func plain() {}\n\
             }\n",
        );
        let root = f
            .roots
            .iter()
            .find(|r| matches!(&r.target, RawRootTarget::Declaration(n) if n == "C.go"))
            .expect("override roots");
        assert_eq!(root.kind, RootKind::Production);
        assert_eq!(root.confidence, Confidence::Probable);
        // A conforming type's other non-private methods are possible protocol witnesses
        // (Ctx::owner_conforms docs) — rooted, but only at the Possible dynamic tier,
        // strictly below the override's Probable.
        let plain = f
            .roots
            .iter()
            .find(|r| matches!(&r.target, RawRootTarget::Declaration(n) if n == "C.plain"))
            .expect("conformance witness roots at Possible");
        assert_eq!(plain.confidence, Confidence::Possible);
    }

    #[test]
    fn methods_of_a_nonconforming_type_are_not_witness_rooted() {
        let f = facts(
            "class Plain {
                 func work() {}
             }
",
        );
        assert!(!f
            .roots
            .iter()
            .any(|r| matches!(&r.target, RawRootTarget::Declaration(n) if n == "Plain.work")));
    }

    #[test]
    fn main_swift_roots_the_whole_file() {
        let f = extract("Sources/App/main.swift", b"let x = 1\nprint(x)\n");
        assert!(f
            .roots
            .iter()
            .any(|r| matches!(r.target, RawRootTarget::WholeFile)
                && r.confidence == Confidence::Certain));
        let f2 = facts("let x = 1\n");
        assert!(!f2
            .roots
            .iter()
            .any(|r| matches!(r.target, RawRootTarget::WholeFile)));
    }

    #[test]
    fn at_main_attribute_roots_certain() {
        let f = facts("@main\nstruct App {\n    static func main() {}\n}\n");
        assert!(f.roots.iter().any(
            |r| matches!(&r.target, RawRootTarget::Declaration(n) if n == "App.main")
                && r.confidence == Confidence::Certain
        ));
    }

    #[test]
    fn body_references_carry_within_and_qualifiers() {
        let f = facts(
            "class C {\n\
             \x20   func run() { helper(); Other.staticCall(); self.field = 1 }\n\
             \x20   func helper() {}\n\
             \x20   var field: Int = 0\n\
             }\n",
        );
        let helper = f.references.iter().find(|r| r.name == "helper").unwrap();
        assert_eq!(helper.within.as_deref(), Some("C.run"));
        assert_eq!(helper.kind, RefKind::Call);

        let call = f
            .references
            .iter()
            .find(|r| r.name == "staticCall")
            .unwrap();
        assert_eq!(call.scope_context.as_deref(), Some("Other"));

        let field = f
            .references
            .iter()
            .find(|r| r.name == "field" && r.scope_context.as_deref() == Some("self"))
            .unwrap();
        assert_eq!(field.kind, RefKind::Read);
    }

    #[test]
    fn a_top_level_global_s_initializer_is_within_itself_except_in_main_swift() {
        // Swift globals are always lazily-initialized — `makeHelper()` only actually runs
        // when `shared` is first accessed, so the reference belongs to `shared`, not to
        // "module load".
        let ordinary = extract("Sources/MyLib/Widget.swift", b"let shared = makeHelper()\n");
        let r = ordinary
            .references
            .iter()
            .find(|r| r.name == "makeHelper")
            .unwrap();
        assert_eq!(r.within.as_deref(), Some("shared"));

        // `main.swift` is a script: top-level code executes procedurally at load, so this
        // stays the ordinary "module load" `within: None` (unaffected by the fix above).
        let script = extract("Sources/App/main.swift", b"let shared = makeHelper()\n");
        let r = script
            .references
            .iter()
            .find(|r| r.name == "makeHelper")
            .unwrap();
        assert_eq!(r.within, None);
    }

    #[test]
    fn inheritance_and_conformance_emit_extend_refs() {
        let f = facts(
            "class Base {}\n\
             protocol Marker {}\n\
             class C: Base, Marker {}\n",
        );
        assert!(f
            .references
            .iter()
            .any(|r| r.name == "Base" && r.kind == RefKind::Extend));
        assert!(f
            .references
            .iter()
            .any(|r| r.name == "Marker" && r.kind == RefKind::Extend));
    }

    #[test]
    fn extension_members_attribute_to_the_extended_type() {
        let f = facts("class Widget {}\nextension Widget {\n    func extra() {}\n}\n");
        assert_eq!(decl(&f, "extra").member_of.as_deref(), Some("Widget"));
        assert!(!f.declarations.iter().any(|d| d.name == "extension"));
    }

    #[test]
    fn generated_marker_sets_detected_origin() {
        let f = facts("// Generated by sourcery. DO NOT EDIT.\nclass C {}\n");
        assert_eq!(
            f.detected_origin,
            Some(kndo_core::vocab::FileOrigin::Generated)
        );
    }

    #[test]
    fn a_non_comment_line_never_triggers_generated_detection() {
        let f = facts("let x = \"Generated by hand\"\nclass C {}\n");
        assert_eq!(f.detected_origin, None);
    }

    #[test]
    fn suppression_pragma_is_collected() {
        let f = facts("class C {\n// kndo:allow unused\nfunc m() {}\n}\n");
        assert_eq!(f.suppressions.len(), 1);
    }

    #[test]
    fn cyclomatic_complexity_counts_branches() {
        let f = facts(
            "class C {\n\
             \x20   func m(x: Int) {\n\
             \x20       if x > 0 { } else { }\n\
             \x20       for i in 0..<10 { }\n\
             \x20   }\n\
             }\n",
        );
        let fm = f.functions.iter().find(|f| f.symbol == "C.m").unwrap();
        assert_eq!(fm.cyclomatic, 3); // base 1 + if + for
    }

    #[test]
    fn nil_coalescing_and_force_unwrap_are_not_branches() {
        let f = facts(
            "class C {\n\
             \x20   func m(n: Int?) -> Int {\n\
             \x20       let a = n ?? 0\n\
             \x20       return a + n!\n\
             \x20   }\n\
             }\n",
        );
        let fm = f.functions.iter().find(|f| f.symbol == "C.m").unwrap();
        assert_eq!(fm.cyclomatic, 1);
    }

    #[test]
    fn catch_block_counts_not_do_statement() {
        let f = facts(
            "class C {\n\
             \x20   func m() {\n\
             \x20       do { try risky() } catch { handle() }\n\
             \x20   }\n\
             \x20   func risky() throws {}\n\
             \x20   func handle() {}\n\
             }\n",
        );
        let fm = f.functions.iter().find(|f| f.symbol == "C.m").unwrap();
        assert_eq!(fm.cyclomatic, 2); // base 1 + one catch_block
    }
}
