[package]
name = "kndo-adapter-css"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kndo-contract = { path = "../kndo-contract" }
kndo-toolkit = { path = "../kndo-toolkit" }
smol_str = { version = "0.3", features = ["serde"] }
tree-sitter = "0.25"
tree-sitter-css = "0.25"
tree-sitter-scss = "1.0"

[dev-dependencies]
kndo-testkit = { path = "../kndo-testkit" }
