//! Extraction against tree-sitter-python 0.25.0, every node kind verified in
//! its `node-types.json`. Module-level defs, classes and assignments declare;
//! class bodies declare members; defs nested in functions are locals and do
//! not. `__all__`'s string elements land as Read references — the module
//! naming its own published names keeps them and records the intent.

use kndo_contract::evidence::{
    Attachment, DeclarationId, EvidenceSink, MarkerTarget, Reach, RefKind, RelationKind, RootKind,
    RootTarget, SymbolKind,
};
use kndo_contract::vocab::{Confidence, ProjectPath};
use kndo_toolkit as tk;
use smol_str::SmolStr;
use tree_sitter::Node;

const GENERATED_NEEDLES: &[&str] = &[
    "@generated",
    "Code generated",
    "DO NOT EDIT",
    "Generated by",
];

const COMMENTS: tk::CommentMarkers<'static> = tk::CommentMarkers {
    line: &["#"],
    block: &[],
    line_doc: b"#!",
    block_doc: b"",
};

const METRICS: tk::MetricsSpec = tk::MetricsSpec {
    is_branch: |n, source| match n.kind() {
        // A `case _:` arm is the catch-the-rest — the shared rule. `and`/`or`
        // count like `&&`/`||` everywhere else; comprehension `if` clauses are
        // real predicates.
        "case_clause" => {
            let mut c = n.walk();
            !n.children(&mut c)
                .any(|ch| ch.kind() == "case_pattern" && tk::text(ch, source) == "_")
        }
        "if_statement"
        | "elif_clause"
        | "for_statement"
        | "while_statement"
        | "except_clause"
        | "conditional_expression"
        | "if_clause"
        | "boolean_operator" => true,
        _ => false,
    },
    token_class: |n| match n.kind() {
        "identifier" => Some("id"),
        "string_content" => Some("str"),
        "integer" | "float" => Some("num"),
        "comment" => None,
        other => Some(other),
    },
};

pub fn extract(
    path: &ProjectPath,
    source: &[u8],
    tree: &tree_sitter::Tree,
    out: &mut EvidenceSink,
) {
    let p = path.as_str();
    let file_name = p.rsplit('/').next().unwrap_or(p);

    // Nothing imports what the runner collects: these modules join the
    // package in a test run and in no other. WHICH files those are is the
    // spec's `file_roles` to say — the discovery convention is a path fact,
    // and only the membership is this file's.
    let test_file = file_name.starts_with("test_") && file_name.ends_with(".py")
        || file_name.ends_with("_test.py")
        || file_name == "conftest.py";
    if test_file {
        out.attachment(Attachment::TestOnly);
    }

    let root = tree.root_node();
    // `if __name__ == "__main__":` — the language's own entry idiom.
    if has_main_guard(root, source) {
        out.root(
            RootTarget::WholeFile,
            RootKind::Production,
            Confidence::Certain,
        );
    }

    // Imports are legal anywhere — function-scoped lazy imports, `if
    // TYPE_CHECKING:` blocks, `try/except ImportError` optional dependencies —
    // and each is the module naming a dependency, so the walk covers the whole
    // tree, not just the top level.
    tk::walk(root, &mut |n| {
        if matches!(n.kind(), "import_statement" | "import_from_statement") {
            imports(n, source, out);
        }
    });

    // The generated-module banner, REPORTED: what it means is a rule in the
    // spec and a verdict in the engine.
    tk::mark_generated(source, GENERATED_NEEDLES, &["#"], out);
    let mut c = root.walk();
    let items: Vec<Node<'_>> = root.named_children(&mut c).collect();
    for item in items {
        top_level_item(item, source, test_file, out);
    }

    references_and_comments(root, source, out);
}

fn has_main_guard(root: Node<'_>, source: &[u8]) -> bool {
    let mut c = root.walk();
    root.named_children(&mut c).any(|item| {
        item.kind() == "if_statement"
            && item.child_by_field_name("condition").is_some_and(|cond| {
                let t = tk::text(cond, source);
                t.contains("__name__") && t.contains("__main__")
            })
    })
}

fn top_level_item(item: Node<'_>, source: &[u8], test_file: bool, out: &mut EvidenceSink) {
    match item.kind() {
        "function_definition" => {
            function(item, source, None, test_file, None, out);
        }
        "class_definition" => {
            class(item, source, test_file, out);
        }
        "decorated_definition" => {
            if let Some(def) = item.child_by_field_name("definition") {
                match def.kind() {
                    "function_definition" => {
                        function(def, source, None, test_file, Some(item), out);
                    }
                    "class_definition" => {
                        decorated_class(def, item, source, test_file, out);
                    }
                    _ => {}
                }
            }
        }
        "expression_statement" => module_assignment(item, source, out),
        // `type Alias = int` (PEP 695): a declaration like any other, and its
        // name sits under a `type` node rather than a bare identifier.
        "type_alias_statement" => {
            if let Some(lhs) = item.child_by_field_name("left")
                && let Some(ident) = tk::child_of_kind(lhs, "identifier")
            {
                let name = tk::text(ident, source);
                out.declaration(name, SymbolKind::Type, tk::span(item), reach_of(name));
            }
        }
        // A def under `if TYPE_CHECKING:`, in a `try/except ImportError`
        // fallback, or behind a version guard is module surface exactly like
        // one at column zero — the guard decides WHICH definition binds, never
        // whether the name exists. Their bodies' references arrive through the
        // file-wide walk either way.
        "if_statement" | "try_statement" | "with_statement" | "while_statement"
        | "for_statement" => {
            let mut c = item.walk();
            for block in item.named_children(&mut c).filter(|n| n.kind() == "block") {
                let mut bc = block.walk();
                let inner: Vec<Node<'_>> = block.named_children(&mut bc).collect();
                for stmt in inner {
                    top_level_item(stmt, source, test_file, out);
                }
            }
        }
        _ => {}
    }
}

/// Every decorator a definition carries, as a MARKER: the dotted path as the
/// source writes it (`pytest.fixture`, `app.route`, `staticmethod`), which the
/// engine qualifies through the file's own import bindings before any rule
/// compares it. What a decorator MEANS is a rule's to say.
fn markers_of(decorated: Node<'_>, source: &[u8], id: DeclarationId, out: &mut EvidenceSink) {
    let mut c = decorated.walk();
    for d in decorated
        .named_children(&mut c)
        .filter(|n| n.kind() == "decorator")
    {
        let mut dc = d.walk();
        let Some(inner) = d.named_children(&mut dc).next() else {
            continue;
        };
        // `@d` and `@d(...)`: the callee of the call, or the path itself.
        let path_node = match inner.kind() {
            "call" => inner.child_by_field_name("function"),
            _ => Some(inner),
        };
        let Some(path_node) = path_node else { continue };
        let args = match inner.kind() {
            "call" => inner
                .child_by_field_name("arguments")
                .map(|a| {
                    let mut ac = a.walk();
                    a.named_children(&mut ac)
                        .map(|n| SmolStr::new(tk::text(n, source).trim_matches(['\'', '"'])))
                        .collect()
                })
                .unwrap_or_default(),
            _ => Vec::new(),
        };
        out.marker(
            MarkerTarget::Declaration(id),
            tk::text(path_node, source),
            args,
            tk::span(d),
        );
    }
}

/// The bases a class promises the surface of. `class C(Base, metaclass=M)`
/// names ONE base: a keyword argument configures the class, it is not a
/// supertype.
fn relations_of(item: Node<'_>, source: &[u8], id: DeclarationId, out: &mut EvidenceSink) {
    let Some(bases) = item.child_by_field_name("superclasses") else {
        return;
    };
    let mut c = bases.walk();
    for b in bases.named_children(&mut c) {
        if b.kind() == "keyword_argument" {
            continue;
        }
        // `Base` and `pkg.Base` alike: the whole path, which a rule compares
        // after the engine qualifies it.
        out.relation(
            id,
            RelationKind::Implements,
            tk::text(b, source),
            tk::span(b),
        );
    }
}

fn decorated_class(
    def: Node<'_>,
    decorated: Node<'_>,
    source: &[u8],
    test_file: bool,
    out: &mut EvidenceSink,
) {
    let Some(id) = class(def, source, test_file, out) else {
        return;
    };
    markers_of(decorated, source, id, out);
    // Handed to its decorator by the language itself.
    out.root(
        RootTarget::Declaration(id),
        RootKind::Production,
        Confidence::Possible,
    );
}

fn class(
    item: Node<'_>,
    source: &[u8],
    test_file: bool,
    out: &mut EvidenceSink,
) -> Option<kndo_contract::evidence::DeclarationId> {
    let name_node = item.child_by_field_name("name")?;
    let name = tk::text(name_node, source);
    let owner_id = out.declaration(name, SymbolKind::Type, tk::span(item), reach_of(name));
    relations_of(item, source, owner_id, out);
    let Some(body) = item.child_by_field_name("body") else {
        return Some(owner_id);
    };
    let in_test_case = test_file;
    let mut c = body.walk();
    let members: Vec<Node<'_>> = body.named_children(&mut c).collect();
    for m in members {
        match m.kind() {
            "function_definition" => {
                if let Some(id) = function(m, source, Some(owner_id), in_test_case, None, out) {
                    let _ = id;
                }
            }
            "decorated_definition" => {
                if let Some(def) = m.child_by_field_name("definition")
                    && def.kind() == "function_definition"
                {
                    function(def, source, Some(owner_id), in_test_case, Some(m), out);
                }
            }
            "expression_statement" => member_assignment(m, source, owner_id, out),
            _ => {}
        }
    }
    Some(owner_id)
}

/// Constructor-family dunders are never declared — the shared posture.
fn never_declared(name: &str) -> bool {
    matches!(name, "__init__" | "__new__" | "__del__")
}

fn is_dunder(name: &str) -> bool {
    name.starts_with("__") && name.ends_with("__") && name.len() > 4
}

fn function(
    item: Node<'_>,
    source: &[u8],
    owner: Option<kndo_contract::evidence::DeclarationId>,
    test_file: bool,
    decorated: Option<Node<'_>>,
    out: &mut EvidenceSink,
) -> Option<kndo_contract::evidence::DeclarationId> {
    let name_node = item.child_by_field_name("name")?;
    let name = tk::text(name_node, source);
    if never_declared(name) {
        return None;
    }
    let kind = if owner.is_some() {
        SymbolKind::Method
    } else {
        SymbolKind::Function
    };
    let id = out.declaration(name, kind, tk::span(item), reach_of(name));
    if let Some(owner) = owner {
        out.member_of(id, owner);
    }
    out.metrics(id, tk::function_metrics(item, &METRICS, source));
    if let Some(decorated) = decorated {
        markers_of(decorated, source, id, out);
    }

    // The runners dispatch `test_*` by NAME in test files — Certain, the same
    // tier as the discovery convention that rooted the file.
    if test_file && name.starts_with("test") {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Test,
            Confidence::Certain,
        );
    }
    // The runtime protocol invokes dunders (`str(x)` → `__str__`): dispatch
    // the source never names.
    if is_dunder(name) {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Possible,
        );
    }
    // `@d def f` IS `f = d(f)`: the definition is handed to its decorator by
    // the language itself — whatever the decorator registers or wraps, that
    // hand-off is a use beyond static sight.
    if decorated.is_some() {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Possible,
        );
    }
    Some(id)
}

/// Module-level `NAME = …`: UPPER_CASE is the ecosystem's constant convention;
/// `__all__`'s strings are the module naming its published surface.
fn module_assignment(stmt: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    let Some(expr) = stmt.named_child(0) else {
        return;
    };
    if expr.kind() != "assignment" {
        return;
    }
    let Some(left) = expr.child_by_field_name("left") else {
        return;
    };
    if left.kind() != "identifier" {
        return;
    }
    let name = tk::text(left, source);
    if name == "__all__" {
        if let Some(right) = expr.child_by_field_name("right") {
            all_strings_as_refs(right, source, out);
        }
        return;
    }
    let kind = if name.chars().any(|c| c.is_ascii_uppercase())
        && !name.chars().any(|c| c.is_ascii_lowercase())
    {
        SymbolKind::Constant
    } else {
        SymbolKind::Variable
    };
    out.declaration(name, kind, tk::span(stmt), reach_of(name));
}

fn member_assignment(
    stmt: Node<'_>,
    source: &[u8],
    owner: kndo_contract::evidence::DeclarationId,
    out: &mut EvidenceSink,
) {
    let Some(expr) = stmt.named_child(0) else {
        return;
    };
    if expr.kind() != "assignment" {
        return;
    }
    let Some(left) = expr.child_by_field_name("left") else {
        return;
    };
    if left.kind() != "identifier" {
        return;
    }
    let name = tk::text(left, source);
    let id = out.declaration(name, SymbolKind::Variable, tk::span(stmt), reach_of(name));
    out.member_of(id, owner);
}

fn all_strings_as_refs(list: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    tk::walk(list, &mut |n| {
        if n.kind() == "string_content" {
            out.reference(tk::text(n, source), RefKind::Read, tk::span(n));
        }
    });
}

// ---------------------------------------------------------------- visibility

/// Convention is the whole ladder: a leading underscore is module-private —
/// the file's — everything else is importable surface. Dunder names are
/// protocol surface — Exported (their leading underscores are spelling, not
/// hiding).
fn reach_of(name: &str) -> Reach {
    if name.starts_with('_') && !is_dunder(name) {
        // PEP 8's "internal use", and the owner's decision (DECISIONS
        // 2026-09-05): `mod._x()` from a sibling module of the same
        // distribution is legal and common, so an `_x` is never accused for
        // being named across the package — only for being named nowhere in it.
        Reach::Unit { up: 0 }
    } else {
        Reach::Exported
    }
}

// ---------------------------------------------------------------- imports

/// `import a.b`, `import a as x` / `from pkg import a, b as c`,
/// `from . import x`, `from .mod import *`. Absolute dotted paths travel as
/// When an import statement runs: inside a function body, when the function
/// does (`Lazy`); inside the consequence of an `if TYPE_CHECKING:` (or
/// `typing.TYPE_CHECKING`) test, never (`Erased` — the name is False at run
/// time); anywhere else, at module load — a class body, a `try`, a module-level
/// `if` all execute while the module initializes.
fn import_timing(item: Node<'_>, source: &[u8]) -> kndo_contract::evidence::Timing {
    use kndo_contract::evidence::Timing;
    let mut node = item;
    while let Some(parent) = node.parent() {
        match parent.kind() {
            "function_definition" | "lambda" => return Timing::Lazy,
            "if_statement" => {
                let guarded = parent
                    .child_by_field_name("condition")
                    .is_some_and(|c| tk::text(c, source).contains("TYPE_CHECKING"));
                let in_consequence = parent
                    .child_by_field_name("consequence")
                    .is_some_and(|block| block.id() == node.id());
                if guarded && in_consequence {
                    return Timing::Erased;
                }
            }
            _ => {}
        }
        node = parent;
    }
    Timing::Load
}

/// Package targets; relative ones keep their leading dots for the resolver.
/// Every from-import binding also emits a submodule probe (see below).
fn imports(item: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    use kndo_contract::evidence::{ImportBinding, ImportShape, ImportTarget};
    let span = tk::span(item);
    let timing = import_timing(item, source);
    match item.kind() {
        "import_statement" => {
            let mut c = item.walk();
            for child in item.named_children(&mut c) {
                let (module, local) = match child.kind() {
                    "dotted_name" => {
                        let t = tk::text(child, source);
                        // `import a.b` binds `a` — the top package's name.
                        (t, t.split('.').next().unwrap_or(t))
                    }
                    "aliased_import" => {
                        let Some(name) = child.child_by_field_name("name") else {
                            continue;
                        };
                        let alias = child
                            .child_by_field_name("alias")
                            .map(|a| tk::text(a, source));
                        let t = tk::text(name, source);
                        (t, alias.unwrap_or(t))
                    }
                    _ => continue,
                };
                out.import_at(
                    timing,
                    ImportTarget::Package(SmolStr::new(module)),
                    ImportShape::Namespace {
                        local: SmolStr::new(local),
                    },
                    span,
                    Confidence::Certain,
                );
            }
        }
        "import_from_statement" => {
            let Some(module_node) = item.child_by_field_name("module_name") else {
                return;
            };
            let module = tk::text(module_node, source);
            let target = if module.starts_with('.') {
                ImportTarget::Relative(SmolStr::new(module))
            } else {
                ImportTarget::Package(SmolStr::new(module))
            };
            let mut star = false;
            let mut bindings: Vec<ImportBinding> = Vec::new();
            let mut c = item.walk();
            for name in item.children_by_field_name("name", &mut c) {
                match name.kind() {
                    "dotted_name" => {
                        let t = tk::text(name, source);
                        bindings.push(ImportBinding {
                            imported: SmolStr::new(t),
                            local: SmolStr::new(t),
                        });
                    }
                    "aliased_import" => {
                        let Some(n) = name.child_by_field_name("name") else {
                            continue;
                        };
                        let imported = tk::text(n, source);
                        let local = name
                            .child_by_field_name("alias")
                            .map(|a| tk::text(a, source))
                            .unwrap_or(imported);
                        bindings.push(ImportBinding {
                            imported: SmolStr::new(imported),
                            local: SmolStr::new(local),
                        });
                    }
                    _ => {}
                }
            }
            let mut wc = item.walk();
            if item
                .named_children(&mut wc)
                .any(|n| n.kind() == "wildcard_import")
            {
                star = true;
            }
            // In `from X import a`, `a` may be the SUBMODULE `X/a.py` rather
            // than an attribute of X — importlib's own lookup order. Each
            // binding gets a namespace probe of that dotted path. `Possible`,
            // not `Certain`: the probe is the ADAPTER speculating about which
            // of the two readings holds, never the author writing a path — so
            // a probe that resolves keeps its file alive, and one that does
            // not stays below the tier where `unresolved` accuses.
            if !star {
                for b in &bindings {
                    let sep = if module.ends_with('.') { "" } else { "." };
                    let probe = format!("{module}{sep}{}", b.imported);
                    let probe_target = if module.starts_with('.') {
                        ImportTarget::Relative(SmolStr::new(&probe))
                    } else {
                        ImportTarget::Package(SmolStr::new(&probe))
                    };
                    out.import_at(
                        timing,
                        probe_target,
                        ImportShape::Namespace {
                            local: b.local.clone(),
                        },
                        span,
                        Confidence::Possible,
                    );
                }
            }
            let shape = if star {
                ImportShape::Glob
            } else {
                ImportShape::Bindings(bindings)
            };
            out.import_at(timing, target, shape, span, Confidence::Certain);
        }
        _ => {}
    }
}

// ---------------------------------------------------------------- references

fn references_and_comments(root: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    tk::walk_pruned(
        root,
        &["import_statement", "import_from_statement"],
        &mut |n| match n.kind() {
            "comment" => tk::comment_evidence(n, source, &COMMENTS, out),
            "identifier" => {
                if let Some(parent) = n.parent() {
                    if is_binder_seat(n, parent) {
                        return;
                    }
                    out.reference_on(
                        tk::text(n, source),
                        classify(n, parent),
                        receiver_of(n, parent, source),
                        tk::span(n),
                    );
                }
            }
            // A FORWARD annotation is a type by another spelling: `x: "Later"`
            // and `def f() -> "Later"` name `Later` exactly as the unquoted
            // form does, and the quotes exist only because the name is not
            // bound yet at that point in the file.
            "string_content" if in_annotation(n) => {
                for name in tk::text(n, source).split(['[', ']', ',', '|', ' ']) {
                    let name = name.trim();
                    if !name.is_empty() && name.chars().all(|c| c.is_alphanumeric() || c == '_') {
                        out.reference_on(name, RefKind::TypeUse, None, tk::span(n));
                    }
                }
            }
            _ => {}
        },
    );
}

/// Identifier seats that BIND a name rather than use one. Assignment targets
/// stay references deliberately: rebinding an imported name is a use of the
/// binding, and Python's evidence errs keep-alive.
/// The seats that hold a NAME beside something else. `a = DEFAULT` and
/// `a: int = DEFAULT` bind `a` and READ `DEFAULT`, both under one node, so
/// naming the kind wholesale threw the default away — audit finding P3.
const SEATS: tk::Seats = tk::Seats(&[
    ("default_parameter", "name"),
    ("typed_default_parameter", "name"),
    ("keyword_argument", "name"),
    ("function_definition", "name"),
    ("class_definition", "name"),
]);

fn is_binder_seat(n: Node<'_>, parent: Node<'_>) -> bool {
    match parent.kind() {
        // Whole-kind seats: everything a `parameters` list names directly, and
        // a `global`/`nonlocal` declaration, is a binder and holds no value.
        "parameters" | "typed_parameter" | "lambda_parameters" => true,
        "global_statement" | "nonlocal_statement" => true,
        _ => SEATS.binds(n),
    }
}

/// What `obj.attr` was read FROM, where the source spells it as a name — the
/// `object` of the attribute this identifier is the attribute of. A receiver
/// that is itself an expression (`a.b.c`, `f().x`) names nothing the pool can
/// use, and absence is the honest answer there.
fn receiver_of(n: Node<'_>, parent: Node<'_>, source: &[u8]) -> Option<SmolStr> {
    if parent.kind() != "attribute" || parent.child_by_field_name("attribute") != Some(n) {
        return None;
    }
    let object = parent.child_by_field_name("object")?;
    (object.kind() == "identifier").then(|| SmolStr::new(tk::text(object, source)))
}

/// Is this string sitting where a TYPE goes — an annotation, a return type, a
/// type alias?
fn in_annotation(n: Node<'_>) -> bool {
    let mut a = n.parent();
    while let Some(node) = a {
        match node.kind() {
            "type" => return true,
            // A string in an ordinary expression is data, and a walk that
            // climbed past the statement would call every literal a type.
            "block" | "module" | "argument_list" | "call" => return false,
            _ => a = node.parent(),
        }
    }
    false
}

fn classify(n: Node<'_>, parent: Node<'_>) -> RefKind {
    match parent.kind() {
        "call" if parent.child_by_field_name("function") == Some(n) => RefKind::Call,
        "attribute" => {
            if parent.child_by_field_name("attribute") == Some(n) {
                let called = parent.parent().is_some_and(|gp| {
                    gp.kind() == "call" && gp.child_by_field_name("function") == Some(parent)
                });
                if called { RefKind::Call } else { RefKind::Read }
            } else {
                RefKind::Read
            }
        }
        // Class bases: `class X(Base):` — the superclasses argument_list.
        "argument_list" => {
            let extends = parent
                .parent()
                .is_some_and(|gp| gp.kind() == "class_definition");
            if extends {
                RefKind::Extend
            } else {
                RefKind::Read
            }
        }
        "type" => RefKind::TypeUse,
        _ => RefKind::Read,
    }
}
