//! Extraction against tree-sitter-python 0.25.0, every node kind verified in
//! its `node-types.json`. Module-level defs, classes and assignments declare;
//! class bodies declare members; defs nested in functions are locals and do
//! not. `__all__`'s string elements land as Read references — the module
//! naming its own published names keeps them and records the intent.

use kndo_contract::evidence::{EvidenceSink, Reach, RefKind, RootKind, RootTarget, SymbolKind};
use kndo_contract::vocab::{Confidence, ProjectPath};
use kndo_toolkit as tk;
use smol_str::SmolStr;
use tree_sitter::Node;

const GENERATED_NEEDLES: &[&str] = &[
    "@generated",
    "Code generated",
    "DO NOT EDIT",
    "Generated by",
];

const COMMENTS: tk::CommentMarkers<'static> = tk::CommentMarkers {
    line: &["#"],
    block: &[],
    line_doc: b"#!",
    block_doc: b"",
};

const METRICS: tk::MetricsSpec = tk::MetricsSpec {
    is_branch: |n, source| match n.kind() {
        // A `case _:` arm is the catch-the-rest — the shared rule. `and`/`or`
        // count like `&&`/`||` everywhere else; comprehension `if` clauses are
        // real predicates.
        "case_clause" => {
            let mut c = n.walk();
            !n.children(&mut c)
                .any(|ch| ch.kind() == "case_pattern" && tk::text(ch, source) == "_")
        }
        "if_statement"
        | "elif_clause"
        | "for_statement"
        | "while_statement"
        | "except_clause"
        | "conditional_expression"
        | "if_clause"
        | "boolean_operator" => true,
        _ => false,
    },
    token_class: |n| match n.kind() {
        "identifier" => Some("id"),
        "string_content" => Some("str"),
        "integer" | "float" => Some("num"),
        "comment" => None,
        other => Some(other),
    },
};

pub fn extract(
    path: &ProjectPath,
    source: &[u8],
    tree: &tree_sitter::Tree,
    out: &mut EvidenceSink,
) {
    let p = path.as_str();
    let file_name = p.rsplit('/').next().unwrap_or(p);

    // The ecosystem's discovery convention: the runners find `test_*.py` /
    // `*_test.py` by name, and auto-load `conftest.py` — the names themselves
    // are the dispatch, so the roots are Certain.
    let test_file = file_name.starts_with("test_") && file_name.ends_with(".py")
        || file_name.ends_with("_test.py")
        || file_name == "conftest.py";
    if test_file {
        out.root(RootTarget::WholeFile, RootKind::Test, Confidence::Certain);
    } else {
        // Library mode, the shared stance: any non-test module is importable
        // published surface. Probable — convention, not this file's statement.
        out.root(
            RootTarget::WholeFile,
            RootKind::Production,
            Confidence::Probable,
        );
    }

    let root = tree.root_node();
    // `if __name__ == "__main__":` — the language's own entry idiom.
    if has_main_guard(root, source) {
        out.root(
            RootTarget::WholeFile,
            RootKind::Production,
            Confidence::Certain,
        );
    }

    // Imports are legal anywhere — function-scoped lazy imports, `if
    // TYPE_CHECKING:` blocks, `try/except ImportError` optional dependencies —
    // and each is the module naming a dependency, so the walk covers the whole
    // tree, not just the top level.
    tk::walk(root, &mut |n| {
        if matches!(n.kind(), "import_statement" | "import_from_statement") {
            imports(n, source, out);
        }
    });

    // A generated module declares nothing accusable; its imports above and
    // references below still keep the rest of the project alive.
    if !tk::generated_marked(source, GENERATED_NEEDLES, &["#"]) {
        let mut c = root.walk();
        let items: Vec<Node<'_>> = root.named_children(&mut c).collect();
        for item in items {
            top_level_item(item, source, test_file, out);
        }
    }

    references_and_comments(root, source, out);
}

fn has_main_guard(root: Node<'_>, source: &[u8]) -> bool {
    let mut c = root.walk();
    root.named_children(&mut c).any(|item| {
        item.kind() == "if_statement"
            && item.child_by_field_name("condition").is_some_and(|cond| {
                let t = tk::text(cond, source);
                t.contains("__name__") && t.contains("__main__")
            })
    })
}

fn top_level_item(item: Node<'_>, source: &[u8], test_file: bool, out: &mut EvidenceSink) {
    match item.kind() {
        "function_definition" => {
            function(item, source, None, test_file, false, out);
        }
        "class_definition" => {
            class(item, source, test_file, out);
        }
        "decorated_definition" => {
            if let Some(def) = item.child_by_field_name("definition") {
                match def.kind() {
                    "function_definition" => {
                        function(def, source, None, test_file, true, out);
                    }
                    "class_definition" => {
                        decorated_class(def, item, source, test_file, out);
                    }
                    _ => {}
                }
            }
        }
        "expression_statement" => module_assignment(item, source, out),
        // Compound statements (the __main__ guard above all) carry no
        // module-surface declarations of their own; their bodies' references
        // arrive through the file-wide walk.
        _ => {}
    }
}

fn decorated_class(
    def: Node<'_>,
    decorated: Node<'_>,
    source: &[u8],
    test_file: bool,
    out: &mut EvidenceSink,
) {
    let Some(id) = class(def, source, test_file, out) else {
        return;
    };
    let _ = decorated;
    // Handed to its decorator by the language itself.
    out.root(
        RootTarget::Declaration(id),
        RootKind::Production,
        Confidence::Possible,
    );
}

fn class(
    item: Node<'_>,
    source: &[u8],
    test_file: bool,
    out: &mut EvidenceSink,
) -> Option<kndo_contract::evidence::DeclarationId> {
    let name_node = item.child_by_field_name("name")?;
    let name = tk::text(name_node, source);
    let owner_id = out.declaration(name, SymbolKind::Type, tk::span(item), reach_of(name));
    let Some(body) = item.child_by_field_name("body") else {
        return Some(owner_id);
    };
    let in_test_case = test_file;
    let mut c = body.walk();
    let members: Vec<Node<'_>> = body.named_children(&mut c).collect();
    for m in members {
        match m.kind() {
            "function_definition" => {
                if let Some(id) = function(m, source, Some(owner_id), in_test_case, false, out) {
                    let _ = id;
                }
            }
            "decorated_definition" => {
                if let Some(def) = m.child_by_field_name("definition")
                    && def.kind() == "function_definition"
                {
                    function(def, source, Some(owner_id), in_test_case, true, out);
                }
            }
            "expression_statement" => member_assignment(m, source, owner_id, out),
            _ => {}
        }
    }
    Some(owner_id)
}

/// Constructor-family dunders are never declared — the shared posture.
fn never_declared(name: &str) -> bool {
    matches!(name, "__init__" | "__new__" | "__del__")
}

fn is_dunder(name: &str) -> bool {
    name.starts_with("__") && name.ends_with("__") && name.len() > 4
}

fn function(
    item: Node<'_>,
    source: &[u8],
    owner: Option<kndo_contract::evidence::DeclarationId>,
    test_file: bool,
    decorated: bool,
    out: &mut EvidenceSink,
) -> Option<kndo_contract::evidence::DeclarationId> {
    let name_node = item.child_by_field_name("name")?;
    let name = tk::text(name_node, source);
    if never_declared(name) {
        return None;
    }
    let kind = if owner.is_some() {
        SymbolKind::Method
    } else {
        SymbolKind::Function
    };
    let id = out.declaration(name, kind, tk::span(item), reach_of(name));
    if let Some(owner) = owner {
        out.member_of(id, owner);
    }
    out.metrics(id, tk::function_metrics(item, &METRICS, source));

    // The runners dispatch `test_*` by NAME in test files — Certain, the same
    // tier as the discovery convention that rooted the file.
    if test_file && name.starts_with("test") {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Test,
            Confidence::Certain,
        );
    }
    // The runtime protocol invokes dunders (`str(x)` → `__str__`): dispatch
    // the source never names.
    if is_dunder(name) {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Possible,
        );
    }
    // `@d def f` IS `f = d(f)`: the definition is handed to its decorator by
    // the language itself — whatever the decorator registers or wraps, that
    // hand-off is a use beyond static sight.
    if decorated {
        out.root(
            RootTarget::Declaration(id),
            RootKind::Production,
            Confidence::Possible,
        );
    }
    Some(id)
}

/// Module-level `NAME = …`: UPPER_CASE is the ecosystem's constant convention;
/// `__all__`'s strings are the module naming its published surface.
fn module_assignment(stmt: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    let Some(expr) = stmt.named_child(0) else {
        return;
    };
    if expr.kind() != "assignment" {
        return;
    }
    let Some(left) = expr.child_by_field_name("left") else {
        return;
    };
    if left.kind() != "identifier" {
        return;
    }
    let name = tk::text(left, source);
    if name == "__all__" {
        if let Some(right) = expr.child_by_field_name("right") {
            all_strings_as_refs(right, source, out);
        }
        return;
    }
    let kind = if name.chars().any(|c| c.is_ascii_uppercase())
        && !name.chars().any(|c| c.is_ascii_lowercase())
    {
        SymbolKind::Constant
    } else {
        SymbolKind::Variable
    };
    out.declaration(name, kind, tk::span(stmt), reach_of(name));
}

fn member_assignment(
    stmt: Node<'_>,
    source: &[u8],
    owner: kndo_contract::evidence::DeclarationId,
    out: &mut EvidenceSink,
) {
    let Some(expr) = stmt.named_child(0) else {
        return;
    };
    if expr.kind() != "assignment" {
        return;
    }
    let Some(left) = expr.child_by_field_name("left") else {
        return;
    };
    if left.kind() != "identifier" {
        return;
    }
    let name = tk::text(left, source);
    let id = out.declaration(name, SymbolKind::Variable, tk::span(stmt), reach_of(name));
    out.member_of(id, owner);
}

fn all_strings_as_refs(list: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    tk::walk(list, &mut |n| {
        if n.kind() == "string_content" {
            out.reference(tk::text(n, source), RefKind::Read, tk::span(n));
        }
    });
}

// ---------------------------------------------------------------- visibility

/// Convention is the whole ladder: a leading underscore is module-private,
/// everything else is importable surface. Dunder names are protocol surface —
/// Exported (their leading underscores are spelling, not hiding).
fn reach_of(name: &str) -> Reach {
    if name.starts_with('_') && !is_dunder(name) {
        Reach::Private
    } else {
        Reach::Exported
    }
}

// ---------------------------------------------------------------- imports

/// `import a.b`, `import a as x` / `from pkg import a, b as c`,
/// `from . import x`, `from .mod import *`. Absolute dotted paths travel as
/// Package targets; relative ones keep their leading dots for the resolver.
/// Every from-import binding also emits a submodule probe (see below).
fn imports(item: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    use kndo_contract::evidence::{ImportBinding, ImportShape, ImportTarget};
    let span = tk::span(item);
    match item.kind() {
        "import_statement" => {
            let mut c = item.walk();
            for child in item.named_children(&mut c) {
                let (module, local) = match child.kind() {
                    "dotted_name" => {
                        let t = tk::text(child, source);
                        // `import a.b` binds `a` — the top package's name.
                        (t, t.split('.').next().unwrap_or(t))
                    }
                    "aliased_import" => {
                        let Some(name) = child.child_by_field_name("name") else {
                            continue;
                        };
                        let alias = child
                            .child_by_field_name("alias")
                            .map(|a| tk::text(a, source));
                        let t = tk::text(name, source);
                        (t, alias.unwrap_or(t))
                    }
                    _ => continue,
                };
                out.import(
                    ImportTarget::Package(SmolStr::new(module)),
                    ImportShape::Namespace {
                        local: SmolStr::new(local),
                    },
                    span,
                    Confidence::Certain,
                );
            }
        }
        "import_from_statement" => {
            let Some(module_node) = item.child_by_field_name("module_name") else {
                return;
            };
            let module = tk::text(module_node, source);
            let target = if module.starts_with('.') {
                ImportTarget::Relative(SmolStr::new(module))
            } else {
                ImportTarget::Package(SmolStr::new(module))
            };
            let mut star = false;
            let mut bindings: Vec<ImportBinding> = Vec::new();
            let mut c = item.walk();
            for name in item.children_by_field_name("name", &mut c) {
                match name.kind() {
                    "dotted_name" => {
                        let t = tk::text(name, source);
                        bindings.push(ImportBinding {
                            imported: SmolStr::new(t),
                            local: SmolStr::new(t),
                        });
                    }
                    "aliased_import" => {
                        let Some(n) = name.child_by_field_name("name") else {
                            continue;
                        };
                        let imported = tk::text(n, source);
                        let local = name
                            .child_by_field_name("alias")
                            .map(|a| tk::text(a, source))
                            .unwrap_or(imported);
                        bindings.push(ImportBinding {
                            imported: SmolStr::new(imported),
                            local: SmolStr::new(local),
                        });
                    }
                    _ => {}
                }
            }
            let mut wc = item.walk();
            if item
                .named_children(&mut wc)
                .any(|n| n.kind() == "wildcard_import")
            {
                star = true;
            }
            // In `from X import a`, `a` may be the SUBMODULE `X/a.py` rather
            // than an attribute of X — importlib's own lookup order. Each
            // binding gets a namespace probe of that dotted path. `Possible`,
            // not `Certain`: the probe is the ADAPTER speculating about which
            // of the two readings holds, never the author writing a path — so
            // a probe that resolves keeps its file alive, and one that does
            // not stays below the tier where `unresolved` accuses.
            if !star {
                for b in &bindings {
                    let sep = if module.ends_with('.') { "" } else { "." };
                    let probe = format!("{module}{sep}{}", b.imported);
                    let probe_target = if module.starts_with('.') {
                        ImportTarget::Relative(SmolStr::new(&probe))
                    } else {
                        ImportTarget::Package(SmolStr::new(&probe))
                    };
                    out.import(
                        probe_target,
                        ImportShape::Namespace {
                            local: b.local.clone(),
                        },
                        span,
                        Confidence::Possible,
                    );
                }
            }
            let shape = if star {
                ImportShape::Glob
            } else {
                ImportShape::Bindings(bindings)
            };
            out.import(target, shape, span, Confidence::Certain);
        }
        _ => {}
    }
}

// ---------------------------------------------------------------- references

fn references_and_comments(root: Node<'_>, source: &[u8], out: &mut EvidenceSink) {
    tk::walk_pruned(
        root,
        &["import_statement", "import_from_statement"],
        &mut |n| match n.kind() {
            "comment" => tk::comment_evidence(n, source, &COMMENTS, out),
            "identifier" => {
                if let Some(parent) = n.parent() {
                    if is_binder_seat(n, parent) {
                        return;
                    }
                    out.reference(tk::text(n, source), classify(n, parent), tk::span(n));
                }
            }
            _ => {}
        },
    );
}

/// Identifier seats that BIND a name rather than use one. Assignment targets
/// stay references deliberately: rebinding an imported name is a use of the
/// binding, and Python's evidence errs keep-alive.
fn is_binder_seat(n: Node<'_>, parent: Node<'_>) -> bool {
    match parent.kind() {
        "function_definition" | "class_definition" => parent.child_by_field_name("name") == Some(n),
        "parameters" | "typed_parameter" | "default_parameter" | "lambda_parameters" => true,
        "keyword_argument" => parent.child_by_field_name("name") == Some(n),
        "global_statement" | "nonlocal_statement" => true,
        _ => false,
    }
}

fn classify(n: Node<'_>, parent: Node<'_>) -> RefKind {
    match parent.kind() {
        "call" if parent.child_by_field_name("function") == Some(n) => RefKind::Call,
        "attribute" => {
            if parent.child_by_field_name("attribute") == Some(n) {
                let called = parent.parent().is_some_and(|gp| {
                    gp.kind() == "call" && gp.child_by_field_name("function") == Some(parent)
                });
                if called { RefKind::Call } else { RefKind::Read }
            } else {
                RefKind::Read
            }
        }
        // Class bases: `class X(Base):` — the superclasses argument_list.
        "argument_list" => {
            let extends = parent
                .parent()
                .is_some_and(|gp| gp.kind() == "class_definition");
            if extends {
                RefKind::Extend
            } else {
                RefKind::Read
            }
        }
        "type" => RefKind::TypeUse,
        _ => RefKind::Read,
    }
}
