[package]
name = "kndo"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kndo-adapter-go = { path = "../kndo-adapter-go" }
kndo-adapter-rust = { path = "../kndo-adapter-rust" }
kndo-adapter-ts = { path = "../kndo-adapter-ts" }
kndo-contract = { path = "../kndo-contract" }
kndo-core = { path = "../kndo-core" }

[dev-dependencies]
kndo-testkit = { path = "../kndo-testkit" }
