[package]
name = "kndo"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kndo-adapter-ts = { path = "../kndo-adapter-ts" }
kndo-contract = { path = "../kndo-contract" }
kndo-core = { path = "../kndo-core" }
