/**
 * @generated by graphql-codegen — nothing imports this file, and in an authored file that
 * would be an unused:file finding; the content-derived Generated origin exempts it.
 */
export type Query = { id: number };
