//! tree-sitter setup for Go (mirrors `kndo-adapter-toolkit::parsing`'s shape — that module's own
//! `Parser`/`Language` plumbing is TS-specific, so this adapter owns its own copy rather than
//! forcing a false shared abstraction over two unrelated grammars).

use tree_sitter::{Language, Parser, Tree};

pub fn go_language() -> Language {
    tree_sitter_go::LANGUAGE.into()
}

pub fn parse(source: &[u8]) -> Option<Tree> {
    let mut parser = Parser::new();
    parser.set_language(&go_language()).ok()?;
    parser.parse(source, None)
}

#[cfg(test)]
mod introspect {
    //! Not adapter tests — a ground-truth probe of tree-sitter-go's real node/field names;
    //! extraction.rs is written against verified facts instead of assumptions (same
    //! methodology `kndo-adapter-toolkit::parsing`'s introspect module uses for TS).
    //! `cargo test -p kndo-adapter-go introspect -- --nocapture --ignored`.

    use super::*;

    fn dump(node: tree_sitter::Node, src: &[u8], depth: usize) {
        let field = node
            .parent()
            .and_then(|p| {
                (0..p.child_count()).find_map(|i| {
                    if p.child(i)? == node {
                        p.field_name_for_child(i as u32)
                    } else {
                        None
                    }
                })
            })
            .unwrap_or("-");
        let text = if node.child_count() == 0 {
            std::str::from_utf8(&src[node.byte_range()]).unwrap_or("?")
        } else {
            ""
        };
        println!(
            "{}{} field={} '{}'",
            "  ".repeat(depth),
            node.kind(),
            field,
            text
        );
        for i in 0..node.child_count() {
            if let Some(c) = node.child(i) {
                dump(c, src, depth + 1);
            }
        }
    }

    #[test]
    #[ignore]
    fn dump_multiname_shapes() {
        let src = br#"
package foo

const A, B = 1, 2
var X, Y int

func Variadic(prefix string, rest ...int) {}
"#;
        let tree = parse(src).unwrap();
        dump(tree.root_node(), src, 0);
    }

    #[test]
    #[ignore]
    fn dump_declaration_shapes() {
        let src = br#"
package foo

func Plain(x int) int { return x }

func (t T) ValueMethod() {}
func (t *T) PointerMethod() {}

type Struct struct {
	Field int
	unexportedField string
}

type Iface interface {
	Method() int
}

type Alias = string
type Defined int

const (
	A = 1
	B = 2
)

var globalVar = 1

func init() {}
"#;
        let tree = parse(src).unwrap();
        dump(tree.root_node(), src, 0);
    }

    #[test]
    #[ignore]
    fn dump_import_shapes() {
        let src = br#"
package foo

import "fmt"
import f "fmt"
import _ "embed"
import . "strings"
import (
	"encoding/json"
	other "github.com/foo/bar"
)
"#;
        let tree = parse(src).unwrap();
        dump(tree.root_node(), src, 0);
    }

    #[test]
    #[ignore]
    fn dump_reference_shapes() {
        let src = br#"
package foo

import "fmt"

func Use() {
	fmt.Println("x")
	helper()
	x := Struct{Field: 1}
	_ = x
}

type Embedder struct {
	Base
	Iface
}

func (e *Embedder) Method() int {
	return e.Base.Value
}
"#;
        let tree = parse(src).unwrap();
        dump(tree.root_node(), src, 0);
    }

    #[test]
    #[ignore]
    fn dump_comment_shapes() {
        let src = br#"
package foo

// kndo:allow unused reason text
func a() {}

/* kndo:allow-file version-skew */

func b() {} // kndo:allow unused trailing comment
"#;
        let tree = parse(src).unwrap();
        dump(tree.root_node(), src, 0);
    }

    #[test]
    #[ignore]
    fn dump_generated_header_shapes() {
        let src = br#"// Code generated by protoc-gen-go. DO NOT EDIT.
package foo
"#;
        let tree = parse(src).unwrap();
        dump(tree.root_node(), src, 0);
    }
}
