// Copyright 2026 The Example Authors. Licence line 1.
// Copyright 2026 The Example Authors. Licence line 2.
// Copyright 2026 The Example Authors. Licence line 3.
// Copyright 2026 The Example Authors. Licence line 4.
// Copyright 2026 The Example Authors. Licence line 5.
// Copyright 2026 The Example Authors. Licence line 6.
// Copyright 2026 The Example Authors. Licence line 7.
// Copyright 2026 The Example Authors. Licence line 8.
// Copyright 2026 The Example Authors. Licence line 9.
// Copyright 2026 The Example Authors. Licence line 10.
// Copyright 2026 The Example Authors. Licence line 11.
// Copyright 2026 The Example Authors. Licence line 12.
// Copyright 2026 The Example Authors. Licence line 13.
// Copyright 2026 The Example Authors. Licence line 14.
// Copyright 2026 The Example Authors. Licence line 15.
// Copyright 2026 The Example Authors. Licence line 16.
// Copyright 2026 The Example Authors. Licence line 17.
// Copyright 2026 The Example Authors. Licence line 18.
// Copyright 2026 The Example Authors. Licence line 19.
// Copyright 2026 The Example Authors. Licence line 20.
// Copyright 2026 The Example Authors. Licence line 21.
// Copyright 2026 The Example Authors. Licence line 22.
// Copyright 2026 The Example Authors. Licence line 23.
// Copyright 2026 The Example Authors. Licence line 24.
//
// Code generated by protoc-gen-go. DO NOT EDIT.

package pkg

// Nothing here is accusable: the generator owns this file.
func unusedGenerated() {}
