//! Rust extraction (docs/adapters/rust.md §2), written against tree-sitter-rust node shapes
//! verified by `parsing::introspect` — never assumed.
//!
//! Shapes that matter here and nowhere else:
//! - `mod foo;` is an **import** (`self::foo`, side-effect-only) — the file-linking edge the
//!   whole adapter is built on (spec §0). `#[path = "…"]` overrides the location (`file:`
//!   specifier form).
//! - A body path rooted at `crate`/`self`/`super` emits a synthetic import (specifier =
//!   path-minus-tail, binding = tail): a fully-qualified use-site IS an import, and emitting
//!   it as one gets certain file edges + binding resolution for free. Bare-rooted body paths
//!   (`helpers::run()`) emit a qualified reference instead (`scope_context`), resolved
//!   through import aliases core-side — a bare root naming an inline module degrades to the
//!   member fallback, silence over accusation (spec §6).
//! - Inline `mod x { … }` flattens: file ≈ module is the standing approximation.
//! - Attributes travel as pending state to the next item: `#[test]`/`#[bench]` → test root,
//!   `#[no_mangle]`/`#[export_name]` → FFI production root, `#[derive(X)]` → `TypeUse`
//!   references (a derive-only dependency stays honestly used), `#[path]` → mod location.

use kndo_adapter_toolkit::metrics::{function_shape, MetricsSyntax};
use kndo_core::adapter::{
    Diagnostic, DiagnosticLevel, FileFacts, FunctionMetrics, ImportBinding, ImportKind, RawImport,
    RawReference, RawRoot, RawRootTarget, RawSuppression, Span,
};
use kndo_core::vocab::{Confidence, RefKind, RootKind, SymbolKind};
use smol_str::SmolStr;
use tree_sitter::Node;

const GENERATED_MARKERS: kndo_adapter_toolkit::classify::ContentMarkers =
    kndo_adapter_toolkit::classify::ContentMarkers {
        generated_markers: &[
            kndo_adapter_toolkit::classify::LineMarker::Contains("@generated"),
            kndo_adapter_toolkit::classify::LineMarker::Contains("Automatically generated"),
            kndo_adapter_toolkit::classify::LineMarker::Contains("Code generated by"),
        ],
        scan_window_lines: 64,
    };

/// docs/adapters/rust.md §2: `?` (try) is an early-return branch; `match_arm` counts each arm.
pub const METRICS_SYNTAX: MetricsSyntax = MetricsSyntax {
    branch_kinds: &[
        "if_expression",
        "match_arm",
        "while_expression",
        "for_expression",
        "try_expression",
        "&&",
        "||",
    ],
    identifier_kinds: &[
        "identifier",
        "field_identifier",
        "type_identifier",
        "shorthand_field_identifier",
    ],
    literal_kinds: &[
        "string_literal",
        "raw_string_literal",
        "char_literal",
        "integer_literal",
        "float_literal",
    ],
    skip_kinds: &["line_comment", "block_comment"],
};

const MIN_CLONE_TOKENS: usize = 50;

/// Primitive types with associated items (`u64::from`, `str::parse`) — path roots that are
/// language, not modules or crates: never worth an import emission.
const PRIMITIVES: &[&str] = &[
    "bool", "char", "str", "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64",
    "i128", "isize", "f32", "f64",
];

/// Attributes seen since the last item — applied to the next non-attribute sibling.
#[derive(Default)]
struct PendingAttrs {
    test: bool,
    bench: bool,
    ffi_export: bool,
    cfg_test: bool,
    mod_path: Option<String>,
    derives: Vec<(SmolStr, Span)>,
}

pub(crate) fn extract(_path: &str, content: &[u8]) -> FileFacts {
    let mut out = FileFacts::default();
    if GENERATED_MARKERS.detect_generated(content) {
        out.detected_origin = Some(kndo_core::vocab::FileOrigin::Generated);
    }

    let Some(tree) = crate::parsing::parse(content) else {
        out.diagnostics.push(Diagnostic {
            level: DiagnosticLevel::Warn,
            path: None,
            message: "failed to initialize the Rust parser".to_string(),
            span: None,
        });
        return out;
    };
    let root = tree.root_node();
    if root.has_error() {
        out.diagnostics.push(Diagnostic {
            level: DiagnosticLevel::Warn,
            path: None,
            message: "parse errors — extraction is partial for this file".to_string(),
            span: None,
        });
    }

    let local_qualifiers = collect_local_qualifiers(root, content);
    walk_items(
        root,
        content,
        &Ctx {
            owner: None,
            in_cfg_test: false,
            local_qualifiers: &local_qualifiers,
        },
        &mut out,
    );
    collect_suppressions(root, content, &mut out);
    out
}

/// Names that qualify paths locally — `use` tails/aliases and `mod` names, anywhere in the
/// file. A bare body path rooted at one of these (`fs::read` after `use std::fs`) is already
/// covered by that import's alias; emitting a root import for it would fabricate a phantom
/// dependency.
fn collect_local_qualifiers(root: Node, src: &[u8]) -> std::collections::HashSet<String> {
    let mut out = std::collections::HashSet::new();
    fn walk(node: Node, src: &[u8], out: &mut std::collections::HashSet<String>) {
        match node.kind() {
            "mod_item" => {
                if let Some(name) = node.child_by_field_name("name") {
                    out.insert(text(name, src).to_string());
                }
            }
            "use_as_clause" => {
                if let Some(alias) = node.child_by_field_name("alias") {
                    out.insert(text(alias, src).to_string());
                }
            }
            "scoped_identifier" | "identifier"
                if node.parent().is_some_and(|p| p.kind() == "use_declaration") =>
            {
                let t = text(node, src);
                out.insert(t.rsplit("::").next().unwrap_or(t).to_string());
            }
            "scoped_use_list" => {
                // `use a::{x, y};` — the simple list items are local names too.
                if let Some(list) = node.child_by_field_name("list") {
                    let mut c = list.walk();
                    for el in list.children(&mut c) {
                        if el.kind() == "identifier" {
                            out.insert(text(el, src).to_string());
                        }
                    }
                }
                if let Some(path) = node.child_by_field_name("path") {
                    let t = text(path, src);
                    out.insert(t.rsplit("::").next().unwrap_or(t).to_string());
                }
            }
            _ => {}
        }
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            walk(child, src, out);
        }
    }
    walk(root, src, &mut out);
    out
}

/// Item-walk context: the member owner, whether we're under a `#[cfg(test)]` module (its
/// declarations become test roots — inline test infrastructure, spec §1), and the file's
/// local qualifier names.
struct Ctx<'a> {
    owner: Option<&'a str>,
    in_cfg_test: bool,
    local_qualifiers: &'a std::collections::HashSet<String>,
}

fn span(node: Node) -> Span {
    Span {
        start: (
            node.start_position().row as u32 + 1,
            node.start_position().column as u32 + 1,
        ),
        end: (
            node.end_position().row as u32 + 1,
            node.end_position().column as u32 + 1,
        ),
    }
}

fn text<'a>(node: Node, src: &'a [u8]) -> &'a str {
    std::str::from_utf8(&src[node.byte_range()]).unwrap_or("")
}

/// `(level, exported)` per the ladder [File "private", Package "pub(crate)", Public "pub"];
/// `pub(super)`/`pub(in …)` widen to the crate rung (spec §2, conservative direction).
fn visibility(node: Node) -> (u8, bool) {
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if child.kind() == "visibility_modifier" {
            let has_restriction = child.child_count() > 1; // `pub` + `(` `crate`/`super`/… `)`
            return if has_restriction {
                (1, true)
            } else {
                (2, true)
            };
        }
    }
    (0, false)
}

/// Item-list walker (source_file, inline-mod bodies — flattened, spec §2). Attributes are
/// pending state applied to the next item.
fn walk_items(list: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let mut pending = PendingAttrs::default();
    let mut cursor = list.walk();
    for item in list.children(&mut cursor) {
        match item.kind() {
            "attribute_item" => collect_attr(item, src, &mut pending, out),
            "line_comment" | "block_comment" => {} // attributes survive doc comments
            _ => {
                handle_item(item, src, ctx, std::mem::take(&mut pending), out);
            }
        }
    }
}

fn collect_attr(item: Node, src: &[u8], pending: &mut PendingAttrs, out: &mut FileFacts) {
    let Some(attr) = item.named_child(0) else {
        return;
    };
    let Some(name_node) = attr.child(0) else {
        return;
    };
    let name = text(name_node, src);
    match name {
        "test" => pending.test = true,
        "bench" => pending.bench = true,
        "no_mangle" | "export_name" | "unsafe" => {
            // `#[unsafe(no_mangle)]` (Rust 2024) nests the real attribute in a token tree —
            // scan the attribute text for the export markers rather than modeling the nesting.
            let full = text(attr, src);
            if full.contains("no_mangle") || full.contains("export_name") {
                pending.ffi_export = true;
            } else if name == "test" {
                pending.test = true;
            }
        }
        "path" => {
            // #[path = "other/loc.rs"] — the string_literal's content child.
            if let Some(value) = attr.child_by_field_name("value") {
                let lit = text(value, src).trim_matches('"');
                pending.mod_path = Some(lit.to_string());
            }
        }
        "derive" => {
            if let Some(args) = attr.child_by_field_name("arguments") {
                let mut c = args.walk();
                for tok in args.children(&mut c) {
                    if tok.kind() == "identifier" {
                        pending
                            .derives
                            .push((SmolStr::new(text(tok, src)), span(tok)));
                    }
                }
                // Path-shaped derives (`serde::Serialize`) also need their crate's import.
                scan_attr_idents(args, src, out);
            }
        }
        "cfg" | "cfg_attr" => {
            // Both branches kept, always (spec §2) — but `#[cfg(test)]` marks the next item
            // (typically `mod tests`) as inline test infrastructure.
            if text(attr, src).contains("test") {
                pending.cfg_test = true;
            }
        }
        _ => {
            // Unknown attributes (`#[rkyv(with = SmolStrAsString)]`, `#[serde(…)]`) may name
            // real items in their arguments — scan for identifier tokens as TypeUse refs so
            // attr-only consumers stay alive (the M5 dogfood's SmolStrAsString case).
            scan_unknown_attr(attr, name, src, out);
        }
    }
}

/// Attribute names whose arguments are lint paths, doc text, or config keys — never item
/// paths (`#[allow(clippy::x)]` must not invent a `clippy` dependency).
const NON_ITEM_ATTRS: [&str; 8] = [
    "allow", "warn", "deny", "forbid", "expect", "doc", "cfg", "cfg_attr",
];

fn scan_unknown_attr(attr: Node, name: &str, src: &[u8], out: &mut FileFacts) {
    if NON_ITEM_ATTRS.contains(&name) {
        return;
    }
    if let Some(args) = attr.child_by_field_name("arguments") {
        scan_attr_idents(args, src, out);
    }
}

/// Attribute arguments are token soup, not structured paths — reconstruct `a::b::C`
/// sequences and treat them like body paths: rooted → synthetic import + binding; bare
/// multi-segment → the crate probe; lone uppercase identifiers → TypeUse references. This is
/// what keeps `#[rkyv(with = crate::rkyv_support::SmolStrAsString)]`'s target and
/// `#[derive(serde::Serialize)]`'s crate honestly used.
fn scan_attr_idents(node: Node, src: &[u8], out: &mut FileFacts) {
    // Linear token pass over this level: group ident (:: ident)* runs.
    let mut cursor = node.walk();
    let children: Vec<Node> = node.children(&mut cursor).collect();
    let mut i = 0;
    while i < children.len() {
        let tok = children[i];
        if matches!(tok.kind(), "identifier" | "crate" | "self" | "super") {
            let mut segments = vec![text(tok, src)];
            let mut j = i + 1;
            while j + 1 < children.len()
                && children[j].kind() == "::"
                && matches!(
                    children[j + 1].kind(),
                    "identifier" | "crate" | "self" | "super"
                )
            {
                segments.push(text(children[j + 1], src));
                j += 2;
            }
            emit_attr_path(&segments, span(tok), out);
            i = j;
        } else {
            scan_attr_idents(tok, src, out);
            i += 1;
        }
    }
}

fn emit_attr_path(segments: &[&str], at: Span, out: &mut FileFacts) {
    let [rest @ .., last] = segments else { return };
    if rest.is_empty() {
        if last.chars().next().is_some_and(char::is_uppercase) {
            out.references.push(RawReference {
                name: SmolStr::new(*last),
                scope_context: None,
                span: at,
                within: None,
                kind: RefKind::TypeUse,
            });
        }
        return;
    }
    let root = rest[0];
    let rooted = matches!(root, "crate" | "self" | "super");
    if rooted || !PRIMITIVES.contains(&root) {
        out.imports.push(RawImport {
            specifier: SmolStr::new(rest.join("::")),
            kind: if rooted {
                ImportKind::Relative
            } else {
                ImportKind::Package
            },
            span: at,
            side_effect_only: false,
            type_only: true,
            confidence: Confidence::Probable,
            bindings: vec![ImportBinding {
                local: SmolStr::new(*last),
                imported: Some(SmolStr::new(*last)),
            }],
            reexported: false,
            opaque_namespace_use: false,
            local_alias: None,
        });
        out.references.push(RawReference {
            name: SmolStr::new(*last),
            scope_context: None,
            span: at,
            within: None,
            kind: RefKind::TypeUse,
        });
    }
}

fn handle_item(item: Node, src: &[u8], ctx: &Ctx<'_>, pending: PendingAttrs, out: &mut FileFacts) {
    let owner = ctx.owner;
    let decls_before = out.declarations.len();
    // Derive attributes reference their derive macros regardless of what item follows.
    for (name, sp) in &pending.derives {
        out.references.push(RawReference {
            name: name.clone(),
            scope_context: None,
            span: *sp,
            within: None,
            kind: RefKind::TypeUse,
        });
    }

    match item.kind() {
        "function_item" => handle_function(item, src, ctx, owner, &pending, None, out),
        "struct_item" | "union_item" => {
            handle_type_decl(item, src, ctx, SymbolKind::Struct, out);
        }
        "enum_item" => handle_enum(item, src, ctx, out),
        "trait_item" => handle_trait(item, src, ctx, out),
        "impl_item" => handle_impl(item, src, ctx, out),
        "const_item" => handle_simple_decl(item, src, ctx, SymbolKind::Const, owner, out),
        "static_item" => handle_simple_decl(item, src, ctx, SymbolKind::Static, owner, out),
        "type_item" => handle_type_decl(item, src, ctx, SymbolKind::TypeAlias, out),
        "macro_definition" => {
            if let Some(name) = item.child_by_field_name("name") {
                push_declaration(
                    out,
                    text(name, src),
                    SymbolKind::Other(SmolStr::new("macro")),
                    item,
                    None,
                    None,
                    // macro_rules! has no pub; a #[macro_export] would make it public, but
                    // the common case is crate-visible — Package level, exported.
                    (1, true),
                );
            }
        }
        "mod_item" => handle_mod(item, src, ctx, &pending, out),
        "use_declaration" => handle_use(item, src, out),
        // (declaration-count bookkeeping below skips imports — they add no declarations)
        "extern_crate_declaration" => {
            if let Some(name) = item.child_by_field_name("name") {
                out.imports.push(RawImport {
                    specifier: SmolStr::new(text(name, src)),
                    kind: ImportKind::Package,
                    span: span(item),
                    side_effect_only: true,
                    type_only: false,
                    confidence: Confidence::Certain,
                    bindings: Vec::new(),
                    reexported: false,
                    opaque_namespace_use: false,
                    local_alias: None,
                });
            }
        }
        _ => {}
    }

    // Inside a `#[cfg(test)]` module, every declaration is test infrastructure — a test
    // root, so reachability colors it (and everything only it reaches) test-side, and the
    // core's root-exemption keeps it out of `test-only`/`untested` findings (spec §1: the
    // inline analogue of Go's `_test.go` role).
    if ctx.in_cfg_test {
        for d in decls_before..out.declarations.len() {
            let decl = &out.declarations[d];
            let qualified = match &decl.member_of {
                Some(owner) => format!("{owner}.{}", decl.name),
                None => decl.name.to_string(),
            };
            out.roots.push(RawRoot {
                kind: RootKind::Test,
                target: RawRootTarget::Declaration(SmolStr::new(qualified)),
                confidence: Confidence::Certain,
            });
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn push_declaration(
    out: &mut FileFacts,
    name: &str,
    kind: SymbolKind,
    item: Node,
    signature_span: Option<Span>,
    member_of: Option<&str>,
    (level, exported): (u8, bool),
) {
    out.declarations.push(kndo_core::adapter::Declaration {
        name: SmolStr::new(name),
        kind,
        span: span(item),
        exported,
        visibility: kndo_core::adapter::VisibilityLevel(level),
        member_of: member_of.map(SmolStr::new),
        signature_span,
    });
}

fn handle_function(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    owner: Option<&str>,
    pending: &PendingAttrs,
    vis_override: Option<(u8, bool)>,
    out: &mut FileFacts,
) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = text(name_node, src);
    // Trait items carry no `pub` of their own — they inherit the trait's visibility (the
    // same Rust rule as enum variants), so `handle_trait` passes the override; every other
    // caller reads the item's own modifier.
    let vis = vis_override.unwrap_or_else(|| visibility(item));
    let body = item.child_by_field_name("body");
    // Signature = the item minus its body: what a caller sees (RFC 0012 §5).
    let signature_span = body.map(|b| Span {
        start: span(item).start,
        end: span(b).start,
    });
    let (kind, qualified) = match owner {
        Some(owner) => (SymbolKind::Method, format!("{owner}.{name}")),
        None => (SymbolKind::Function, name.to_string()),
    };
    push_declaration(out, name, kind, item, signature_span, owner, vis);

    if pending.test || pending.bench {
        out.roots.push(RawRoot {
            kind: RootKind::Test,
            target: RawRootTarget::Declaration(SmolStr::new(&qualified)),
            confidence: Confidence::Certain,
        });
    }
    // Top-level `fn main`: the bin entry point (same unconditional stance as Go's main/init —
    // Probable because only bin targets actually run it; a library's stray `main` over-lives,
    // the safe direction).
    if owner.is_none() && name == "main" {
        out.roots.push(RawRoot {
            kind: RootKind::Production,
            target: RawRootTarget::Declaration(SmolStr::new(&qualified)),
            confidence: Confidence::Probable,
        });
    }
    // FFI export: an attribute says so, or a `pub extern "C" fn` shape does (spec §2).
    let is_extern_fn = {
        let mut c = item.walk();
        let found = item
            .children(&mut c)
            .any(|n| n.kind() == "function_modifiers" && text(n, src).contains("extern"));
        found
    };
    if pending.ffi_export || (vis.1 && is_extern_fn) {
        out.roots.push(RawRoot {
            kind: RootKind::Production,
            target: RawRootTarget::Declaration(SmolStr::new(&qualified)),
            confidence: Confidence::Probable,
        });
    }

    // Signature types are used-when-the-fn-is-used: within = the fn (RFC 0012 §4).
    let mut c = item.walk();
    for child in item.children(&mut c) {
        if child.by_ref_is_body(body) {
            continue;
        }
        walk_type_refs(child, src, Some(&qualified), ctx.local_qualifiers, out);
    }
    if let Some(body) = body {
        walk_body(body, src, Some(&qualified), ctx.local_qualifiers, out);
        let shape = function_shape(body, &METRICS_SYNTAX, MIN_CLONE_TOKENS);
        out.functions.push(FunctionMetrics {
            symbol: SmolStr::new(&qualified),
            cyclomatic: shape.cyclomatic,
            loc: shape.loc,
            token_count: shape.token_count as u32,
            fingerprints: shape.fingerprints,
        });
    }
}

/// Tiny helper: is `self` the body node? (Option comparison without cloning nodes.)
trait IsBody {
    fn by_ref_is_body(&self, body: Option<Node>) -> bool;
}
impl IsBody for Node<'_> {
    fn by_ref_is_body(&self, body: Option<Node>) -> bool {
        body.is_some_and(|b| b.id() == self.id())
    }
}

fn handle_type_decl(item: Node, src: &[u8], ctx: &Ctx<'_>, kind: SymbolKind, out: &mut FileFacts) {
    let Some(name) = item.child_by_field_name("name") else {
        return;
    };
    let vis = visibility(item);
    push_declaration(out, text(name, src), kind, item, None, None, vis);
    // Field/alias types are load-bearing for the type: TypeUse refs, within = the type.
    let type_name = text(name, src).to_string();
    let mut c = item.walk();
    for child in item.children(&mut c) {
        walk_type_refs(child, src, Some(&type_name), ctx.local_qualifiers, out);
    }
}

fn handle_enum(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = text(name_node, src);
    let vis = visibility(item);
    push_declaration(out, name, SymbolKind::Enum, item, None, None, vis);
    if let Some(body) = item.child_by_field_name("body") {
        let mut c = body.walk();
        for variant in body.children(&mut c) {
            if variant.kind() == "enum_variant" {
                if let Some(vname) = variant.child_by_field_name("name") {
                    push_declaration(
                        out,
                        text(vname, src),
                        SymbolKind::EnumMember,
                        variant,
                        None,
                        Some(name),
                        vis, // variants share the enum's visibility (Rust rule)
                    );
                }
                walk_type_refs(variant, src, Some(name), ctx.local_qualifiers, out);
            }
        }
    }
}

fn handle_trait(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = text(name_node, src);
    let vis = visibility(item);
    push_declaration(out, name, SymbolKind::Interface, item, None, None, vis);
    if let Some(body) = item.child_by_field_name("body") {
        let mut members = body.walk();
        let mut pending = PendingAttrs::default();
        for member in body.children(&mut members) {
            match member.kind() {
                "attribute_item" => collect_attr(member, src, &mut pending, out),
                "function_item" | "function_signature_item" => {
                    let p = std::mem::take(&mut pending);
                    handle_function(member, src, ctx, Some(name), &p, Some(vis), out);
                }
                "associated_type" | "const_item" => {
                    let _ = std::mem::take(&mut pending);
                    if let Some(mname) = member.child_by_field_name("name") {
                        push_declaration(
                            out,
                            text(mname, src),
                            if member.kind() == "const_item" {
                                SymbolKind::Const
                            } else {
                                SymbolKind::TypeAlias
                            },
                            member,
                            None,
                            Some(name),
                            vis,
                        );
                    }
                }
                _ => {}
            }
        }
    }
}

fn handle_impl(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    // The self type's bare name: `impl S`, `impl S<T>`, `impl a::S` all own members under `S`.
    let Some(type_node) = item.child_by_field_name("type") else {
        return;
    };
    let self_type = last_type_identifier(type_node, src);
    let Some(self_type) = self_type else { return };

    // `impl Trait for T` — the Implement reference that keeps dispatch-aware liveness honest
    // (RFC 0012 §3): using the trait keeps its implementations alive.
    if let Some(trait_node) = item.child_by_field_name("trait") {
        if let Some(trait_name) = last_type_identifier(trait_node, src) {
            out.references.push(RawReference {
                name: SmolStr::new(trait_name),
                scope_context: None,
                span: span(trait_node),
                within: Some(SmolStr::new(&self_type)),
                kind: RefKind::Implement,
            });
        }
    }

    let is_trait_impl = item.child_by_field_name("trait").is_some();
    if let Some(body) = item.child_by_field_name("body") {
        let mut members = body.walk();
        let mut pending = PendingAttrs::default();
        for member in body.children(&mut members) {
            match member.kind() {
                "attribute_item" => collect_attr(member, src, &mut pending, out),
                "function_item" => {
                    let p = std::mem::take(&mut pending);
                    handle_function(member, src, ctx, Some(&self_type), &p, None, out);
                    // Trait-impl methods are called through the trait's dispatch (dyn, generic
                    // bounds, operator/format machinery — `Display::fmt` is never `x.fmt()` in
                    // source), so the name-based member fallback cannot see their call sites:
                    // root them at Probable (the RFC 0012 §3 dispatch rule, made concrete —
                    // over-liveness in the safe direction, spec §6).
                    if is_trait_impl {
                        if let Some(mname) = member.child_by_field_name("name") {
                            out.roots.push(RawRoot {
                                kind: RootKind::Production,
                                target: RawRootTarget::Declaration(SmolStr::new(format!(
                                    "{self_type}.{}",
                                    text(mname, src)
                                ))),
                                confidence: Confidence::Probable,
                            });
                        }
                    }
                }
                "const_item" | "type_item" | "associated_type" => {
                    let _ = std::mem::take(&mut pending);
                    if let Some(mname) = member.child_by_field_name("name") {
                        push_declaration(
                            out,
                            text(mname, src),
                            if member.kind() == "const_item" {
                                SymbolKind::Const
                            } else {
                                SymbolKind::TypeAlias
                            },
                            member,
                            None,
                            Some(&self_type),
                            visibility(member),
                        );
                    }
                }
                _ => {}
            }
        }
    }
}

/// The rightmost `type_identifier` under a type node — `S`, `S<T>`, `a::b::S` all yield `S`.
fn last_type_identifier(node: Node, src: &[u8]) -> Option<String> {
    if node.kind() == "type_identifier" {
        return Some(text(node, src).to_string());
    }
    let mut found = None;
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if let Some(name) = last_type_identifier(child, src) {
            found = Some(name);
        }
    }
    found
}

fn handle_simple_decl(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    kind: SymbolKind,
    owner: Option<&str>,
    out: &mut FileFacts,
) {
    let Some(name) = item.child_by_field_name("name") else {
        return;
    };
    let vis = visibility(item);
    push_declaration(out, text(name, src), kind, item, None, owner, vis);
    // Initializer expressions run at load: within = None (RFC 0012 §4's load-time rule).
    if let Some(value) = item.child_by_field_name("value") {
        walk_body(value, src, None, ctx.local_qualifiers, out);
    }
    if let Some(ty) = item.child_by_field_name("type") {
        walk_type_refs(ty, src, None, ctx.local_qualifiers, out);
    }
}

fn handle_mod(item: Node, src: &[u8], ctx: &Ctx<'_>, pending: &PendingAttrs, out: &mut FileFacts) {
    let Some(name) = item.child_by_field_name("name") else {
        return;
    };
    match item.child_by_field_name("body") {
        // Inline module: flatten (spec §2 — file ≈ module, stated once, leaned on everywhere).
        Some(body) => walk_items(
            body,
            src,
            &Ctx {
                owner: None,
                in_cfg_test: ctx.in_cfg_test || pending.cfg_test,
                local_qualifiers: ctx.local_qualifiers,
            },
            out,
        ),
        // `mod foo;` — THE file-linking import (spec §0). #[path] overrides the location.
        // `pub mod foo;` additionally re-exports the child's whole surface (reexported, no
        // bindings — the shape phase 2.7's library-surface fixpoint expands): a published
        // crate's API lives behind exactly these chains.
        None => {
            let specifier = match &pending.mod_path {
                Some(p) => format!("file:{p}"),
                None => format!("self::{}", text(name, src)),
            };
            let (_, is_pub) = visibility(item);
            out.imports.push(RawImport {
                specifier: SmolStr::new(specifier),
                kind: ImportKind::Relative,
                span: span(item),
                side_effect_only: true,
                type_only: false,
                confidence: Confidence::Certain,
                bindings: Vec::new(),
                reexported: is_pub,
                // The child module's items are addressable through `name::…` qualifiers.
                opaque_namespace_use: false,
                local_alias: Some(SmolStr::new(text(name, src))),
            });
        }
    }
}

// ---------------------------------------------------------------- use declarations

fn handle_use(item: Node, src: &[u8], out: &mut FileFacts) {
    let reexported = {
        let mut c = item.walk();
        let found = item
            .children(&mut c)
            .any(|n| n.kind() == "visibility_modifier");
        found
    };
    let Some(argument) = item.child_by_field_name("argument") else {
        return;
    };
    collect_use(argument, src, "", reexported, span(item), out);
}

fn import_kind(path: &str) -> ImportKind {
    match path.split("::").next() {
        Some("crate" | "self" | "super") => ImportKind::Relative,
        _ => ImportKind::Package,
    }
}

/// The entry-liveness companion (spec §3): a deep path into a crate traverses its module
/// tree from the entry, so `use crate_name::deep::Item` also imports `crate_name` alone.
fn push_entry_import(specifier: &str, at: Span, out: &mut FileFacts) {
    if import_kind(specifier) != ImportKind::Package {
        return;
    }
    let Some((root, _)) = specifier.split_once("::") else {
        return;
    };
    out.imports.push(RawImport {
        specifier: SmolStr::new(root),
        kind: ImportKind::Package,
        span: at,
        side_effect_only: true,
        type_only: false,
        confidence: Confidence::Certain,
        bindings: Vec::new(),
        reexported: false,
        opaque_namespace_use: false,
        local_alias: None,
    });
}

fn make_import(specifier: &str, kind_span: (ImportKind, Span), reexported: bool) -> RawImport {
    RawImport {
        specifier: SmolStr::new(specifier),
        kind: kind_span.0,
        span: kind_span.1,
        side_effect_only: false,
        type_only: false,
        confidence: Confidence::Certain,
        bindings: Vec::new(),
        reexported,
        opaque_namespace_use: false,
        local_alias: None,
    }
}

/// Recursive over the use-argument shapes verified in `introspect`: `scoped_identifier`,
/// `scoped_use_list`, `use_wildcard`, `use_as_clause`, bare `identifier`/`crate`/`self`.
/// `prefix` is the path accumulated from enclosing lists (`use a::{b::{c}}` reaches `c` with
/// prefix `a::b`).
fn collect_use(
    node: Node,
    src: &[u8],
    prefix: &str,
    reexported: bool,
    at: Span,
    out: &mut FileFacts,
) {
    let join = |tail: &str| {
        if prefix.is_empty() {
            tail.to_string()
        } else {
            format!("{prefix}::{tail}")
        }
    };
    match node.kind() {
        // Full path, no list: `use a::b::X;` — specifier keeps the full path; the resolver's
        // two-step tail rule (spec §3) decides module-vs-item, extraction never guesses.
        "scoped_identifier" | "identifier" | "crate" | "self" | "super" => {
            let full = join(text(node, src));
            let last = full.rsplit("::").next().unwrap_or(&full).to_string();
            let mut imp = make_import(&full, (import_kind(&full), at), reexported);
            if !matches!(last.as_str(), "crate" | "self" | "super") {
                imp.bindings.push(ImportBinding {
                    local: SmolStr::new(&last),
                    imported: Some(SmolStr::new(&last)),
                });
                // A module import (`use crate::a::helpers;`) makes `helpers::…` qualifiers
                // resolvable — the alias is the tail either way; harmless when the tail was
                // an item (nothing qualifies through an item name).
                imp.local_alias = Some(SmolStr::new(&last));
            }
            out.imports.push(imp);
            push_entry_import(&full, at, out);
        }
        "use_as_clause" => {
            let (Some(path), Some(alias)) = (
                node.child_by_field_name("path"),
                node.child_by_field_name("alias"),
            ) else {
                return;
            };
            let full = join(text(path, src));
            let imported = full.rsplit("::").next().unwrap_or(&full).to_string();
            let local = text(alias, src);
            let mut imp = make_import(&full, (import_kind(&full), at), reexported);
            imp.bindings.push(ImportBinding {
                local: SmolStr::new(local),
                imported: Some(SmolStr::new(&imported)),
            });
            imp.local_alias = Some(SmolStr::new(local));
            out.imports.push(imp);
            push_entry_import(&full, at, out);
        }
        "use_wildcard" => {
            // `use p::*` — the truth of a glob is a Wildcard over the target's exports.
            let inner = node
                .named_child(0)
                .map(|n| text(n, src).to_string())
                .unwrap_or_default();
            let full = join(&inner);
            let mut imp = make_import(&full, (import_kind(&full), at), reexported);
            imp.opaque_namespace_use = true;
            out.imports.push(imp);
        }
        "scoped_use_list" => {
            let (Some(path), Some(list)) = (
                node.child_by_field_name("path"),
                node.child_by_field_name("list"),
            ) else {
                return;
            };
            let new_prefix = join(text(path, src));
            collect_use(list, src, &new_prefix, reexported, at, out);
        }
        "use_list" => {
            // Simple identifiers and as-clauses group into ONE import for the prefix; nested
            // shapes recurse into their own imports.
            let mut grouped = make_import(prefix, (import_kind(prefix), at), reexported);
            let mut cursor = node.walk();
            for element in node.children(&mut cursor) {
                match element.kind() {
                    "identifier" => grouped.bindings.push(ImportBinding {
                        local: SmolStr::new(text(element, src)),
                        imported: Some(SmolStr::new(text(element, src))),
                    }),
                    "self" => {
                        // `use a::{self, b}` — the module itself becomes qualifiable.
                        let tail = prefix.rsplit("::").next().unwrap_or(prefix);
                        grouped.local_alias = Some(SmolStr::new(tail));
                    }
                    "use_as_clause" => {
                        let (Some(p), Some(alias)) = (
                            element.child_by_field_name("path"),
                            element.child_by_field_name("alias"),
                        ) else {
                            continue;
                        };
                        if p.kind() == "identifier" || p.kind() == "self" {
                            grouped.bindings.push(ImportBinding {
                                local: SmolStr::new(text(alias, src)),
                                imported: Some(SmolStr::new(text(p, src))),
                            });
                        } else {
                            collect_use(element, src, prefix, reexported, at, out);
                        }
                    }
                    "scoped_identifier" | "scoped_use_list" | "use_wildcard" | "use_list" => {
                        collect_use(element, src, prefix, reexported, at, out);
                    }
                    _ => {}
                }
            }
            if !grouped.bindings.is_empty() || grouped.local_alias.is_some() {
                out.imports.push(grouped);
                push_entry_import(prefix, at, out);
            }
        }
        _ => {}
    }
}

// ---------------------------------------------------------------- references

/// Type positions: every `type_identifier` is a `TypeUse`; scoped type paths rooted at
/// `crate`/`self`/`super` also emit the synthetic import (module doc).
fn walk_type_refs(
    node: Node,
    src: &[u8],
    within: Option<&str>,
    quals: &std::collections::HashSet<String>,
    out: &mut FileFacts,
) {
    match node.kind() {
        "line_comment" | "block_comment" => {}
        "type_identifier" => out.references.push(RawReference {
            name: SmolStr::new(text(node, src)),
            scope_context: None,
            span: span(node),
            within: within.map(SmolStr::new),
            kind: RefKind::TypeUse,
        }),
        "scoped_type_identifier" => {
            handle_scoped_path(node, src, within, RefKind::TypeUse, quals, out);
        }
        // Field/variant attributes (`#[rkyv(with = crate::…::SmolStrAsString)]`, `#[serde(…)]`)
        // are token soup below the type body — same scan as item-level unknown attributes, so
        // attr-only consumers referenced from *fields* stay alive too.
        "attribute_item" => {
            if let Some(attr) = node.named_child(0) {
                if let Some(name_node) = attr.child(0) {
                    scan_unknown_attr(attr, text(name_node, src), src, out);
                }
            }
        }
        _ => {
            let mut cursor = node.walk();
            for child in node.children(&mut cursor) {
                walk_type_refs(child, src, within, quals, out);
            }
        }
    }
}

/// Expression bodies: calls, qualified paths, member accesses, macro invocations, plain
/// identifier reads (locals shadowing a top-level name over-approximate ALIVE — the safe
/// direction, spec §2).
fn walk_body(
    node: Node,
    src: &[u8],
    within: Option<&str>,
    quals: &std::collections::HashSet<String>,
    out: &mut FileFacts,
) {
    match node.kind() {
        "line_comment" | "block_comment" => return,
        "identifier" => {
            if is_reference_position(node) {
                out.references.push(RawReference {
                    name: SmolStr::new(text(node, src)),
                    scope_context: None,
                    span: span(node),
                    within: within.map(SmolStr::new),
                    kind: if node.parent().is_some_and(|p| p.kind() == "call_expression") {
                        RefKind::Call
                    } else {
                        RefKind::Read
                    },
                });
            }
            return;
        }
        "scoped_identifier" => {
            let kind = if node.parent().is_some_and(|p| p.kind() == "call_expression") {
                RefKind::Call
            } else {
                RefKind::Read
            };
            handle_scoped_path(node, src, within, kind, quals, out);
            return;
        }
        "field_expression" => {
            // `x.method()` / `x.field` — a member access by construction: the duck-typed
            // fallback territory (RFC 0012 §3), mirrored from the Go adapter.
            let (Some(value), Some(field)) = (
                node.child_by_field_name("value"),
                node.child_by_field_name("field"),
            ) else {
                return;
            };
            let kind = if node.parent().is_some_and(|p| p.kind() == "call_expression") {
                RefKind::Call
            } else {
                RefKind::Read
            };
            if matches!(value.kind(), "identifier" | "self") {
                out.references.push(RawReference {
                    name: SmolStr::new(text(field, src)),
                    scope_context: Some(SmolStr::new(text(value, src))),
                    span: span(node),
                    within: within.map(SmolStr::new),
                    kind,
                });
                if value.kind() == "identifier" {
                    out.references.push(RawReference {
                        name: SmolStr::new(text(value, src)),
                        scope_context: None,
                        span: span(value),
                        within: within.map(SmolStr::new),
                        kind: RefKind::Read,
                    });
                }
                return;
            }
            // Complex receiver: member ref with no usable qualifier, then walk the receiver.
            out.references.push(RawReference {
                name: SmolStr::new(text(field, src)),
                scope_context: Some(SmolStr::new("<expr>")),
                span: span(node),
                within: within.map(SmolStr::new),
                kind,
            });
            walk_body(value, src, within, quals, out);
            return;
        }
        "macro_invocation" => {
            handle_macro(node, src, within, quals, out);
            return;
        }
        "type_identifier" => {
            out.references.push(RawReference {
                name: SmolStr::new(text(node, src)),
                scope_context: None,
                span: span(node),
                within: within.map(SmolStr::new),
                kind: RefKind::TypeUse,
            });
            return;
        }
        "scoped_type_identifier" => {
            handle_scoped_path(node, src, within, RefKind::TypeUse, quals, out);
            return;
        }
        _ => {}
    }
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        walk_body(child, src, within, quals, out);
    }
}

/// Whether a bare identifier here reads a value (vs. binding a new name in a pattern).
fn is_reference_position(node: Node) -> bool {
    let Some(parent) = node.parent() else {
        return false;
    };
    match parent.kind() {
        // Patterns bind, they don't read.
        "parameter"
        | "closure_parameters"
        | "tuple_pattern"
        | "tuple_struct_pattern"
        | "struct_pattern"
        | "field_pattern"
        | "match_pattern"
        | "or_pattern"
        | "captured_pattern"
        | "reference_pattern"
        | "mut_pattern" => false,
        "let_declaration" => {
            // `let NAME = value` — pattern side binds, value side reads.
            parent
                .child_by_field_name("pattern")
                .is_none_or(|p| p.id() != node.id())
        }
        // Struct-literal initializers READ: a `field_initializer`'s identifier child is
        // always the value (the field name is a `field_identifier`, a different node kind),
        // and a shorthand `Foo { x }` reads local `x` — both fall through to `true`.
        _ => true,
    }
}

/// A `::`-path outside a `use`: rooted paths become a synthetic import + a plain binding
/// reference (a fully-qualified use-site IS an import); bare-rooted paths emit a qualified
/// reference resolved through import aliases (module doc).
fn handle_scoped_path(
    node: Node,
    src: &[u8],
    within: Option<&str>,
    kind: RefKind,
    quals: &std::collections::HashSet<String>,
    out: &mut FileFacts,
) {
    let full = text(node, src);
    // Strip generic turbofish (`Vec::<u8>::new` → segments without the `::<u8>` part).
    let segments: Vec<&str> = full
        .split("::")
        .filter(|s| !s.is_empty() && !s.starts_with('<'))
        .collect();
    emit_path(&segments, span(node), within, kind, quals, out);
}

/// The path emissions shared by AST-shaped paths (`handle_scoped_path`) and token-soup paths
/// reconstructed inside macro invocations (`scan_token_tree`) — one rule, two surfaces.
fn emit_path(
    segments: &[&str],
    at: Span,
    within: Option<&str>,
    kind: RefKind,
    quals: &std::collections::HashSet<String>,
    out: &mut FileFacts,
) {
    let [rest @ .., last] = segments else {
        return;
    };
    if rest.is_empty() {
        return;
    }
    let root = rest[0];
    if matches!(root, "crate" | "self" | "super") {
        out.imports.push(RawImport {
            specifier: SmolStr::new(rest.join("::")),
            kind: ImportKind::Relative,
            span: at,
            side_effect_only: false,
            type_only: kind == RefKind::TypeUse,
            confidence: Confidence::Certain,
            bindings: vec![ImportBinding {
                local: SmolStr::new(*last),
                imported: Some(SmolStr::new(*last)),
            }],
            reexported: false,
            opaque_namespace_use: false,
            local_alias: None,
        });
        out.references.push(RawReference {
            name: SmolStr::new(*last),
            scope_context: None,
            span: at,
            within: within.map(SmolStr::new),
            kind,
        });
    } else {
        // Bare root: `helpers::run`, `serde_json::to_string`, `Vec::new`. The immediate
        // qualifier goes to scope_context — the core matches it against import aliases
        // (RFC 0012 §9); an uppercase qualifier is a type's associated item, which lands in
        // the member fallback via the qualified table.
        let qualifier = rest.last().copied().unwrap_or(root);
        out.references.push(RawReference {
            name: SmolStr::new(*last),
            scope_context: Some(SmolStr::new(qualifier)),
            span: at,
            within: within.map(SmolStr::new),
            kind,
        });
        // Multi-segment bare paths (`cycles::mod::item`, `serde_json::x::y`): the parent
        // path imports with the tail as its binding (so the item resolves in the deep
        // target), and the bare root imports alone as well — a deep path traverses the
        // crate's module tree from its entry, so the entry stays alive (spec §3). For an
        // external crate the extra root import just duplicates the dependency edge.
        let import_worthy = !PRIMITIVES.contains(&root) && !quals.contains(root);
        if import_worthy && rest.len() == 1 && !root.chars().next().is_some_and(char::is_uppercase)
        {
            // Single-qualifier bare path (`helpers::run()`, `rand_chacha::x()`): the root
            // alone imports at Probable — a local module resolves to its file (resolution's
            // local-retry precedence), an unknown crate becomes the Dependency edge the
            // `undeclared` analysis needs. The qualified reference stays for binding.
            out.imports.push(RawImport {
                specifier: SmolStr::new(root),
                kind: ImportKind::Package,
                span: at,
                side_effect_only: true,
                type_only: false,
                confidence: Confidence::Probable,
                bindings: Vec::new(),
                reexported: false,
                opaque_namespace_use: false,
                local_alias: None,
            });
        }
        if import_worthy && rest.len() > 1 && !root.chars().next().is_some_and(char::is_uppercase) {
            out.imports.push(RawImport {
                specifier: SmolStr::new(rest.join("::")),
                kind: ImportKind::Package,
                span: at,
                side_effect_only: false,
                type_only: kind == RefKind::TypeUse,
                confidence: Confidence::Probable,
                bindings: vec![ImportBinding {
                    local: SmolStr::new(*last),
                    imported: Some(SmolStr::new(*last)),
                }],
                reexported: false,
                opaque_namespace_use: false,
                local_alias: None,
            });
            out.imports.push(RawImport {
                specifier: SmolStr::new(root),
                kind: ImportKind::Package,
                span: at,
                side_effect_only: true,
                type_only: false,
                confidence: Confidence::Probable,
                bindings: Vec::new(),
                reexported: false,
                opaque_namespace_use: false,
                local_alias: None,
            });
            // The binding resolves the plain name — no qualifier needed for this one.
            out.references.push(RawReference {
                name: SmolStr::new(*last),
                scope_context: None,
                span: at,
                within: within.map(SmolStr::new),
                kind,
            });
        }
    }
}

fn handle_macro(
    node: Node,
    src: &[u8],
    within: Option<&str>,
    quals: &std::collections::HashSet<String>,
    out: &mut FileFacts,
) {
    let Some(macro_name) = node.child_by_field_name("macro") else {
        return;
    };
    let name = text(macro_name, src);
    out.references.push(RawReference {
        name: SmolStr::new(name.rsplit("::").next().unwrap_or(name)),
        scope_context: None,
        span: span(macro_name),
        within: within.map(SmolStr::new),
        kind: RefKind::Call,
    });

    // include!/include_str!/include_bytes! with a literal: a probable file edge (spec §2).
    if matches!(name, "include" | "include_str" | "include_bytes") {
        if let Some(lit) = first_string_literal(node, src) {
            out.imports.push(RawImport {
                specifier: SmolStr::new(format!("file:{lit}")),
                kind: ImportKind::Relative,
                span: span(node),
                side_effect_only: true,
                type_only: false,
                confidence: Confidence::Probable,
                bindings: Vec::new(),
                reexported: false,
                opaque_namespace_use: false,
                local_alias: None,
            });
            return;
        }
    }

    // Identifier tokens inside the macro's token tree: plain reads (`format!("{}", user)`
    // keeps `user`'s referents alive). No wildcard per macro — spec §2's bounded stance.
    scan_token_tree(node, src, within, quals, out);
}

fn first_string_literal<'a>(node: Node, src: &'a [u8]) -> Option<&'a str> {
    if node.kind() == "string_content" {
        return Some(text(node, src));
    }
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if let Some(found) = first_string_literal(child, src) {
            return Some(found);
        }
    }
    None
}

fn scan_token_tree(
    node: Node,
    src: &[u8],
    within: Option<&str>,
    quals: &std::collections::HashSet<String>,
    out: &mut FileFacts,
) {
    // Rust 2021 inline format captures: `format!("v{VERSION}")` reads `VERSION` from inside
    // the string literal — invisible to the identifier-token scan below, so string content
    // in macro token trees is scanned for `{ident}` / `{ident:spec}` shapes (`{{` escapes
    // skipped, non-identifier args like `{}` / `{0}` ignored).
    if node.kind() == "string_content" {
        for name in format_captures(text(node, src)) {
            out.references.push(RawReference {
                name: SmolStr::new(name),
                scope_context: None,
                span: span(node),
                within: within.map(SmolStr::new),
                kind: RefKind::Read,
            });
        }
        return;
    }
    // Linear token pass, one level: expression code inside a macro is token soup, so
    // `render::render_query(x)` arrives as loose `identifier :: identifier` tokens — the
    // same reconstruction as attribute arguments, routed through the body-path rule
    // (`emit_path`) so qualified names bind exactly as they would outside the macro. Lone
    // identifiers stay plain reads. A following sibling `token_tree` is an argument list —
    // that path is a call.
    let mut cursor = node.walk();
    let children: Vec<Node> = node.children(&mut cursor).collect();
    let mut i = 0;
    while i < children.len() {
        let tok = children[i];
        if matches!(tok.kind(), "identifier" | "crate" | "self" | "super") {
            let mut segments = vec![text(tok, src)];
            let mut j = i + 1;
            while j + 1 < children.len()
                && children[j].kind() == "::"
                && matches!(
                    children[j + 1].kind(),
                    "identifier" | "crate" | "self" | "super"
                )
            {
                segments.push(text(children[j + 1], src));
                j += 2;
            }
            let kind = if children.get(j).is_some_and(|n| n.kind() == "token_tree") {
                RefKind::Call
            } else {
                RefKind::Read
            };
            if segments.len() == 1 {
                if tok.kind() == "identifier" {
                    out.references.push(RawReference {
                        name: SmolStr::new(segments[0]),
                        scope_context: None,
                        span: span(tok),
                        within: within.map(SmolStr::new),
                        kind: RefKind::Read,
                    });
                }
            } else {
                emit_path(&segments, span(tok), within, kind, quals, out);
            }
            i = j;
        } else {
            scan_token_tree(tok, src, within, quals, out);
            i += 1;
        }
    }
}

/// The identifier-shaped inline captures of a format string body: `{name}` and `{name:spec}`,
/// with `{{`/`}}` escapes honored. Positional (`{}`, `{0}`) and anything not a lone identifier
/// contribute nothing.
fn format_captures(s: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] != b'{' {
            i += 1;
            continue;
        }
        if bytes.get(i + 1) == Some(&b'{') {
            i += 2; // escaped brace
            continue;
        }
        let start = i + 1;
        let mut j = start;
        while j < bytes.len() && bytes[j] != b'}' && bytes[j] != b':' {
            j += 1;
        }
        let candidate = &s[start..j];
        let is_ident = !candidate.is_empty()
            && candidate
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
            && candidate
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_');
        if is_ident {
            out.push(candidate);
        }
        i = j + 1;
    }
    out
}

// ---------------------------------------------------------------- suppressions

fn collect_suppressions(node: Node, src: &[u8], out: &mut FileFacts) {
    if matches!(node.kind(), "line_comment" | "block_comment") {
        if let Some(pragma) =
            kndo_adapter_toolkit::suppression::parse_suppression_pragma(text(node, src))
        {
            out.suppressions.push(RawSuppression {
                span: span(node),
                category: pragma.category,
                subject: pragma.subject,
                reason: pragma.reason,
                scope: pragma.scope,
            });
        }
    }
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        collect_suppressions(child, src, out);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn facts(src: &str) -> FileFacts {
        extract("src/lib.rs", src.as_bytes())
    }

    fn decl_names(f: &FileFacts) -> Vec<(&str, bool)> {
        f.declarations
            .iter()
            .map(|d| (d.name.as_str(), d.exported))
            .collect()
    }

    #[test]
    fn field_attribute_paths_import_and_reference_their_targets() {
        // The M5 dogfood's SmolStrAsString case: a struct alive only through a field-level
        // `#[rkyv(with = …)]` attribute must stay alive — extraction emits the synthetic
        // import (path minus tail) plus a TypeUse reference for the tail.
        let f = facts(
            "pub struct Node {\n\
             \x20   #[rkyv(with = rkyv::with::Map<crate::support::Helper>)]\n\
             \x20   pub name: String,\n\
             }\n",
        );
        assert!(f
            .imports
            .iter()
            .any(|i| i.specifier == "crate::support"
                && i.bindings.iter().any(|b| b.local == "Helper")));
        assert!(f.imports.iter().any(|i| i.specifier == "rkyv::with"));
        assert!(f
            .references
            .iter()
            .any(|r| r.name == "Helper" && r.kind == RefKind::TypeUse));
    }

    #[test]
    fn lint_attributes_never_invent_dependencies() {
        // `#[allow(clippy::x)]` arguments are lint paths, not item paths — no import, no ref,
        // at item level and field level alike.
        let f = facts(
            "#[allow(clippy::type_complexity)]\n\
             pub struct S {\n\
             \x20   #[allow(clippy::struct_field_names)]\n\
             \x20   pub f: u32,\n\
             }\n",
        );
        assert!(
            !f.imports.iter().any(|i| i.specifier.contains("clippy")),
            "lint namespaces must not become dependency probes"
        );
    }

    #[test]
    fn declarations_cover_the_item_zoo() {
        let f = facts(
            "pub fn free() {}\n\
             pub(crate) struct S;\n\
             enum E { A, B }\n\
             pub trait Tr { fn m(&self); }\n\
             impl S { pub fn method(&self) {} }\n\
             const C: u32 = 1;\n\
             static ST: u32 = 2;\n\
             type Alias = u32;\n\
             macro_rules! mac { () => {} }\n",
        );
        let names: Vec<&str> = f.declarations.iter().map(|d| d.name.as_str()).collect();
        assert_eq!(
            names,
            ["free", "S", "E", "A", "B", "Tr", "m", "method", "C", "ST", "Alias", "mac"]
        );
        let method = f.declarations.iter().find(|d| d.name == "method").unwrap();
        assert_eq!(method.member_of.as_deref(), Some("S"));
        assert_eq!(method.kind, SymbolKind::Method);
        let variant = f.declarations.iter().find(|d| d.name == "A").unwrap();
        assert_eq!(variant.member_of.as_deref(), Some("E"));
        let trait_method = f.declarations.iter().find(|d| d.name == "m").unwrap();
        assert_eq!(trait_method.member_of.as_deref(), Some("Tr"));
    }

    #[test]
    fn visibility_maps_to_the_three_rung_ladder() {
        let f = facts(
            "fn private_fn() {}\n\
             pub(crate) fn crate_fn() {}\n\
             pub(super) fn super_fn() {}\n\
             pub fn public_fn() {}\n",
        );
        let by_name = |n: &str| f.declarations.iter().find(|d| d.name == n).unwrap();
        assert_eq!(by_name("private_fn").visibility.0, 0);
        assert!(!by_name("private_fn").exported);
        assert_eq!(by_name("crate_fn").visibility.0, 1);
        assert_eq!(by_name("super_fn").visibility.0, 1); // widened, spec §2
        assert_eq!(by_name("public_fn").visibility.0, 2);
        assert!(by_name("public_fn").exported);
    }

    #[test]
    fn struct_literal_initializers_read_their_values() {
        // `field: CONST` and shorthand `Foo { x }` both READ — the field name is a
        // `field_identifier` node and never collides with the value identifier (the M5
        // dogfood's BASELINE_FILE_VERSION case).
        let f = facts(
            "const V: u32 = 1;\n\
             fn build() -> S { let x = 2; S { version: V, x } }\n",
        );
        let reads: Vec<&str> = f
            .references
            .iter()
            .filter(|r| r.kind == RefKind::Read)
            .map(|r| r.name.as_str())
            .collect();
        assert!(reads.contains(&"V"));
        assert!(reads.contains(&"x"));
    }

    #[test]
    fn macro_token_trees_reconstruct_scoped_paths() {
        // `print!("{}", render::render_query(x))` — expression code inside a macro is token
        // soup; the `a::b` run must bind like a body path (qualified reference through the
        // `use`-established qualifier), not decay into disconnected identifier reads.
        let f = facts(
            "use crate::render;\n\
             fn go(x: u32) { print!(\"{}\", render::render_query(x)); }\n",
        );
        assert!(f.references.iter().any(|r| r.name == "render_query"
            && r.scope_context.as_deref() == Some("render")
            && r.kind == RefKind::Call));
        // Rooted paths inside macros import like body paths.
        let f2 = facts("fn go() { assert!(crate::checks::verify()); }\n");
        assert!(f2
            .imports
            .iter()
            .any(|i| i.specifier == "crate::checks"
                && i.bindings.iter().any(|b| b.local == "verify")));
    }

    #[test]
    fn inline_format_captures_read_from_string_literals() {
        // Rust 2021 `format!("v{VERSION} {n:>8}")` reads VERSION and n from inside the
        // string; `{{esc}}`, `{}` and `{0}` contribute nothing.
        let f = facts(
            "const VERSION: u32 = 1;\n\
             fn p(n: u32) { println!(\"v{VERSION} {n:>8} {{esc}} {} {0}\", n); }\n",
        );
        let reads: Vec<&str> = f
            .references
            .iter()
            .filter(|r| r.kind == RefKind::Read)
            .map(|r| r.name.as_str())
            .collect();
        assert!(reads.contains(&"VERSION"));
        assert!(reads.contains(&"n"));
        assert!(!reads.contains(&"esc"));
    }

    #[test]
    fn trait_methods_inherit_the_trait_visibility() {
        // Trait items carry no `pub`; their visibility IS the trait's (like enum variants).
        // Without this, a `pub trait`'s methods sit on the private rung and the duck-typed
        // member fallback filters their cross-file call sites out — the M5 dogfood flagged
        // every `LanguageAdapter` method unused while the engine calls them all.
        let f = facts(
            "pub trait Adapter { fn claim(&self); }\n\
             pub(crate) trait Internal { fn helper(&self); }\n\
             trait Private { fn hidden(&self); }\n",
        );
        let by_name = |n: &str| f.declarations.iter().find(|d| d.name == n).unwrap();
        assert_eq!(by_name("claim").visibility.0, 2);
        assert_eq!(by_name("helper").visibility.0, 1);
        assert_eq!(by_name("hidden").visibility.0, 0);
    }

    #[test]
    fn mod_declarations_are_file_linking_imports() {
        let f = facts("mod plain;\n#[path = \"other/loc.rs\"]\nmod pathed;\nmod inline { pub fn inner() {} }\n");
        let specs: Vec<&str> = f.imports.iter().map(|i| i.specifier.as_str()).collect();
        assert!(specs.contains(&"self::plain"));
        assert!(specs.contains(&"file:other/loc.rs"));
        // inline mod flattened, not imported
        assert!(f.declarations.iter().any(|d| d.name == "inner"));
        let plain = f
            .imports
            .iter()
            .find(|i| i.specifier == "self::plain")
            .unwrap();
        assert!(plain.side_effect_only);
        assert_eq!(plain.local_alias.as_deref(), Some("plain"));
    }

    #[test]
    fn use_shapes_produce_the_contract_emissions() {
        let f = facts(
            "use crate::a::b::Thing;\n\
             use crate::a::{X, Y as Z};\n\
             use crate::deep::*;\n\
             use crate::x as alias;\n\
             pub use crate::a::Reexported;\n\
             use serde::Serialize;\n",
        );
        let single = f
            .imports
            .iter()
            .find(|i| i.specifier == "crate::a::b::Thing")
            .expect("full-path specifier, two-step tail is the resolver's job");
        assert_eq!(single.bindings[0].local.as_str(), "Thing");
        assert_eq!(single.kind, ImportKind::Relative);

        let grouped = f
            .imports
            .iter()
            .find(|i| i.specifier == "crate::a" && !i.bindings.is_empty())
            .unwrap();
        let locals: Vec<&str> = grouped.bindings.iter().map(|b| b.local.as_str()).collect();
        assert_eq!(locals, ["X", "Z"]);
        assert_eq!(grouped.bindings[1].imported.as_deref(), Some("Y"));

        let glob = f
            .imports
            .iter()
            .find(|i| i.specifier == "crate::deep")
            .unwrap();
        assert!(glob.opaque_namespace_use);

        let aliased = f
            .imports
            .iter()
            .find(|i| i.specifier == "crate::x")
            .unwrap();
        assert_eq!(aliased.local_alias.as_deref(), Some("alias"));

        let reexport = f
            .imports
            .iter()
            .find(|i| i.specifier == "crate::a::Reexported")
            .unwrap();
        assert!(reexport.reexported);

        let external = f
            .imports
            .iter()
            .find(|i| i.specifier == "serde::Serialize")
            .unwrap();
        assert_eq!(external.kind, ImportKind::Package);
    }

    #[test]
    fn test_attribute_roots_the_function_and_ffi_roots_production() {
        let f = facts(
            "#[test]\nfn a_test() {}\n\
             #[no_mangle]\npub extern \"C\" fn ffi_entry() {}\n\
             fn plain() {}\n",
        );
        let test_root = f
            .roots
            .iter()
            .find(|r| r.kind == RootKind::Test)
            .expect("#[test] roots");
        assert!(matches!(&test_root.target, RawRootTarget::Declaration(n) if n == "a_test"));
        let ffi_root = f
            .roots
            .iter()
            .find(|r| r.kind == RootKind::Production)
            .expect("FFI export roots");
        assert!(matches!(&ffi_root.target, RawRootTarget::Declaration(n) if n == "ffi_entry"));
        assert_eq!(ffi_root.confidence, Confidence::Probable);
    }

    #[test]
    fn body_references_carry_within_and_qualifiers() {
        let f = facts("fn caller() { helper(); helpers::run(); crate::util::deep_call(); }\n");
        let helper = f.references.iter().find(|r| r.name == "helper").unwrap();
        assert_eq!(helper.within.as_deref(), Some("caller"));
        assert_eq!(helper.kind, RefKind::Call);

        let run = f.references.iter().find(|r| r.name == "run").unwrap();
        assert_eq!(run.scope_context.as_deref(), Some("helpers"));

        // Rooted body path → synthetic import + plain binding reference.
        let deep = f
            .imports
            .iter()
            .find(|i| i.specifier == "crate::util")
            .expect("rooted body path becomes an import");
        assert_eq!(deep.bindings[0].local.as_str(), "deep_call");
        assert!(f.references.iter().any(|r| r.name == "deep_call"));
    }

    #[test]
    fn method_bodies_are_within_the_qualified_member() {
        let f = facts("struct S;\nimpl S { fn m(&self) { helper(); } }\n");
        let helper = f.references.iter().find(|r| r.name == "helper").unwrap();
        assert_eq!(helper.within.as_deref(), Some("S.m"));
    }

    #[test]
    fn impl_trait_for_type_emits_implement() {
        let f = facts("trait Tr { fn m(&self); }\nstruct S;\nimpl Tr for S { fn m(&self) {} }\n");
        assert!(f
            .references
            .iter()
            .any(|r| r.name == "Tr" && r.kind == RefKind::Implement));
    }

    #[test]
    fn derives_reference_their_macros() {
        let f = facts("#[derive(Debug, Serialize)]\nstruct D;\n");
        assert!(f
            .references
            .iter()
            .any(|r| r.name == "Serialize" && r.kind == RefKind::TypeUse));
    }

    #[test]
    fn macro_invocations_reference_the_macro_and_scan_arguments() {
        let f = facts("fn f() { format!(\"{}\", user_count); }\n");
        assert!(f
            .references
            .iter()
            .any(|r| r.name == "format" && r.kind == RefKind::Call));
        assert!(f.references.iter().any(|r| r.name == "user_count"));
    }

    #[test]
    fn include_macro_is_a_probable_file_import() {
        let f = facts("fn f() { include!(\"generated.rs\"); }\n");
        let inc = f
            .imports
            .iter()
            .find(|i| i.specifier == "file:generated.rs")
            .unwrap();
        assert_eq!(inc.confidence, Confidence::Probable);
    }

    #[test]
    fn metrics_cover_functions_and_methods_with_rust_branches() {
        let f = facts(
            "fn gnarly(x: u32) -> u32 {\n\
                 if x > 1 && x < 10 { return 1; }\n\
                 match x { 2 => 2, 3 => 3, _ => 4 }\n\
             }\n\
             struct S;\n\
             impl S { fn m(&self) {} }\n",
        );
        let gnarly = f.functions.iter().find(|m| m.symbol == "gnarly").unwrap();
        // 1 + if + && + 3 match arms = 6
        assert_eq!(gnarly.cyclomatic, 6);
        assert!(f.functions.iter().any(|m| m.symbol == "S.m"));
    }

    #[test]
    fn suppressions_parse_from_line_comments() {
        let f = facts("// kndo:allow unused reason=\"kept for the demo\"\nfn kept() {}\n");
        assert_eq!(f.suppressions.len(), 1);
        assert_eq!(f.suppressions[0].category.as_str(), "unused");
    }

    #[test]
    fn generated_marker_sets_detected_origin() {
        let f = facts("// Code generated by prost. DO NOT EDIT.\npub struct Msg;\n");
        assert_eq!(
            f.detected_origin,
            Some(kndo_core::vocab::FileOrigin::Generated)
        );
        let _ = decl_names(&f);
    }
}
