// @generated by graphql-codegen — DO NOT EDIT.
//
// The banner says who WROTE this file, so what it declares is not judged. It
// says nothing about whether the file earns its place, so the whole-file
// accusation stands as it would for any orphan.
export type Query = { id: number };
