<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.foo</groupId>
    <artifactId>parent</artifactId>
    <version>1.0</version>
  </parent>
  <artifactId>widget-tests</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.foo</groupId>
      <artifactId>widget</artifactId>
    </dependency>
  </dependencies>
</project>
