//! The gate registry — the single source the CI workflow is GENERATED from.
//!
//! v1 kept the invariant list in three hand-synced places (a prose list, the workflow
//! steps, and the grep of `--list`), with a recorded incident: a named gate that had
//! never once passed in CI while appearing in the job list. Here the registry is the
//! only spelling: `cargo xtask gen-ci` renders `.github/workflows/ci.yml` from it, the
//! workflow's existence check greps the same names, and the `generated_ci_is_current`
//! gate fails the build when the committed file and the generator drift. Renaming or
//! deleting a gate without regenerating cannot pass.

use std::path::PathBuf;

pub struct Gate {
    /// The `#[test]` function name in `tests/gates.rs` — checked against `--list`.
    pub name: &'static str,
    /// One line of what the gate protects, rendered into the step name.
    pub invariant: &'static str,
}

pub const GATES: &[Gate] = &[
    Gate {
        name: "generated_ci_is_current",
        invariant: "the committed ci.yml byte-matches the generator",
    },
    Gate {
        name: "contract_fingerprint_is_intentional",
        invariant: "a contract shape change updates fingerprint.txt in the same commit",
    },
    Gate {
        name: "dogfood_kndo_reports_nothing_on_itself",
        invariant: "kndo over this repository reports zero findings",
    },
    Gate {
        name: "warm_and_cold_runs_are_byte_identical",
        invariant: "cached, re-cached and uncached runs serialize identically",
    },
    Gate {
        name: "threads_one_and_many_are_byte_identical",
        invariant: "thread count never changes a byte of output",
    },
    Gate {
        name: "incremental_and_full_assembly_are_byte_identical",
        invariant: "a change replayed over cached evidence equals a from-scratch build",
    },
    Gate {
        name: "a_shared_cache_is_read_and_warmed_across_trees",
        invariant: "a second tree over another tree's cache hits it, adds nothing for identical content, and reports the uncached bytes",
    },
    Gate {
        name: "a_pinned_base_side_reports_the_bytes_of_a_fresh_one",
        invariant: "a persisted base side composes the byte-identical comparison, under its own identity only",
    },
    Gate {
        name: "adapter_conformance_fixtures_are_byte_identical",
        invariant: "the harvested fixture corpus replays to its pinned reports",
    },
    Gate {
        name: "fixture_expectations_hold",
        invariant: "every fixture's expectations.toml holds: dead reported, alive unreported, known gaps still open",
    },
    Gate {
        name: "finding_identity_is_unique",
        invariant: "no two findings in any pinned report share an identity — every subject a file can hold twice carries its position",
    },
    Gate {
        name: "contract_changes_are_loud",
        invariant: "a changed pinned report, fingerprint or graph semantics version is named in DECISIONS.md by the same commits",
    },
    Gate {
        name: "dogfood_zero_means_measured",
        invariant: "every dogfood abstention is accepted in writing — zero cannot cheapen",
    },
    Gate {
        name: "report_schema_is_generated_and_valid",
        invariant: "the committed schema is derived from the types and validates real reports",
    },
    Gate {
        name: "agent_format_matches_its_committed_golden",
        invariant: "the agent render of the everything-specimen report is byte-pinned",
    },
    Gate {
        name: "query_contract_is_generated_and_pinned",
        invariant: "query schemas are derived and valid, the agent render is byte-pinned, and used-by empties exactly where unused accused",
    },
    Gate {
        name: "frontends_import_only_the_facade",
        invariant: "a frontend's production dependencies contain exactly one kndo crate: kndo",
    },
    Gate {
        name: "builtin_conduct_proofs",
        invariant: "every built-in conducting extension proves its effect baseline-then-conduct, closed over the conduct subset of default_extensions",
    },
    Gate {
        name: "extension_dependency_implication",
        invariant: "an extension named in another's dependencies activates even when its own rules never match",
    },
    Gate {
        name: "abi_compat_matrix",
        invariant: "the pinned reference components still run against the HEAD host",
    },
    Gate {
        name: "every_relative_markdown_link_resolves",
        invariant: "a relative Markdown link names a path that exists",
    },
];

/// Repo-relative location of the generated workflow.
pub const WORKFLOW_REPO_PATH: &str = ".github/workflows/ci.yml";

/// Absolute path to the generated workflow, resolved from this crate's location
/// (crates/kndo-gates → the repository root is two levels up).
pub fn workflow_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(WORKFLOW_REPO_PATH)
}

const TEMPLATE: &str = r#"# GENERATED by `cargo xtask gen-ci` from kndo-gates' registry — edits land there,
# never here. The `generated_ci_is_current` gate fails when this file drifts.
name: ci

on:
  push:
    branches: [claude/proyecto-rediseno-greenfield-yg7bjp, main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: lint (fmt, clippy, commit message)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: @TOOLCHAIN@
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt --check
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: conventional commit (HEAD)
        run: |
          subject=$(git log -1 --format=%s)
          echo "$subject"
          case "$subject" in "Merge "*) exit 0;; esac
          echo "$subject" | grep -qE '^(feat|fix|docs|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9,/_-]+\))?!?: .+' \
            || { echo "not a conventional commit"; exit 1; }

  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Windows builds since the SCSS grammar's build script is vendored with
        # its one portable flag (vendor/README.md); a platform the suite never ran
        # on is a platform a tag would meet first.
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: @TOOLCHAIN@
          # The ABI compliance suite builds the reference guests at run time; a
          # toolchain without this target dies with "can't find crate for `core`".
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: cargo test --workspace
        run: cargo test --workspace

  gates:
    name: named gates
    runs-on: ubuntu-latest
    env:
      # The loud-change gate diffs the range this run judges: a pull request's
      # base..head, or the pushed commit against its parent.
      KNDO_LOUD_RANGE: ${{ github.event.pull_request.base.sha && format('{0}..{1}', github.event.pull_request.base.sha, github.event.pull_request.head.sha) || 'HEAD~1..HEAD' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: @TOOLCHAIN@
      - uses: Swatinem/rust-cache@v2
      - name: every named gate still exists
        run: |
          set -eu
          cargo test -p kndo-gates --test gates -- --list > /tmp/gate-list.txt
          missing=""
          for name in @GATE_NAMES@; do
            grep -q "$name" /tmp/gate-list.txt || missing="$missing $name"
          done
          [ -z "$missing" ] || { echo "named gates missing from the harness:$missing"; exit 1; }
@GATE_STEPS@
  docs:
    name: docs site builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install mdBook
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -fsSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz \
            | tar -xz -C "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: mdbook build
        run: mdbook build docs
      - uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          path: docs/book

  deploy-docs:
    name: docs site deploys (main)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  corpus:
    name: corpus is measured and its findings are committed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: @TOOLCHAIN@
      - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v4
        with:
          path: /tmp/kndo-corpus
          key: corpus-${{ hashFiles('corpus/corpus.toml') }}
      - name: clone the pinned corpus
        run: bash corpus/clone.sh /tmp/kndo-corpus
      - name: measure
        run: cargo run --release -p xtask -- corpus --corpus-dir /tmp/kndo-corpus
      - name: the committed measurement matches this code
        run: git diff --exit-code -- corpus-findings/

  package-install:
    name: package + install (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: @TOOLCHAIN@
      - uses: Swatinem/rust-cache@v2
      - name: package, exactly as a release will
        run: cargo run -p xtask -- package --tag v0.0.0-ci --out-dir dist
      - name: verify checksum, install and run from the artifact
        run: cargo run -p xtask -- verify-artifact --dir dist
      # The Linux release artifact is musl — a static binary that runs on any
      # distribution — and the release build is the first time a musl binary
      # would otherwise exist. Built and run here on every push instead.
      - name: package the musl release target
        if: runner.os == 'Linux'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get update && sudo apt-get install -y musl-tools
          cargo run -p xtask -- package --target x86_64-unknown-linux-musl --tag v0.0.0-ci --out-dir dist-musl
          cargo run -p xtask -- verify-artifact --dir dist-musl
          ldd target/x86_64-unknown-linux-musl/release/kndo 2>&1 | grep -Eq "statically linked|not a dynamic executable" \
            || { echo "the musl release binary is not statically linked"; exit 1; }
      # The installer is a contract about the artifact's name and layout; until
      # it runs end to end against the producer's own output, nothing checks it.
      # Served over HTTP so every line it runs for a user runs here.
      - name: install through install.sh from the artifact just built
        if: runner.os != 'Windows'
        run: |
          served=dist; [ "$RUNNER_OS" = "Linux" ] && served=dist-musl
          (cd "$served" && python3 -m http.server 8765 >/dev/null 2>&1 &)
          sleep 1
          KNDO_VERSION=v0.0.0-ci KNDO_BASE_URL=http://127.0.0.1:8765 KNDO_INSTALL_DIR="$RUNNER_TEMP/kndo-bin" sh install.sh
          "$RUNNER_TEMP/kndo-bin/kndo" --version

  release-notes:
    name: release notes render (git-cliff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@v2
        with:
          tool: git-cliff
      - name: the changelog config renders the unreleased commits
        run: git-cliff --config cliff.toml --unreleased --strip header
"#;

/// The pinned toolchain, read from `rust-toolchain.toml` at render time so the
/// workflow and the local pin cannot disagree: one file is the source, the
/// generator copies it.
pub fn toolchain() -> String {
    let text = std::fs::read_to_string(
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../rust-toolchain.toml"),
    )
    .expect("rust-toolchain.toml at the workspace root");
    text.lines()
        .find_map(|l| l.trim().strip_prefix("channel = "))
        .map(|v| v.trim_matches('"').to_string())
        .expect("rust-toolchain.toml declares a channel")
}

pub fn render_ci() -> String {
    let names: Vec<&str> = GATES.iter().map(|g| g.name).collect();
    let steps: String = GATES
        .iter()
        .map(|g| {
            format!(
                "      - name: gate — {} ({})\n        run: cargo test -p kndo-gates --test gates -- --exact {}\n",
                g.name, g.invariant, g.name
            )
        })
        .collect();
    TEMPLATE
        .replace("@GATE_NAMES@", &names.join(" "))
        .replace("@GATE_STEPS@", &steps)
        .replace("@TOOLCHAIN@", &toolchain())
}

/// The release surface's one table: every platform a release publishes, and
/// the artifact's name and layout. The release workflow's build matrix is
/// rendered from it, `xtask package` names its archive by it, and
/// `tests/release_channels.rs` reads the consumers that cannot call Rust —
/// `install.sh`, the Action, the Homebrew template, the install docs — against
/// it, so a channel that drifts fails on the commit that drifts it, not on the
/// tag that ships it.
pub mod release {
    /// One released platform: everything the pipeline and its consumers agree on.
    pub struct Target {
        /// The Rust target triple — also the last field of every artifact name.
        pub triple: &'static str,
        /// The GitHub runner that builds it.
        pub runner: &'static str,
        /// Built through `cross` rather than natively: musl needs it (a real
        /// static binary, independent of the host's glibc, and an aarch64 one
        /// from an x86_64 runner); macOS builds on its own runner.
        pub cross: bool,
        /// `(uname -s, uname -m)` pairs that resolve to this triple — what makes
        /// the installer's and the Action's platform detection checkable: a
        /// triple nothing maps to is a triple nobody can install.
        pub uname: &'static [(&'static str, &'static str)],
    }

    /// Linux is musl, deliberately: a static binary that runs on any
    /// distribution regardless of its glibc. Windows is a CI platform, not a
    /// release target: no consumer maps a Windows platform yet — a `.zip` and a
    /// PowerShell installer are a channel of their own, with their own test.
    pub const TARGETS: &[Target] = &[
        Target {
            triple: "x86_64-unknown-linux-musl",
            runner: "ubuntu-latest",
            cross: true,
            uname: &[("Linux", "x86_64")],
        },
        Target {
            triple: "aarch64-unknown-linux-musl",
            runner: "ubuntu-latest",
            cross: true,
            uname: &[("Linux", "aarch64"), ("Linux", "arm64")],
        },
        Target {
            triple: "x86_64-apple-darwin",
            runner: "macos-latest",
            cross: false,
            uname: &[("Darwin", "x86_64")],
        },
        Target {
            triple: "aarch64-apple-darwin",
            runner: "macos-latest",
            cross: false,
            uname: &[("Darwin", "arm64")],
        },
    ];

    /// The binary's name inside every archive.
    pub const BINARY: &str = "kndo";

    /// The archive's stem — its base name, and the single directory it holds:
    /// `kndo-v1.2.0-aarch64-apple-darwin`. The tag is verbatim, leading `v`
    /// included: that is what `GITHUB_REF_NAME` holds and what the producer
    /// uploads, and a consumer that strips it asks for a file that never was.
    pub fn stem(tag: &str, triple: &str) -> String {
        format!("kndo-{tag}-{triple}")
    }

    /// The archive file name: the stem plus `.tar.gz`. Every archive nests its
    /// contents under the stem, which is why every consumer strips exactly one
    /// leading path component.
    pub fn archive_name(tag: &str, triple: &str) -> String {
        format!("{}.tar.gz", stem(tag, triple))
    }

    /// The Homebrew template's checksum placeholder for one target.
    pub fn sha_placeholder(triple: &str) -> String {
        format!("{{{{SHA256:{triple}}}}}")
    }
}

pub const RELEASE_WORKFLOW_REPO_PATH: &str = ".github/workflows/release.yml";

pub fn release_workflow_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(RELEASE_WORKFLOW_REPO_PATH)
}

const RELEASE_TEMPLATE: &str = r#"# GENERATED by `cargo xtask gen-ci` from kndo-gates' release table — edits land
# there, never here. The `generated_ci_is_current` gate fails when this file drifts.
#
# A `v*` tag publishes; a dispatch with the tag is the escape hatch. The one
# producer of the artifact is `cargo xtask package`: this workflow never builds
# an archive by hand.
name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "The release tag to publish (vX.Y.Z), verbatim"
        required: true

env:
  CARGO_TERM_COLOR: always
  TAG: ${{ inputs.tag || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
@MATRIX@
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: @TOOLCHAIN@
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - name: Install cross
        if: matrix.cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: package through xtask
        run: cargo run -p xtask -- package --target ${{ matrix.target }} ${{ matrix.cross && '--cross' || '' }} --tag "$TAG" --out-dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/*.tar.gz
          if-no-files-found: error

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: checksums over every artifact
        working-directory: dist
        run: sha256sum -- *.tar.gz > checksums.txt
      - uses: taiki-e/install-action@v2
        with:
          tool: git-cliff
      - name: release notes
        run: git-cliff --config cliff.toml --unreleased --tag "$TAG" --strip header -o RELEASE_NOTES.md
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          body_path: RELEASE_NOTES.md
          files: dist/*
          fail_on_unmatched_files: true

  update-tap:
    name: update-tap
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: render the formula from the template
        working-directory: dist
        run: |
          set -eu
          version="${TAG#v}"
          sha() { sha256sum "$1" | awk '{print $1}'; }
          sed -e "s/{{VERSION}}/${version}/g" @SHA_SUBSTITUTIONS@
            ../packaging/homebrew/kndo.rb.tmpl > kndo.rb
      # Needs the tap repository (eulke/homebrew-tap) and a token with push access
      # to it (secrets.HOMEBREW_TAP_TOKEN) — neither is assumed to exist yet.
      - name: push the formula to the tap
        env:
          TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          set -eu
          git clone "https://x-access-token:${TAP_TOKEN}@github.com/eulke/homebrew-tap.git" tap
          mkdir -p tap/Formula
          cp dist/kndo.rb tap/Formula/kndo.rb
          cd tap
          git config user.name "kndo release"
          git config user.email "release@kndo.invalid"
          git add Formula/kndo.rb
          git commit -m "kndo ${{ inputs.tag }}" || true
          git push
"#;

pub fn render_release() -> String {
    let matrix: String = release::TARGETS
        .iter()
        .map(|t| {
            format!(
                "          - target: {}
            os: {}
            cross: {}
",
                t.triple, t.runner, t.cross
            )
        })
        .collect();
    let shas: String = release::TARGETS
        .iter()
        .map(|t| {
            format!(
                "            -e \"s|{}|$(sha \"kndo-${{TAG}}-{}.tar.gz\")|\" \\\n",
                release::sha_placeholder(t.triple),
                t.triple
            )
        })
        .collect();
    RELEASE_TEMPLATE
        .replace("@MATRIX@", matrix.trim_end_matches('\n'))
        .replace("@SHA_SUBSTITUTIONS@", shas.trim_end_matches('\n'))
        .replace("@TOOLCHAIN@", &toolchain())
}
