//! CSS/SCSS extraction, written against tree-sitter-css 0.25.0 and tree-sitter-scss 1.0.0
//! node shapes verified by `parsing`'s `#[ignore]`d ground-truth dumps.
//! One shared walker for both grammars — `tree-sitter-scss` is a strict grammar superset, not a
//! fork with renamed nodes, so dispatch is purely on node *kind*, never on which grammar parsed
//! the tree. Selector/class/id declarations are deliberately not extracted — only
//! custom properties / SCSS variables, mixins, and functions are.

use kndo_adapter_toolkit::classify::{ContentMarkers, LineMarker};
use kndo_adapter_toolkit::parsing::span;
use kndo_core::adapter::{
    Declaration, Diagnostic, DiagnosticLevel, FileFacts, ImportKind, RawImport, RawReference, Span,
    VisibilityLevel,
};
use kndo_core::vocab::{Confidence, FileOrigin, RefKind, SymbolKind};
use rustc_hash::FxHashSet;
use smol_str::SmolStr;
use tree_sitter::Node;

const GENERATED_MARKERS: ContentMarkers = ContentMarkers {
    generated_markers: &[
        LineMarker::Contains("Generated by"),
        LineMarker::Contains("generated by"),
        LineMarker::Contains("DO NOT EDIT"),
    ],
    scan_window_lines: 64,
    comment_openers: &["/*"],
};

/// `within` attribution: `None` everywhere except inside a `@mixin`/`@function`
/// body, where it names that callable — the one place in this adapter a reference belongs to
/// something other than "module load."
struct Ctx<'a> {
    within: Option<&'a str>,
}

type Handler = fn(Node, &[u8], &Ctx<'_>, &mut FxHashSet<SmolStr>, &mut FileFacts);

const HANDLERS: &[(&str, Handler)] = &[
    ("declaration", handle_declaration),
    ("mixin_statement", handle_mixin),
    ("function_statement", handle_function),
    ("include_statement", handle_include),
    ("import_statement", handle_import_like),
    ("use_statement", handle_import_like),
    ("forward_statement", handle_import_like),
    ("call_expression", handle_call),
    ("variable", handle_variable_reference),
];

pub(crate) fn extract(path: &str, content: &[u8]) -> FileFacts {
    let mut out = FileFacts::default();
    if GENERATED_MARKERS.detect_generated(content) {
        out.detected_origin = Some(FileOrigin::Generated);
    }
    let Some(tree) = crate::parsing::parse(path, content) else {
        out.diagnostics.push(Diagnostic {
            level: DiagnosticLevel::Warn,
            path: None,
            message: "failed to initialize the CSS/SCSS parser".to_string(),
            span: None,
        });
        return out;
    };
    let root = tree.root_node();
    if root.has_error() {
        out.diagnostics.push(Diagnostic {
            level: DiagnosticLevel::Warn,
            path: None,
            message: "parse errors — extraction is partial for this file".to_string(),
            span: None,
        });
    }
    let mut seen: FxHashSet<SmolStr> = FxHashSet::default();
    let top = Ctx { within: None };
    walk(root, content, &top, &mut seen, &mut out);
    kndo_adapter_toolkit::suppression::collect_suppressions(
        root,
        content,
        &["comment", "js_comment"],
        &mut out.suppressions,
    );
    out
}

fn walk(node: Node, src: &[u8], ctx: &Ctx<'_>, seen: &mut FxHashSet<SmolStr>, out: &mut FileFacts) {
    if let Some((_, handler)) = HANDLERS.iter().find(|(k, _)| *k == node.kind()) {
        handler(node, src, ctx, seen, out);
        return;
    }
    for child in node.children(&mut node.walk()) {
        walk(child, src, ctx, seen, out);
    }
}

fn walk_children(
    node: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
    skip: &str,
) {
    for child in node.children(&mut node.walk()) {
        if child.kind() != skip {
            walk(child, src, ctx, seen, out);
        }
    }
}

// ---------------------------------------------------------------- declarations: variables

fn is_variable_name(name: &str) -> bool {
    name.starts_with("--") || name.starts_with('$')
}

fn handle_declaration(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
) {
    if let Some(name_node) = find_child(item, "property_name") {
        let name = text(name_node, src);
        if is_variable_name(name) && seen.insert(SmolStr::new(name)) {
            push_declaration(out, name, SymbolKind::CssVariable, item);
        }
    }
    walk_children(item, src, ctx, seen, out, "property_name");
}

// ---------------------------------------------------------------- declarations: mixins & functions

fn handle_mixin(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
) {
    handle_named_callable(
        item,
        src,
        ctx,
        seen,
        out,
        SymbolKind::Other(SmolStr::new("mixin")),
    );
}

fn handle_function(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
) {
    handle_named_callable(item, src, ctx, seen, out, SymbolKind::Function);
}

/// `@mixin`/`@function` share one shape: a `name` field, an optional `parameters` list, a
/// `block` body — both become callable `Declaration`s and both root their own body's
/// `within`.
fn handle_named_callable(
    item: Node,
    src: &[u8],
    _ctx: &Ctx<'_>,
    seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
    kind: SymbolKind,
) {
    let Some(name_node) = item.child_by_field_name("name") else {
        return;
    };
    let name = text(name_node, src);
    if seen.insert(SmolStr::new(name)) {
        push_declaration(out, name, kind, item);
    }
    let inner = Ctx { within: Some(name) };
    if let Some(params) = find_child(item, "parameters") {
        walk(params, src, &inner, seen, out);
    }
    if let Some(body) = find_child(item, "block") {
        walk(body, src, &inner, seen, out);
    }
}

// ---------------------------------------------------------------- references: var()/$name/@include/calls

fn handle_call(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
) {
    if let Some(fname_node) = find_child(item, "function_name") {
        let fname = text(fname_node, src);
        if fname == "var" {
            emit_var_call_reference(item, src, ctx, out);
        } else {
            emit_reference(out, fname, ctx.within, RefKind::Call, span(fname_node));
        }
    }
    walk_children(item, src, ctx, seen, out, "function_name");
}

/// `var(--name, <fallback>)`: the first argument, when it's a custom-property name,
/// is the reference — the fallback (if any) is ordinary value content, walked normally by the
/// generic recursion `handle_call` already does over every non-`function_name` child.
fn emit_var_call_reference(item: Node, src: &[u8], ctx: &Ctx<'_>, out: &mut FileFacts) {
    let Some(args) = find_child(item, "arguments") else {
        return;
    };
    // `arguments`'s children include the anonymous `(`/`)` tokens (tree-sitter's `.children()`
    // walks every child, named or not) — the first *named* child is the real first argument.
    let Some(first) = args.children(&mut args.walk()).find(|c| c.is_named()) else {
        return;
    };
    let name = text(first, src);
    if name.starts_with("--") {
        emit_reference(out, name, ctx.within, RefKind::Read, span(first));
    }
}

fn handle_variable_reference(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    _seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
) {
    emit_reference(out, text(item, src), ctx.within, RefKind::Read, span(item));
}

fn handle_include(
    item: Node,
    src: &[u8],
    ctx: &Ctx<'_>,
    seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
) {
    if let Some(name_node) = find_child(item, "identifier") {
        emit_reference(
            out,
            text(name_node, src),
            ctx.within,
            RefKind::Call,
            span(name_node),
        );
    }
    walk_children(item, src, ctx, seen, out, "identifier");
}

fn emit_reference(
    out: &mut FileFacts,
    name: &str,
    within: Option<&str>,
    kind: RefKind,
    site: Span,
) {
    out.references.push(RawReference {
        name: SmolStr::new(name),
        scope_context: None,
        span: site,
        within: within.map(SmolStr::new),
        kind,
    });
}

// ---------------------------------------------------------------- imports: @import/@use/@forward

/// `@import`/`@use`/`@forward` all reduce to the same shape here: find the first string literal
/// anywhere in the statement's subtree (handles both `@import "x.css";` and `@import
/// url("x.css");`) and emit one side-effect-only `RawImport`. `resolve()` is what
/// actually tells a plain-CSS relative path apart from an SCSS module specifier, via its
/// candidate list — extraction doesn't need to know which at-rule produced the specifier.
fn handle_import_like(
    item: Node,
    src: &[u8],
    _ctx: &Ctx<'_>,
    _seen: &mut FxHashSet<SmolStr>,
    out: &mut FileFacts,
) {
    let Some(specifier) = find_string_value_text(item, src) else {
        return;
    };
    out.imports.push(RawImport {
        specifier: SmolStr::new(specifier),
        kind: ImportKind::Relative,
        span: span(item),
        side_effect_only: true,
        type_only: false,
        confidence: Confidence::Certain,
        bindings: Vec::new(),
        reexported: false,
        opaque_namespace_use: false,
        module_names_visible: false,
        local_alias: None,
    });
}

/// `tree-sitter-css`'s `string_value` wraps a `string_content` child excluding the quotes;
/// `tree-sitter-scss`'s doesn't (verified directly — its `string_value`'s only children are
/// the two anonymous quote tokens), so its *own* text is the fallback, quotes trimmed by hand.
fn find_string_value_text<'a>(node: Node<'a>, src: &'a [u8]) -> Option<&'a str> {
    if node.kind() == "string_value" {
        return Some(match find_child(node, "string_content") {
            Some(content) => text(content, src),
            None => trim_quotes(text(node, src)),
        });
    }
    node.children(&mut node.walk())
        .find_map(|child| find_string_value_text(child, src))
}

fn trim_quotes(s: &str) -> &str {
    s.trim_matches(|c| c == '"' || c == '\'')
}

// ---------------------------------------------------------------- small tree helpers

fn push_declaration(out: &mut FileFacts, name: &str, kind: SymbolKind, item: Node) {
    out.declarations.push(Declaration {
        name: SmolStr::new(name),
        kind,
        span: span(item),
        exported: true,
        visibility: VisibilityLevel(0),
        member_of: None,
        signature_span: None,
        implicitly_invoked: false,
        nested_scope: false,
        visibility_inherited: false,
    });
}

fn find_child<'a>(node: Node<'a>, kind: &str) -> Option<Node<'a>> {
    node.children(&mut node.walk()).find(|n| n.kind() == kind)
}

fn text<'a>(node: Node, src: &'a [u8]) -> &'a str {
    std::str::from_utf8(&src[node.byte_range()]).unwrap_or("")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn css(src: &str) -> FileFacts {
        extract("src/main.css", src.as_bytes())
    }

    fn scss(src: &str) -> FileFacts {
        extract("src/main.scss", src.as_bytes())
    }

    fn decl<'a>(f: &'a FileFacts, name: &str) -> &'a Declaration {
        f.declarations.iter().find(|d| d.name == name).unwrap()
    }

    #[test]
    fn custom_property_declaration_and_var_reference() {
        let f = css(":root {\n    --brand: red;\n}\n.btn {\n    color: var(--brand);\n}\n");
        let d = decl(&f, "--brand");
        assert_eq!(d.kind, SymbolKind::CssVariable);
        let r = f.references.iter().find(|r| r.name == "--brand").unwrap();
        assert_eq!(r.kind, RefKind::Read);
        assert_eq!(r.within, None);
    }

    #[test]
    fn a_var_reference_missing_the_dashes_is_not_a_custom_property_use() {
        // `var(foo)` isn't valid CSS, but extraction shouldn't fabricate a reference from it.
        let f = css(".btn { color: var(foo); }\n");
        assert!(f.references.iter().all(|r| r.name != "foo"));
    }

    #[test]
    fn redeclared_custom_property_keeps_only_the_first_declaration() {
        let f = css(":root { --accent: blue; }\n.dark { --accent: purple; }\n");
        assert_eq!(
            f.declarations
                .iter()
                .filter(|d| d.name == "--accent")
                .count(),
            1
        );
        assert_eq!(decl(&f, "--accent").span.start.0, 1);
    }

    #[test]
    fn import_both_syntactic_forms() {
        let f = css("@import \"base.css\";\n@import url(\"theme.css\");\n");
        let specs: Vec<&str> = f.imports.iter().map(|i| i.specifier.as_str()).collect();
        assert!(specs.contains(&"base.css"));
        assert!(specs.contains(&"theme.css"));
        assert!(f
            .imports
            .iter()
            .all(|i| i.side_effect_only && i.bindings.is_empty()));
    }

    #[test]
    fn scss_variable_declaration_and_bare_reference() {
        let f = scss("$brand: red;\n.btn {\n    color: $brand;\n}\n");
        assert_eq!(decl(&f, "$brand").kind, SymbolKind::CssVariable);
        let r = f.references.iter().find(|r| r.name == "$brand").unwrap();
        assert_eq!(r.kind, RefKind::Read);
    }

    #[test]
    fn scss_mixin_declaration_include_reference_and_within_attribution() {
        let f = scss(
            "@mixin flex-center($gap: 0) {\n\
             \x20   display: flex;\n\
             \x20   gap: $gap;\n\
             }\n\
             .card {\n\
             \x20   @include flex-center(4px);\n\
             }\n",
        );
        let d = decl(&f, "flex-center");
        assert_eq!(d.kind, SymbolKind::Other(SmolStr::new("mixin")));
        let include_ref = f
            .references
            .iter()
            .find(|r| r.name == "flex-center" && r.kind == RefKind::Call)
            .unwrap();
        assert_eq!(include_ref.within, None); // @include sits in a plain rule body
        let gap_ref = f.references.iter().find(|r| r.name == "$gap").unwrap();
        assert_eq!(gap_ref.within.as_deref(), Some("flex-center")); // inside the mixin's own body
    }

    #[test]
    fn scss_function_declaration_and_generic_call_resolve_for_free() {
        let f = scss(
            "@function double($n) {\n\
             \x20   @return $n * 2;\n\
             }\n\
             .box {\n\
             \x20   width: double(4px);\n\
             }\n",
        );
        assert_eq!(decl(&f, "double").kind, SymbolKind::Function);
        assert!(f
            .references
            .iter()
            .any(|r| r.name == "double" && r.kind == RefKind::Call));
    }

    #[test]
    fn scss_use_and_forward_are_extracted_as_imports() {
        let f = scss("@use \"tokens\";\n@forward \"mixins\";\n");
        let specs: Vec<&str> = f.imports.iter().map(|i| i.specifier.as_str()).collect();
        assert!(specs.contains(&"tokens"));
        assert!(specs.contains(&"mixins"));
    }

    #[test]
    fn generated_marker_sets_detected_origin() {
        let f = css("/* Generated by tool X. DO NOT EDIT. */\n.btn { color: red; }\n");
        assert_eq!(f.detected_origin, Some(FileOrigin::Generated));
    }

    #[test]
    fn a_non_comment_line_never_triggers_generated_detection() {
        let f = css(".btn { content: \"Generated by hand\"; }\n");
        assert_eq!(f.detected_origin, None);
    }

    #[test]
    fn suppression_pragma_is_collected() {
        let f = css("/* kndo:allow unused reason=\"template\" */\n.unused-thing { color: red; }\n");
        assert_eq!(f.suppressions.len(), 1);
    }

    #[test]
    fn malformed_content_surfaces_a_diagnostic_not_a_panic() {
        let f = css("{ this is not valid css \n");
        assert_eq!(f.diagnostics.len(), 1);
    }

    #[test]
    fn use_with_alias_is_a_known_upstream_grammar_bug_but_still_recovers_the_specifier() {
        // `tree-sitter-scss` 1.0.0 errors on `as t`, but the
        // `string_value` child survives the partial parse — the specifier still extracts.
        let f = scss("@use \"tokens\" as t;\n");
        assert_eq!(f.diagnostics.len(), 1);
        assert!(f.imports.iter().any(|i| i.specifier == "tokens"));
    }
}
